#!/usr/bin/env python3
"""Fix ALL German names, descriptions, and SEO for 461 calculators."""
import json, os

CALC_DIR = r"C:\Microsaas\obra\src\calculators"

# Mapping: slug -> (name, description)
DE = {
    # === Block 1: Estructuras ===
    "hormigon-masa": ("Betonrechner (unbewehrt)", "Berechnen Sie das Volumen und den Materialbedarf für unbewehrten Beton. Geben Sie Länge, Breite und Dicke Ihrer Bodenplatte ein und erhalten Sie Kubikmeter Beton, Zementsäcke sowie Sand- und Kiesmengen."),
    "hormigon-armado": ("Stahlbeton-Rechner", "Berechnen Sie Stahlbeton mit Bewehrung. Ermitteln Sie Betonvolumen, Stahlbedarf und Schalungsfläche für Stützen, Balken und Wände nach Eurocode 2."),
    "zapata-aislada": ("Einzelfundament-Rechner", "Berechnen Sie Beton und Bewehrungsstahl für Einzelfundamente. Geben Sie die Abmessungen der Stütze und des Fundaments ein."),
    "muro-contencion": ("Stützmauer-Rechner", "Berechnen Sie Betonvolumen und Bewehrungsstahl für Stützmauern. Geben Sie Höhe, Länge und Fundamentabmessungen ein."),
    "pilares-hormigon": ("Stahlbetonstützen-Rechner", "Berechnen Sie Betonvolumen, Bewehrungsstahl und Schalung für Stahlbetonstützen."),
    "vigas-hormigon": ("Stahlbetonbalken-Rechner", "Berechnen Sie Beton und Bewehrung für Unterzüge, Stürze und Ringbalken."),
    "forjado-vigueta": ("Decken-Rechner (Fertigteilträger)", "Berechnen Sie Fertigteilträger, Hohlsteine und Ortbeton für Rippendecken."),
    "losa-hormigon": ("Bodenplatten-Rechner", "Berechnen Sie Beton, Baustahlmatten und Randschalung für Bodenplatten und massive Decken."),
    "cimiento-corrido": ("Streifenfundament-Rechner", "Berechnen Sie Beton und Bewehrung für Streifenfundamente unter tragenden und nichttragenden Wänden."),
    "excavacion-tierra": ("Erdaushub-Rechner", "Berechnen Sie das Aushubvolumen, die Anzahl der LKW-Ladungen und das Gesamtgewicht des Aushubs."),
    
    # === Block 2: Mamposteria ===
    "ladrillo-hueco": ("Lochziegel-Rechner", "Berechnen Sie den Ziegel- und Mörtelbedarf für Mauerwerk mit Lochziegeln. Inklusive Verschnittzuschlag."),
    "ladrillo-cara-vista": ("Verblendziegel-Rechner", "Berechnen Sie Verblendziegel und Fugenmörtel für Sichtmauerwerk mit Abzug für Fenster- und Türöffnungen."),
    "bloque-hormigon": ("Beton-Hohlblockstein-Rechner", "Berechnen Sie Hohlblocksteine und Mörtel für tragende und nichttragende Betonwände."),
    "tabique-pladur": ("Trockenbau-Rechner", "Berechnen Sie Gipskartonplatten, UW/CW-Profile und Schrauben für Ihre Trockenbauwand."),
    "aislamiento-termico": ("Wärmedämmstoff-Rechner", "Berechnen Sie den Dämmstoffbedarf für Wände, Dächer und Böden. Ermitteln Sie U-Wert und Dämmstärke."),
    "revoco-proyectado": ("Spritzputz-Rechner", "Berechnen Sie den Putzbedarf für Außenwände – Spritzputz, Unterputz und Oberputz."),
    "mortero-cemento": ("Zementmörtel-Rechner", "Berechnen Sie das Mischungsverhältnis und die Materialmengen für Zementmörtel (1:3, 1:4 oder 1:6)."),
    "enfoscado-guarnecido": ("Innenputz-Rechner", "Berechnen Sie Grundputz und Feinputz für Innenwände und Decken."),
    "mamposteria-piedra": ("Bruchsteinmauer-Rechner", "Berechnen Sie Bruchsteine und Mörtel für Natursteinmauerwerk, Gartenmauern und Sockel."),
    "cubierta-teja": ("Dachziegel-Rechner", "Berechnen Sie Dachziegel, Firstziegel, Ortgangsteine und Dachlatten für geneigte Dächer."),
    "postes-valla": ("Zaunpfosten-Rechner", "Berechnen Sie Beton, Kies und die Anzahl der benötigten Zaunpfosten für Ihren Gartenzaun."),
    "drywall-calculator": ("Trockenbau-Rechner (US-Einheiten)", "Berechnen Sie Gipskartonplatten, Profile und Schrauben in US-üblichen Einheiten."),
    "retaining-wall-calculator": ("Stützmauer-Rechner (US-Einheiten)", "Berechnen Sie Betonblöcke und Fundament für Ihre Gartenstützmauer."),
    "landscape-rock-calculator": ("Zierkies-Rechner", "Berechnen Sie die benötigte Menge an Zierkies oder Splitt für Ihre Gartenfläche."),
    "sod-turf-calculator": ("Rollrasen-Rechner", "Berechnen Sie die Anzahl der benötigten Rollrasen-Bahnen für Ihren Garten."),
    "mulch-calculator": ("Mulch-Rechner", "Berechnen Sie die benötigte Mulchmenge für Ihre Beete und Gartenflächen."),
    "concrete-steps-calculator": ("Betontreppen-Rechner", "Berechnen Sie Betonvolumen und Bewehrung für Außentreppen aus Beton."),
    "roofing-shingle-calculator": ("Dachschindel-Rechner", "Berechnen Sie die Anzahl der benötigten Dachschindeln für Ihr Schrägdach."),
    
    # === Block 3: Pavimentos ===
    "solado-ceramico": ("Keramikfliesen-Rechner", "Berechnen Sie Fliesen, Kleber und Fugenmörtel für Ihren Keramikboden – inklusive Verschnitt."),
    "porcelanico": ("Feinsteinzeug-Rechner", "Berechnen Sie Feinsteinzeugfliesen und Flexkleber für großformatige Bodenbeläge."),
    "laminado-flotante": ("Laminat-Rechner", "Berechnen Sie Laminatdielen, Trittschalldämmung und Sockelleisten für die schwimmende Verlegung."),
    "parquet-madera": ("Parkett-Rechner", "Berechnen Sie Massivholzparkett, Parkettkleber und Versiegelung für die vollflächige Verklebung."),
    "marmol-granito": ("Natursteinplatten-Rechner", "Berechnen Sie Marmor- oder Granitplatten, Kleber und Fugenmörtel."),
    "terrazo": ("Terrazzo-Rechner", "Berechnen Sie Terrazzoplatten oder fugenlosen Terrazzo-Gussbelag für Ihre Bodenfläche."),
    "azulejo-pared": ("Wandfliesen-Rechner", "Berechnen Sie Wandfliesen, Kleber und Fugenmörtel. Inklusive Abzug für Fenster und Türen."),
    "mosaico": ("Mosaikfliesen-Rechner", "Berechnen Sie Mosaikfliesen auf Matten, Mosaikkleber und Fugenmörtel für Nassräume."),
    "adhesivo-ceramico": ("Fliesenkleber-Rechner", "Berechnen Sie die benötigte Klebermenge für Wand- und Bodenfliesen je nach Zahnspachtel."),
    "lechada-junta": ("Fugenmörtel-Rechner", "Berechnen Sie die Fugenmörtelmenge für Fliesenbeläge je nach Fugengröße und Fugentiefe."),
    "carpet-calculator": ("Teppichboden-Rechner", "Berechnen Sie Teppichboden, Unterlage und Klebeband für Ihren Bodenbelag."),
    "laminate-flooring-calculator": ("Laminatboden-Rechner", "Berechnen Sie Laminat, Unterlagsmatten und Sockelleisten für die schwimmende Verlegung."),
    "grout-calculator": ("Fugenmasse-Rechner", "Berechnen Sie die Fugenmasse für Fliesen und Platten nach amerikanischen Einheiten."),
    "paver-calculator": ("Pflasterstein-Rechner", "Berechnen Sie Pflastersteine, Splitt und Sand für Ihre Einfahrt oder Terrasse."),
    "backsplash-tile-calculator": ("Küchenrückwand-Rechner", "Berechnen Sie die benötigten Fliesen für Ihre Küchenrückwand."),
    
    # === Block 4: Fontaneria ===
    "tuberia-pvc-saneamiento": ("KG-Rohr-Rechner (Abwasser)", "Dimensionieren Sie KG-Abwasserrohre aus PVC für Ihre Hausinstallation nach DIN EN 12056."),
    "tuberia-cobre-pex": ("Trinkwasserrohr-Rechner", "Berechnen Sie den Rohrquerschnitt für Kupfer-, PEX- und Mehrschichtverbundrohre nach DIN 1988."),
    "presion-agua": ("Wasserdruck-Rechner", "Berechnen Sie den verfügbaren Wasserdruck unter Berücksichtigung von geodätischer Höhe und Druckverlusten."),
    "deposito-agua": ("Wassertank-Rechner", "Berechnen Sie das benötigte Speichervolumen für Ihren Trinkwassertank nach Personenzahl und Verbrauch."),
    "calentador-agua": ("Warmwasserbereiter-Rechner", "Berechnen Sie die Leistung und Speichergröße für Durchlauferhitzer oder Warmwasserspeicher."),
    "caldera-gas": ("Gastherme-Rechner", "Berechnen Sie die erforderliche Heizleistung Ihrer Gastherme nach Wohnfläche und Dämmstandard."),
    "radiador-aluminio": ("Heizkörper-Rechner", "Berechnen Sie die Anzahl der Heizkörperglieder und die Gesamtwärmeleistung für Ihre Räume."),
    "suelo-radiante": ("Fußbodenheizung-Rechner", "Berechnen Sie die Heizleistung und den Wasserdurchfluss für Ihre Fußbodenheizung."),
    "riego-goteo": ("Tropfbewässerung-Rechner", "Berechnen Sie Tropferanzahl, Gesamtdurchfluss und Bewässerungskreise für Ihren Garten."),
    "acometida-agua": ("Hausanschluss-Rechner", "Dimensionieren Sie die Wasserzuleitung vom Hauptanschluss bis zum Hauswasserzähler."),
    "depuradora-piscina": ("Poolfilter-Rechner", "Berechnen Sie Umwälzleistung, Filtergröße und Pumpenleistung für Ihre Schwimmbadtechnik."),
    "sifon-sumidero": ("Geruchsverschluss-Rechner", "Berechnen Sie die erforderliche Sperrwasserhöhe und den maximalen Abfluss Ihres Siphons."),
    "volumen-piscina": ("Poolvolumen-Rechner", "Berechnen Sie das Wasservolumen und die benötigte Chlormenge für Ihren Swimmingpool."),
    "tierra-jardin": ("Gartenerde-Rechner", "Berechnen Sie die benötigte Menge an Mutterboden, Kompost und Substrat für Ihren Garten."),
    
    # Block 5 — Electricidad
    "cable-electrico-seccion": ("Kabelquerschnitt-Rechner", "Berechnen Sie den Leitungsquerschnitt nach VDE 0298 — Strombelastbarkeit, Spannungsfall und Kurzschlussschutz."),
    "caida-tension": ("Spannungsfall-Rechner", "Berechnen Sie den Spannungsfall in elektrischen Leitungen nach DIN VDE 0100-520."),
    "luminarias-lumenes": ("Beleuchtungsstärke-Rechner", "Berechnen Sie die benötigten Lumen und die Anzahl der LED-Leuchten für Ihre Raumbeleuchtung nach DIN EN 12464-1."),
    "puntos-luz-habitacion": ("Leuchtenanzahl-Rechner", "Planen Sie die optimale Anzahl und Positionierung von Deckenleuchten pro Raum."),
    "cuadro-electrico": ("Verteiler-Rechner", "Planen Sie Ihren Sicherungskasten: Anzahl der Stromkreise, FI-Schalter und Leitungsschutzschalter."),
    "instalacion-solar": ("Photovoltaik-Rechner", "Berechnen Sie die Anzahl der Solarmodule und die Wechselrichterleistung für Ihre PV-Anlage."),
    "baterias-autonomia": ("Batteriespeicher-Rechner", "Berechnen Sie die Kapazität und Autonomie Ihres Batteriespeichers — netzgekoppelt oder Inselanlage."),
    "trifasica-potencia": ("Drehstrom-Rechner", "Berechnen Sie Wirk-, Schein- und Blindleistung im Drehstromnetz."),
    "puesta-tierra": ("Erdungsanlage-Rechner", "Berechnen Sie den Erdungswiderstand für Tiefenerder, Ringerder oder Fundamenterder nach DIN 18014."),
    "consumo-electrico-mensual": ("Stromverbrauch-Rechner", "Berechnen Sie Ihren monatlichen Stromverbrauch und die jährlichen Stromkosten."),
    
    # Block 6 — Climatizacion
    "aire-acondicionado-btu": ("Klimaanlagen-Rechner", "Berechnen Sie die erforderliche Kühlleistung in BTU/h für Ihre Räume — Faktoren für Fenster, Personen und Wärmequellen."),
    "conductos-aire": ("Lüftungskanal-Rechner", "Berechnen Sie den Kanalquerschnitt und die Strömungsgeschwindigkeit für Ihre Lüftungsanlage."),
    "ventilacion-mecanica": ("Lüftungsanlage-Rechner", "Berechnen Sie den erforderlichen Luftvolumenstrom nach DIN 1946-6 für Wohnungslüftung."),
    "bomba-calor-aerotermia": ("Wärmepumpen-Rechner", "Berechnen Sie die Jahresarbeitszahl (JAZ) und die Stromkosten Ihrer Luft-Wasser-Wärmepumpe."),
    "calculo-cop-eer": ("COP/EER-Rechner", "Berechnen Sie die Effizienz Ihrer Wärmepumpe oder Klimaanlage — COP für Heizen, EER für Kühlen."),
    "dimensionado-conducto": ("Lüftungsrohr-Rechner", "Dimensionieren Sie Wickelfalzrohre nach der Methode der gleichen Reibung (Pa/m)."),
    "rejillas-difusores": ("Luftdurchlass-Rechner", "Berechnen Sie Anströmgeschwindigkeit, freien Querschnitt und Wurfweite für Lüftungsgitter und Diffusoren."),
    "carga-gas-refrigerante": ("Kältemittelfüllmengen-Rechner", "Berechnen Sie die Kältemittelfüllmenge für R32- und R410A-Split-Klimageräte."),
    "insulation-batt-calculator": ("Dämmmatten-Rechner", "Berechnen Sie die Anzahl der benötigten Dämmmatten für Dachboden oder Zwischenwände."),
    
    # Block 7 — Carpinteria
    "ventanas-aluminio-pvc": ("Fenster-Rechner", "Berechnen Sie Fensterfläche, Rahmenumfang und Verglasungsanteil für Alu- oder Kunststofffenster."),
    "puertas-paso": ("Zimmertüren-Rechner", "Berechnen Sie Türblattmaße, Zargen und Türdrücker für Innentüren in Standardgrößen."),
    "puertas-correderas": ("Schiebetüren-Rechner", "Berechnen Sie Laufschienenlänge, benötigte Beschläge und Wandvorbereitung für Schiebetüren."),
    "escalera-madera": ("Holztreppen-Rechner", "Berechnen Sie Steigung, Auftritt und Anzahl der Stufen nach der Schrittmaßregel (2s + a = 63 cm)."),
    "barandilla-metalica": ("Geländer-Rechner", "Berechnen Sie Pfostenabstand, Füllstabanzahl und Materiallängen für Metallgeländer nach DIN 18065."),
    "estructuras-metalicas": ("Stahlbau-Rechner", "Berechnen Sie Profilgewichte für IPE-, HEB- und UPN-Träger sowie den Farbanstrichbedarf."),
    "cerrajeria-puerta": ("Türbeschlag-Rechner", "Berechnen Sie die Zylinderlänge und wählen Sie die passende Sicherheitsstufe für Ihren Türbeschlag."),
    "vidrio-cristal": ("Glasdicken-Rechner", "Ermitteln Sie die erforderliche Glasdicke für Fenster, Türen, Duschkabinen und Geländer."),
    "decking-calculator": ("Terrassendielen-Rechner", "Berechnen Sie die benötigte Anzahl an Terrassendielen und Unterkonstruktionshölzern."),
    "fence-picket-calculator": ("Zaunlatten-Rechner", "Berechnen Sie die Anzahl der Zaunlatten, Querriegel und Pfosten für Ihren Gartenzaun."),
    "crown-molding-calculator": ("Deckenleisten-Rechner", "Berechnen Sie die benötigten Längen an Deckenabschlussleisten (Stuckleisten) pro Raum."),
    "baseboard-calculator": ("Fußleisten-Rechner", "Berechnen Sie die benötigten Meter an Fußleisten für Ihre Räume."),
    
    # Block 8 — Pintura
    "pintura-plastica-paredes": ("Wandfarben-Rechner", "Berechnen Sie den Farbverbrauch in Litern für Innenwände — inklusive Anzahl der Anstriche."),
    "pintura-techo": ("Deckenfarben-Rechner", "Berechnen Sie den Farbverbrauch für Ihre Zimmerdecken mit Abzug für Deckendurchbrüche."),
    "esmalte-sintetico": ("Kunstharzlack-Rechner", "Berechnen Sie den Lackverbrauch für Metall- und Holzbauteile im Innen- und Außenbereich."),
    "barniz-exterior": ("Holzlack-Rechner (Außenbereich)", "Berechnen Sie den Holzschutzlack-Bedarf für Fenster, Türen und Fassaden im Außenbereich."),
    "papel-pintado": ("Tapeten-Rechner", "Berechnen Sie die Anzahl der benötigten Tapetenrollen inklusive Rapportverschnitt."),
    "acabado-texturado": ("Strukturputz-Rechner", "Berechnen Sie den Materialbedarf für Dekorputz, Rollputz oder Modellierputz."),
    "imprimacion-sellador": ("Grundierung-Rechner", "Berechnen Sie die benötigte Menge an Tiefengrund, Haftgrund oder Sperrgrund."),
    "masilla-filler": ("Spachtelmasse-Rechner", "Berechnen Sie den Spachtelbedarf zum Füllen von Rissen, Löchern und Unebenheiten."),
    "lija-abrasivo": ("Schleifmittel-Rechner", "Berechnen Sie den Schleifpapier- oder Schleifvlies-Bedarf nach zu bearbeitender Fläche."),
    "paint-coverage-calculator": ("Farbreichweite-Rechner", "Berechnen Sie, wie viele Quadratmeter Sie mit einem Eimer Farbe streichen können."),
    "wallpaper-calculator": ("Tapeten-Rechner (Rollenware)", "Berechnen Sie Tapetenrollen nach angloamerikanischen Rollenmaßen."),
    
    # Block 9 — Gestion
    "presupuesto-reforma": ("Renovierungsbudget-Rechner", "Erstellen Sie ein detailliertes Budget für Ihre Renovierung — Summieren Sie alle Gewerke mit Einheitspreisen."),
    "precio-hora-trabajo": ("Stundensatz-Rechner (Handwerker)", "Berechnen Sie Ihren Stundensatz aus Lohnkosten, Sozialabgaben, Gemeinkosten und Gewinnmarge."),
    "amortizacion-maquinaria": ("Maschinen-Abschreibung-Rechner", "Berechnen Sie die jährliche Abschreibung Ihrer Baumaschinen — linear oder degressiv."),
    "amortizacion-vehiculo": ("Fahrzeug-Abschreibung-Rechner", "Berechnen Sie den jährlichen Wertverlust Ihres Firmenfahrzeugs mit Kilometerfaktor."),
    "coste-combustible": ("Kraftstoffkosten-Rechner", "Berechnen Sie die Treibstoffkosten für Baustellenfahrten nach Verbrauch, Strecke und Kraftstoffpreis."),
    "dietas-desplazamiento": ("Reisekosten-Rechner", "Berechnen Sie Verpflegungsmehraufwand und Übernachtungskosten für Dienstreisen und Montage."),
    "alquiler-contenedor": ("Containermiete-Rechner", "Berechnen Sie die Kosten für die Anmietung von Baucontainern nach Größe und Mietdauer."),
    "alquiler-andamio": ("Gerüstmiete-Rechner", "Berechnen Sie die Mietkosten für Fassadengerüste und Fahrgerüste nach Fläche und Dauer."),
    "limpieza-obra": ("Baureinigungs-Rechner", "Kalkulieren Sie die Kosten für die Bauendreinigung — Grobreinigung, Feinreinigung und Glasreinigung."),
    "seguro-responsabilidad": ("Betriebshaftpflicht-Rechner", "Schätzen Sie die Jahresprämie für Ihre Bauhaftpflichtversicherung nach Deckungssumme und Risiko."),
    "epi-equipos-proteccion": ("PSA-Kosten-Rechner", "Kalkulieren Sie die Kosten für persönliche Schutzausrüstung für Ihr Baustellenteam."),
    "senalizacion-obra": ("Baustellenbeschilderung-Rechner", "Berechnen Sie die Kosten für die erforderliche Baustellenbeschilderung nach Baustellenverordnung."),
    "rendimiento-diario": ("Tagesleistung-Rechner", "Berechnen Sie die tägliche Arbeitsleistung in m², m³ oder Einheiten für verschiedene Gewerke."),
    "planificacion-gantt": ("Bauzeitenplan-Rechner", "Schätzen Sie die Dauer der einzelnen Bauphasen und erstellen Sie einen groben Bauzeitenplan."),
    "licencias-municipales": ("Baugenehmigungskosten-Rechner", "Schätzen Sie die Kosten für Baugenehmigung, ICIO, Tasa urbanística und andere kommunale Gebühren."),
    "iva-irpf": ("MwSt- und Einkommensteuer-Rechner", "Berechnen Sie Mehrwertsteuer und IRPF-Einbehalt für Rechnungen im Baugewerbe."),
    "prestamo-equipo": ("Maschinenfinanzierung-Rechner", "Berechnen Sie Monatsrate, Zinskosten und Gesamtbetrag für die Finanzierung von Baumaschinen."),
    "margen-beneficio": ("Gewinnspanne-Rechner", "Berechnen Sie die Gewinnspanne aus Einkaufs- und Verkaufspreis — absolut und prozentual."),
    "punto-equilibrio-2": ("Break-Even-Rechner (Baugewerbe)", "Berechnen Sie den Break-Even-Point für Ihr Bauprojekt: Wie viele Einheiten müssen Sie verkaufen, um kostendeckend zu arbeiten?"),
    "consumo-agua-obra": ("Baustellenwasser-Rechner", "Berechnen Sie den Wasserverbrauch und die Wasserkosten für verschiedene Bauphasen."),
    "factor-merma-material": ("Materialverschnitt-Rechner", "Berechnen Sie den tatsächlichen Materialbedarf inklusive Verschnitt-Zuschlag für verschiedene Baustoffe."),
    "coste-mano-obra": ("Arbeitskosten-Rechner", "Kalkulieren Sie die Gesamtkosten für Arbeitskräfte — Lohn, Sozialabgaben, Urlaub und Feiertage."),
    "roi-herramienta": ("Werkzeug-ROI-Rechner", "Berechnen Sie, ab wann sich die Anschaffung eines neuen Werkzeugs oder einer Maschine amortisiert."),
    "countertop-calculator": ("Arbeitsplatten-Rechner", "Berechnen Sie die benötigte Arbeitsplattenfläche und das Material für Ihre Küche."),
    
    # === Block 10: Matematicas ===
    "porcentaje": ("Prozentrechner", "Berechnen Sie den Prozentwert, Prozentsatz oder Grundwert aus zwei gegebenen Größen."),
    "cambio-porcentual": ("Prozentuale Veränderung", "Berechnen Sie die prozentuale Zu- oder Abnahme zwischen zwei Werten."),
    "area-circulo": ("Kreisfläche berechnen", "Berechnen Sie die Fläche und den Umfang eines Kreises aus dem Radius oder Durchmesser."),
    "area-rectangulo": ("Rechteckfläche berechnen", "Berechnen Sie Fläche, Umfang und Diagonale eines Rechtecks aus Länge und Breite."),
    "area-triangulo": ("Dreieckfläche berechnen", "Berechnen Sie die Fläche eines Dreiecks aus Grundseite und Höhe."),
    "area": ("Flächen-Rechner", "Umrechner für Flächeneinheiten — m², cm², km², Hektar, Quadratfuß u.v.m."),
    "pitagoras": ("Satz des Pythagoras", "Berechnen Sie die fehlende Seite eines rechtwinkligen Dreiecks — a² + b² = c²."),
    "regla-de-tres": ("Dreisatz-Rechner", "Lösen Sie proportionale Zuordnungen mit dem einfachen oder umgekehrten Dreisatz."),
    "volumen-cilindro": ("Zylindervolumen berechnen", "Berechnen Sie Volumen, Mantelfläche und Oberfläche eines Zylinders."),
    "volumen-esfera": ("Kugelvolumen berechnen", "Berechnen Sie Volumen und Oberfläche einer Kugel aus dem Radius."),
    "volumen": ("Volumen-Rechner", "Umrechner für Volumeneinheiten — m³, Liter, Gallonen, Kubikfuß u.v.m."),
    "potencias": ("Potenz-Rechner", "Berechnen Sie beliebige Potenzen und wissenschaftliche Notation."),
    "raiz": ("Wurzel-Rechner", "Berechnen Sie Quadratwurzeln, Kubikwurzeln und beliebige n-te Wurzeln."),
    "logaritmo": ("Logarithmus-Rechner", "Berechnen Sie Logarithmen zu beliebiger Basis — log₁₀, ln, ld."),
    "logaritmo-2": ("Logarithmus-Rechner (erweitert)", "Berechnen Sie Logarithmen mit Umkehrfunktion und Basiswechsel."),
    "logaritmo-natural": ("Natürlicher Logarithmus (ln)", "Berechnen Sie den natürlichen Logarithmus und die Exponentialfunktion eˣ."),
    "factorial": ("Fakultät-Rechner", "Berechnen Sie die Fakultät n! = 1 × 2 × 3 × ... × n."),
    "factorial-2": ("Fakultät-Rechner (große Zahlen)", "Berechnen Sie Fakultäten für große n mit wissenschaftlicher Ausgabe."),
    "ecuacion-segundo-grado": ("Quadratische Gleichungen lösen", "Lösen Sie quadratische Gleichungen ax² + bx + c = 0 mit der Mitternachtsformel."),
    "mcm-mcd": ("kgV und ggT berechnen", "Berechnen Sie das kleinste gemeinsame Vielfache und den größten gemeinsamen Teiler."),
    "combinaciones": ("Kombinatorik-Rechner (nCr & nPr)", "Berechnen Sie Kombinationen und Permutationen — n über k."),
    "combinaciones-2": ("Kombinationen ohne Wiederholung", "Berechnen Sie C(n,k) = n! / (k! (n−k)!)."),
    "combinaciones-3": ("Kombinationen mit Wiederholung", "Berechnen Sie Kombinationen mit Zurücklegen."),
    "permutaciones": ("Permutationen ohne Wiederholung", "Berechnen Sie P(n,k) = n! / (n−k)!."),
    "permutaciones-2": ("Permutationen mit Wiederholung", "Berechnen Sie Permutationen, wenn Elemente mehrfach vorkommen."),
    "modulo-complejo": ("Komplexe Zahlen", "Berechnen Sie Betrag und Argument einer komplexen Zahl a + bi."),
    "producto-escalar": ("Skalarprodukt berechnen", "Berechnen Sie das Skalarprodukt zweier Vektoren und den eingeschlossenen Winkel."),
    "producto-vectorial": ("Kreuzprodukt berechnen", "Berechnen Sie das Kreuzprodukt zweier 3D-Vektoren."),
    "magnitud-vector-3d": ("Vektorbetrag (3D)", "Berechnen Sie den Betrag eines Vektors im dreidimensionalen Raum."),
    "valor-absoluto": ("Absolutwert-Rechner", "Berechnen Sie den Absolutwert |x| und den Abstand zum Nullpunkt."),
    "regla-trapecios-integral": ("Trapezregel (Integration)", "Nähern Sie bestimmte Integrale mit der Trapezregel an."),
    "derivada-polinomio": ("Ableitung von Polynomen", "Berechnen Sie die erste und zweite Ableitung eines Polynoms."),
    "determinante-matriz-2x2": ("Determinante (2x2-Matrix)", "Berechnen Sie die Determinante det(A) = ad − bc."),
    "fraction-calculator": ("Bruchrechner", "Addieren, subtrahieren, multiplizieren und dividieren Sie Brüche."),
    "gcf-lcm-calculator": ("ggT und kgV (EN)", "Berechnen Sie den größten gemeinsamen Teiler und das kleinste gemeinsame Vielfache."),
    "prime-factorization": ("Primfaktorzerlegung", "Zerlegen Sie eine Zahl in ihre Primfaktoren."),
    "rounding-calculator": ("Runden-Rechner", "Runden Sie Zahlen auf eine bestimmte Anzahl Dezimalstellen oder signifikante Stellen."),
    "scientific-notation": ("Wissenschaftliche Notation", "Wandeln Sie Zahlen in wissenschaftliche Notation um (a × 10^n)."),
    "circle-calculator": ("Kreis-Rechner (EN)", "Berechnen Sie Radius, Durchmesser, Umfang und Fläche eines Kreises."),
    "rectangle-calculator": ("Rechteck-Rechner (EN)", "Berechnen Sie Fläche, Umfang und Diagonale eines Rechtecks."),
    "right-triangle-calculator": ("Rechtwinkliges Dreieck", "Berechnen Sie Seiten und Winkel im rechtwinkligen Dreieck mit Trigonometrie."),
    "square-calculator": ("Quadrat-Rechner (EN)", "Berechnen Sie Fläche, Umfang und Diagonale eines Quadrats."),
    "sphere-calculator": ("Kugel-Rechner (EN)", "Berechnen Sie Volumen, Oberfläche und Durchmesser einer Kugel."),
    "cylinder-volume": ("Zylindervolumen (EN)", "Berechnen Sie das Volumen eines Zylinders aus Radius und Höhe."),
    "cone-volume": ("Kegelvolumen (EN)", "Berechnen Sie das Volumen eines Kegels aus Radius und Höhe."),
    "pyramid-volume": ("Pyramidenvolumen", "Berechnen Sie das Volumen einer Pyramide aus Grundfläche und Höhe."),
    "heron-triangle-area": ("Dreieckfläche nach Heron", "Berechnen Sie die Dreieckfläche aus allen drei Seitenlängen mit der Heron-Formel."),
    "slope-calculator": ("Steigungs-Rechner", "Berechnen Sie die Steigung einer Geraden aus zwei Punkten."),
    "trapezoid-calculator": ("Trapezflächen-Rechner", "Berechnen Sie die Fläche eines Trapezes aus den beiden parallelen Seiten und der Höhe."),
    "suma-progresion-aritmetica": ("Arithmetische Reihe", "Berechnen Sie die Summe einer arithmetischen Reihe und das n-te Glied."),
    "suma-progresion-geometrica": ("Geometrische Reihe", "Berechnen Sie die Summe einer geometrischen Reihe und das n-te Glied."),
    "suma-aritmetica": ("Arithmetische Summe (kurz)", "Schnellrechner für die Summe arithmetischer Folgen."),
    "suma-geometrica": ("Geometrische Summe (kurz)", "Schnellrechner für die Summe geometrischer Folgen."),
    "media": ("Mittelwert-Rechner", "Berechnen Sie das arithmetische Mittel, den Durchschnitt einer Zahlenreihe."),
    "mediana": ("Median-Rechner", "Berechnen Sie den Median (Zentralwert) einer sortierten Zahlenreihe."),
    "mediana-2": ("Median-Rechner (gruppiert)", "Berechnen Sie den Median aus gruppierten Daten mit Klassenhäufigkeiten."),
    "varianza": ("Varianz-Rechner", "Berechnen Sie die Varianz einer Datenreihe als Maß für die Streuung."),
    "desviacion-estandar": ("Standardabweichung", "Berechnen Sie die Standardabweichung einer Datenreihe (Quadratwurzel der Varianz)."),
    "desviacion-estandar-2": ("Standardabweichung (Stichprobe)", "Berechnen Sie die Stichproben-Standardabweichung mit (n-1)-Korrektur."),
    "varianza-2": ("Stichproben-Varianz", "Berechnen Sie die korrigierte Stichprobenvarianz mit Freiheitsgrad n-1."),
    "cuartiles": ("Quartil-Rechner", "Berechnen Sie Q1, Median und Q3 sowie den Interquartilsabstand."),
    "coeficiente-variacion": ("Variationskoeffizient", "Berechnen Sie den Variationskoeffizienten (Standardabweichung / Mittelwert × 100 %)."),
    "intervalo-confianza": ("Konfidenzintervall-Rechner", "Berechnen Sie das Konfidenzintervall für den Mittelwert bei gegebener Sicherheitswahrscheinlichkeit."),
    "puntuacion-z": ("Z-Wert (Standardisierung)", "Berechnen Sie den z-Wert = (x − μ) / σ."),
    "z-score-percentile": ("Z-Wert zu Perzentil", "Rechnen Sie z-Werte in Perzentile der Standardnormalverteilung um."),
    "probabilidad": ("Wahrscheinlichkeits-Rechner", "Berechnen Sie die Wahrscheinlichkeit von Ereignissen — günstige / mögliche Fälle."),
    "combinations-permutations": ("Kombinationen & Permutationen (EN)", "Berechnen Sie nCr und nPr nach der englischen Formelnotation."),
    "crecimiento-exponencial": ("Exponentielles Wachstum", "Berechnen Sie exponentielles Wachstum oder Zerfall — N(t) = N₀ · e^(kt)."),
    
    # === Block 11: Finanzas ===
    "hipoteca": ("Hypotheken-Rechner", "Berechnen Sie die monatliche Rate, die Gesamtkosten und den Tilgungsplan Ihrer Hypothek."),
    "prestamo": ("Darlehens-Rechner", "Berechnen Sie die monatliche Rate, Zinskosten und Restschuld für Annuitätendarlehen."),
    "interes-compuesto": ("Zinseszins-Rechner", "Berechnen Sie das Endkapital mit Zinseszins — Kₙ = K₀ · (1 + i)^n."),
    "interes-simple": ("Einfacher Zins-Rechner", "Berechnen Sie Zinserträge ohne Zinseszinseffekt — Z = K · i · t."),
    "ahorro-compuesto": ("Sparplan-Rechner", "Berechnen Sie das Endvermögen bei regelmäßigen Einzahlungen mit Zinseszins."),
    "ahorro-universidad": ("Studienspar-Rechner", "Berechnen Sie, wie viel Sie monatlich für das Studium Ihrer Kinder zurücklegen müssen."),
    "plan-jubilacion": ("Rentenplan-Rechner", "Berechnen Sie das benötigte Kapital und die monatliche Sparrate für Ihre Altersvorsorge."),
    "inflacion": ("Inflations-Rechner", "Berechnen Sie, wie die Inflation die Kaufkraft Ihres Geldes über die Jahre verändert."),
    "subida-salarial": ("Gehaltserhöhung-Rechner", "Berechnen Sie die prozentuale oder absolute Gehaltserhöhung und das neue Jahresgehalt."),
    "calculadora-iva": ("Mehrwertsteuer-Rechner", "Berechnen Sie Brutto, Netto und MwSt-Betrag mit wählbarem Steuersatz."),
    "salario-neto": ("Nettolohn-Rechner", "Berechnen Sie Ihr Nettogehalt nach Abzug von Lohnsteuer und Sozialabgaben."),
    "descuento": ("Rabatt-Rechner", "Berechnen Sie den reduzierten Preis und die Ersparnis bei Preisnachlässen."),
    "punto-de-equilibrio": ("Break-Even-Rechner", "Berechnen Sie die Gewinnschwelle — wann Ihre Einnahmen die Kosten decken."),
    "punto-equilibrio": ("Break-Even-Rechner (einfach)", "Schneller Break-Even-Rechner: Fixkosten, variable Kosten und Verkaufspreis."),
    "punto-equilibrio-unidades": ("Break-Even in Stückzahlen", "Berechnen Sie, wie viele Einheiten Sie verkaufen müssen, um Ihre Kosten zu decken."),
    "roi": ("ROI-Rechner", "Berechnen Sie den Return on Investment — (Gewinn / Investition) × 100 %."),
    "amortizacion-prestamo": ("Darlehenstilgung-Rechner", "Berechnen Sie Tilgungsplan, Zinsanteil und Restschuld für Ihr Darlehen."),
    "periodo-recuperacion": ("Amortisationsdauer-Rechner", "Berechnen Sie, wie viele Jahre es dauert, bis sich eine Investition amortisiert."),
    "periodo-recuperacion-2": ("Dynamische Amortisation", "Berechnen Sie die Amortisationsdauer unter Berücksichtigung von Zinsen und Inflation."),
    "tasa-anual-efectiva": ("Effektivzins-Rechner", "Rechnen Sie Nominalzins in Effektivzins um — der tatsächliche Zinssatz nach Gebühren."),
    "tasa-crecimiento-anual-compuesto": ("CAGR-Rechner", "Berechnen Sie die durchschnittliche jährliche Wachstumsrate einer Investition."),
    "tasa-real-retorno": ("Realrendite-Rechner", "Berechnen Sie die inflationsbereinigte Rendite Ihrer Geldanlage."),
    "tasa-capitalizacion": ("Kapitalisierungszins-Rechner", "Berechnen Sie den Cap Rate für Immobilieninvestitionen."),
    "cagr-mensual": ("Monatliche Wachstumsrate", "Berechnen Sie die monatliche Wachstumsrate aus Anfangs- und Endwert."),
    "regla-72": ("72er-Regel-Rechner", "Berechnen Sie, in wie vielen Jahren sich Ihr Kapital bei gegebenem Zinssatz verdoppelt."),
    "rentabilidad-alquiler": ("Mietrendite-Rechner", "Berechnen Sie die Brutto- und Nettomietrendite Ihrer Immobilie."),
    "rentabilidad-dividendo": ("Dividendenrendite-Rechner", "Berechnen Sie die Dividendenrendite — jährliche Dividende je Aktie / Aktienkurs."),
    "retorno-acciones": ("Aktienrendite-Rechner", "Berechnen Sie die Gesamtrendite Ihrer Aktien — Kursgewinn plus Dividenden."),
    "ratio-deuda": ("Schuldenquote-Rechner", "Berechnen Sie Ihre Schuldenquote und bewerten Sie Ihre finanzielle Gesundheit."),
    "ratio-per": ("KGV-Rechner (Kurs-Gewinn-Verhältnis)", "Berechnen Sie das Kurs-Gewinn-Verhältnis einer Aktie für die fundamentale Bewertung."),
    "ratio-sharpe": ("Sharpe-Ratio-Rechner", "Berechnen Sie die risikoadjustierte Rendite Ihrer Anlage mit der Sharpe-Ratio."),
    "valor-actual-anualidad": ("Barwert einer Annuität", "Berechnen Sie den heutigen Wert zukünftiger regelmäßiger Zahlungen."),
    "valor-futuro-anualidad": ("Endwert einer Annuität", "Berechnen Sie den zukünftigen Wert regelmäßiger Einzahlungen mit Zinseszins."),
    "deposito-plazo": ("Festgeld-Rechner", "Berechnen Sie Zinsertrag und Endkapital für Termingelder und Festgeldanlagen."),
    "liquidacion-hipoteca": ("Hypotheken-Ablösung", "Berechnen Sie die Vorfälligkeitsentschädigung und Restschuld bei vorzeitiger Ablösung."),
    "liquidacion-tarjeta-credito": ("Kreditkarten-Tilgung", "Berechnen Sie, wie lange Sie brauchen, um Ihr Kreditkartenguthaben zu tilgen."),
    "prestamo-afordable": ("Finanzierungsrahmen-Rechner", "Berechnen Sie, wie viel Kredit Sie sich bei Ihrem Einkommen maximal leisten können."),
    "necesidades-seguro-vida": ("Lebensversicherungs-Rechner", "Berechnen Sie die empfohlene Versicherungssumme für Ihre Risikolebensversicherung."),
    "wacc": ("WACC-Rechner (Kapitalkosten)", "Berechnen Sie die gewichteten durchschnittlichen Kapitalkosten für die Unternehmensbewertung."),
    "profit-margin": ("Gewinnmarge-Rechner", "Berechnen Sie Bruttomarge, Betriebsmarge und Nettomarge Ihres Unternehmens."),
    "double-discount": ("Doppelrabatt-Rechner", "Berechnen Sie den Endpreis nach zwei aufeinanderfolgenden Rabatten."),
    "rendimiento-equivalente-impuestos": ("Steueräquivalenz-Rendite", "Berechnen Sie die Rendite, die eine steuerpflichtige Anlage bräuchte, um mit einer steuerfreien gleichzuziehen."),
    "dividend-yield": ("Dividendenrendite (EN)", "Quick calculator for dividend yield: annual dividend / stock price × 100."),
    "salary-to-hourly": ("Gehalt in Stundenlohn", "Rechnen Sie Ihr Bruttojahresgehalt in einen effektiven Stundenlohn um."),
    "hourly-to-salary": ("Stundenlohn in Jahresgehalt", "Rechnen Sie Ihren Stundenlohn in ein Bruttojahresgehalt um."),
    "mortgage-calculator": ("Hypotheken-Rechner (EN)", "Calculate monthly payments, total interest and amortization schedule for a fixed-rate mortgage."),
    "savings-calculator": ("Spar-Rechner (EN)", "Calculate the future value of your savings with compound interest."),
    "debt-payoff": ("Schuldentilgung-Rechner", "Berechnen Sie Tilgungsdauer und Zinskosten nach der Schneeball- oder Lawinenmethode."),
    "emergency-fund": ("Notgroschen-Rechner", "Berechnen Sie, wie viel Sie als finanzielles Polster für Notfälle zurücklegen sollten."),
    "npv-calculator": ("Kapitalwert-Rechner (NPV)", "Berechnen Sie den Nettobarwert einer Investition unter Berücksichtigung aller zukünftigen Cashflows."),
    "impuesto-ganancias-capital": ("Kapitalertragsteuer-Rechner", "Berechnen Sie die Steuer auf Gewinne aus Aktien, Immobilien oder Kryptowährungen."),
    "tipo-cambio-comision": ("Währungsrechner mit Gebühr", "Berechnen Sie den erhaltenen Betrag nach Währungsumrechnung abzüglich Bankgebühren."),
    "coste-consumo-electrico": ("Stromkosten-Rechner", "Berechnen Sie die Stromkosten für Haushaltsgeräte aus Leistung und Nutzungsdauer."),
    
    # Block 12 — Salud
    "imc-bmi": ("BMI-Rechner (Body-Mass-Index)", "Berechnen Sie Ihren Body-Mass-Index aus Körpergewicht und Körpergröße und erhalten Sie eine Gewichtsklassifikation nach WHO."),
    "calorias-diarias": ("Kalorienbedarf-Rechner", "Berechnen Sie Ihren täglichen Kalorienbedarf anhand des Grundumsatzes und Ihres Aktivitätslevels."),
    "peso-ideal": ("Idealgewicht-Rechner", "Berechnen Sie Ihr Idealgewicht nach verschiedenen wissenschaftlichen Formeln (Devine, Robinson, Miller, Lorentz)."),
    "agua-diaria": ("Wasserbedarf-Rechner", "Berechnen Sie Ihre empfohlene tägliche Trinkmenge anhand Ihres Körpergewichts und Aktivitätslevels."),
    "agua-diaria-2": ("Wasserbedarf-Rechner (detailliert)", "Detaillierte Berechnung Ihres täglichen Wasserbedarfs nach Körpergewicht, Sport und Klima."),
    "agua-por-peso": ("Wasserbedarf nach Gewicht", "Berechnen Sie Ihre optimale tägliche Trinkmenge pro Kilogramm Körpergewicht."),
    "metabolismo-basal": ("Grundumsatz-Rechner", "Berechnen Sie Ihren Grundumsatz — die Kalorien, die Ihr Körper in völliger Ruhe verbrennt."),
    "tasa-metabolica-basal-mifflin": ("Grundumsatz nach Mifflin-St Jeor", "Berechnen Sie Ihren Grundumsatz mit der genauesten Formel nach ADA-Empfehlung (Mifflin-St Jeor)."),
    "tasa-metabolica-mifflin": ("Grundumsatz Mifflin-St Jeor", "Mifflin-St Jeor Grundumsatz-Berechnung mit detaillierter Ausgabe."),
    "metabolismo-en-reposo": ("Ruhestoffwechsel-Rechner", "Berechnen Sie Ihren Ruheenergieverbrauch — ähnlich dem Grundumsatz unter Laborbedingungen."),
    "gasto-energetico-total": ("Gesamtumsatz-Rechner (TDEE)", "Berechnen Sie Ihren täglichen Gesamtenergieverbrauch aus Grundumsatz × Aktivitätsfaktor."),
    "frecuencia-cardiaca-max": ("Maximalpuls-Rechner", "Berechnen Sie Ihre maximale Herzfrequenz mit verschiedenen Formeln (Haskell, Tanaka, Arena)."),
    "frecuencia-cardiaca-max-salud": ("Maximalpuls (Herzgesundheit)", "Berechnen Sie Ihre maximale Herzfrequenz zur Überwachung Ihrer Herz-Kreislauf-Gesundheit."),
    "frecuencia-cardiaca-karvonen": ("Trainingspuls nach Karvonen", "Berechnen Sie Ihre optimale Trainingsherzfrequenz nach der Karvonen-Formel."),
    "zonas-cardiacas": ("Herzfrequenz-Zonen", "Berechnen Sie Ihre fünf Trainingszonen für optimales Ausdauer- und Intervalltraining."),
    "zonas-frecuencia-cardiaca": ("Trainingszonen (detailliert)", "Detaillierte Herzfrequenz-Zonen mit Trainingsempfehlungen für jede Zone."),
    "heart-rate-zones": ("Heart Rate Zones (EN)", "Calculate your five training heart rate zones for endurance, fat burn, and HIIT training."),
    "horas-sueno": ("Schlafbedarf-Rechner", "Berechnen Sie Ihre optimale Schlafens- und Aufwachzeit basierend auf 90-Minuten-Schlafzyklen."),
    "rango-peso-saludable": ("Gesundes Gewicht (BMI-Bereich)", "Berechnen Sie den gesunden Gewichtsbereich für Ihre Körpergröße nach BMI-Klassifikation."),
    "imc-deportista": ("BMI für Sportler", "Berechnen Sie den korrigierten BMI für Athleten — berücksichtigt höhere Muskelmasse."),
    "bmi-prime": ("BMI-Prime-Rechner", "Berechnen Sie das Verhältnis Ihres BMI zum oberen Normalgewicht (BMI=25)."),
    "grasa-corporal-navy": ("Körperfett-Rechner (US Navy)", "Berechnen Sie Ihren Körperfettanteil mit der Formel der US Navy — nur Umfang messen."),
    "grasa-corporal-marina": ("Körperfett-Rechner (Navy Methode)", "Berechnen Sie Ihren Körperfettanteil mit der Navy-Methode und erhalten Sie Ihre Fitness-Kategorie."),
    "masa-magra": ("Magermasse-Rechner", "Berechnen Sie Ihre fettfreie Körpermasse aus Gesamtgewicht und Körperfettanteil."),
    "porcentaje-grasa": ("Körperfettanteil-Rechner", "Berechnen Sie den prozentualen Körperfettanteil aus verschiedenen Messpunkten."),
    "indice-adiposidad-corporal": ("BAI-Rechner (Körperfettindex)", "Berechnen Sie den Body Adiposity Index als Alternative zum BMI — nur Hüftumfang und Größe."),
    "aumento-peso-embarazo": ("Gewichtszunahme Schwangerschaft", "Berechnen Sie die empfohlene Gewichtszunahme während der Schwangerschaft nach Ihrem Ausgangs-BMI."),
    "fecha-parto": ("Geburtstermin-Rechner", "Berechnen Sie den voraussichtlichen Geburtstermin aus dem ersten Tag der letzten Periode."),
    "calculadora-ovulacion": ("Eisprungkalender", "Berechnen Sie Ihre fruchtbaren Tage und den Eisprung für Kinderwunsch oder natürliche Familienplanung."),
    "percentil-crecimiento-infantil": ("Wachstums-Perzentile (Kinder)", "Berechnen Sie die Wachstumsperzentile Ihres Kindes nach WHO-Referenzkurven."),
    "ingesta-proteica": ("Proteinbedarf-Rechner", "Berechnen Sie Ihre optimale tägliche Proteinzufuhr nach Aktivitätslevel und Trainingsziel."),
    "proteina-diaria": ("Täglicher Proteinbedarf", "Berechnen Sie, wie viele Gramm Protein Sie täglich für Muskelaufbau oder Gewichtsverlust brauchen."),
    "ingesta-fibra": ("Ballaststoffbedarf-Rechner", "Berechnen Sie Ihre empfohlene tägliche Ballaststoffzufuhr für eine gesunde Verdauung."),
    "bmr-harris-benedict": ("Grundumsatz Harris-Benedict", "Berechnen Sie Ihren Grundumsatz mit der Harris-Benedict-Formel (überarbeitet 1984)."),
    "bmr-katch-mcardle": ("Grundumsatz Katch-McArdle", "Berechnen Sie den Grundumsatz aus der Magermasse — genauer für Athleten und Bodybuilder."),
    "tasa-metabolica-basal-mifflin": ("Grundumsatz Mifflin-St Jeor", "Berechnen Sie Ihren Grundumsatz nach der Mifflin-St Jeor-Gleichung — dem wissenschaftlichen Standard."),
    "gasto-energetico-total": ("Gesamtumsatz (TDEE)", "Berechnen Sie Ihren täglichen Gesamtenergieverbrauch mit Aktivitätsfaktoren."),
    "peso-objetivo": ("Zielgewicht-Rechner", "Berechnen Sie die Kaloriendefizit oder -überschuss und die Dauer bis zu Ihrem Wunschgewicht."),
    "weight-loss-percentage": ("Gewichtsverlust in Prozent", "Berechnen Sie Ihren Gewichtsverlust als Prozentsatz des Ausgangsgewichts."),
    "macro-calculator": ("Makronährstoff-Rechner", "Berechnen Sie Ihre optimale Verteilung von Proteinen, Kohlenhydraten und Fetten."),
    "blood-pressure": ("Blutdruck-Rechner", "Klassifizieren Sie Ihren Blutdruck nach AHA/ESC-Richtlinien und berechnen Sie den mittleren arteriellen Druck (MAP)."),
    "waist-hip-ratio": ("Taille-Hüft-Verhältnis (WHR)", "Berechnen Sie Ihr Taille-Hüft-Verhältnis und Ihr kardiovaskuläres Risikoprofil."),
    "waist-height-ratio": ("Taille-Größe-Verhältnis (WHtR)", "Berechnen Sie das Verhältnis Taillenumfang zu Körpergröße — ein starker Prädiktor für Gesundheitsrisiken."),
    "bsa-ideal-weight": ("Körperoberfläche (BSA)", "Berechnen Sie Ihre Körperoberfläche nach Mosteller-Formel — wichtig für Medikamentendosierung."),
    "a1c-estimator": ("HbA1c-Schätzer (Blutzuckerlangzeitwert)", "Schätzen Sie Ihren HbA1c-Wert aus dem durchschnittlichen Blutzuckerwert."),
    "cholesterol-ldl": ("LDL-Cholesterin-Rechner", "Berechnen Sie Ihr LDL-Cholesterin nach der Friedewald-Formel aus Gesamtcholesterin, HDL und Triglyceriden."),
    "aclaramiento-creatinina": ("Kreatinin-Clearance", "Berechnen Sie die glomeruläre Filtrationsrate nach Cockcroft-Gault."),
    "calculadora-edad": ("Altersrechner", "Berechnen Sie Ihr exaktes Alter in Jahren, Monaten, Tagen, Stunden und Minuten."),
    "one-rep-max": ("Maximalkraft-Rechner (1RM)", "Berechnen Sie Ihre Maximalkraft (One-Repetition Maximum) aus Wiederholungszahl und Gewicht."),
    "repeticion-maxima-brzycki": ("1RM-Rechner nach Brzycki", "Berechnen Sie Ihre Maximalkraft mit der Brzycki-Formel: 1RM = Gewicht / (1,0278 − 0,0278 × Wdh.)."),
    "mets-actividad": ("MET-Aktivitätsrechner", "Berechnen Sie den Kalorienverbrauch Ihrer Aktivität anhand des metabolischen Äquivalents (MET)."),
    "calorias-caminar": ("Kalorienverbrauch Gehen", "Berechnen Sie den Kalorienverbrauch beim Spazierengehen oder Walken."),
    "calorias-ejercicio": ("Kalorienverbrauch Sport", "Berechnen Sie den Kalorienverbrauch für verschiedene Sportarten anhand von MET-Werten."),
    "pasos-calorias": ("Schritte in Kalorien", "Rechnen Sie Ihre tägliche Schrittzahl in verbrannte Kalorien um."),
    "vo2-max": ("VO2max-Rechner", "Schätzen Sie Ihre maximale Sauerstoffaufnahme (VO2max) — das Maß für Ihre Ausdauerleistungsfähigkeit."),
    "vo2-max-estimator": ("VO2max-Schätzer", "Erweiterte VO2max-Berechnung aus verschiedenen Leistungstests."),
    
    # Block 13 — Cotidiano
    "propina": ("Trinkgeld-Rechner", "Berechnen Sie das Trinkgeld und den Gesamtbetrag Ihrer Restaurantrechnung — aufteilbar auf Personen."),
    "age-calculator-advanced": ("Altersrechner (erweitert)", "Berechnen Sie Ihr exaktes Alter in Jahren, Monaten, Wochen, Tagen und Minuten zwischen zwei Daten."),
    "diferencia-fechas": ("Datumsdifferenz-Rechner", "Berechnen Sie die Anzahl der Tage, Wochen, Monate und Jahre zwischen zwei Daten."),
    "date-difference": ("Date Difference (EN)", "Calculate the exact number of days, weeks, months and years between any two dates."),
    "prestamo-afordable": ("Finanzierungsrahmen", "Berechnen Sie, wie viel Kredit Sie sich leisten können."),
    "coste-combustible-2": ("Spritkosten-Rechner", "Berechnen Sie die Kraftstoffkosten für Ihre Autofahrt."),
    "coste-sms": ("SMS-Kosten-Rechner", "Berechnen Sie die Kosten für SMS-Nachrichten."),
    "tiempo-lectura": ("Lesezeit-Rechner", "Berechnen Sie die geschätzte Lesezeit für einen Text anhand der Wortanzahl."),
    "tiempo-lectura-2": ("Lesezeit (detailliert)", "Detaillierte Lesezeit-Berechnung mit Angaben in Wörtern pro Minute."),
    "tiempo-descarga": ("Downloadzeit-Rechner", "Berechnen Sie die benötigte Zeit zum Herunterladen einer Datei bei gegebener Internetgeschwindigkeit."),
    "tiempo-transferencia-datos": ("Datenübertragungszeit", "Berechnen Sie die Übertragungsdauer für Datenmengen bei verschiedenen Bandbreiten."),
    "tiempo-actividad": ("Aktivitätsdauer-Rechner", "Berechnen Sie die benötigte Zeit für Aktivitäten bei gegebener Geschwindigkeit."),
    "duracion-bateria": ("Akkulaufzeit-Rechner", "Berechnen Sie die geschätzte Akkulaufzeit Ihres Geräts aus Kapazität und Verbrauch."),
    "brillo-pantalla-nits": ("Bildschirmhelligkeit (Nits)", "Rechnen Sie Helligkeitswerte in cd/m² (Nits) um."),
    "dpi-pantalla": ("DPI-Rechner (Bildschirm)", "Berechnen Sie die Pixeldichte (DPI) Ihres Bildschirms aus Auflösung und Bildschirmdiagonale."),
    "relacion-aspecto": ("Seitenverhältnis-Rechner", "Berechnen Sie das Seitenverhältnis aus Breite und Höhe — z.B. 16:9, 4:3, 21:9."),
    "resolucion-pantalla": ("Bildschirmauflösung-Rechner", "Berechnen Sie Auflösungswerte und Megapixel für gängige Bildschirmformate."),
    "tamano-archivo": ("Dateigrößen-Rechner", "Berechnen Sie die Dateigröße aus Auflösung, Farbtiefe und Komprimierung."),
    "tamano-archivo-video": ("Videodateigröße-Rechner", "Berechnen Sie die geschätzte Dateigröße für Videoaufnahmen."),
    "capacidad-raid": ("RAID-Kapazität-Rechner", "Berechnen Sie die nutzbare Speicherkapazität für RAID 0, 1, 5, 6 und 10."),
    "estimador-datos": ("Datenverbrauch-Schätzer", "Schätzen Sie Ihren monatlichen Datenverbrauch für Streaming, Surfen und Downloads."),
    "palabras-por-minuto": ("Schreibgeschwindigkeit", "Berechnen Sie Ihre Tippgeschwindigkeit in Wörtern pro Minute."),
    "tip-calculator-advanced": ("Trinkgeld-Rechner (EN)", "Advanced tip calculator with bill splitting and service rating."),
    "latencia-ping": ("Ping-Latenz-Rechner", "Berechnen Sie die Signallaufzeit aus der Entfernung und der Lichtgeschwindigkeit."),
    "ancho-banda": ("Bandbreiten-Rechner", "Berechnen Sie die maximal übertragbare Datenmenge pro Zeit aus der Bandbreite."),
    "entropia-contrasena": ("Passwort-Entropie-Rechner", "Berechnen Sie die Entropie und die Sicherheit Ihres Passworts aus Länge und Zeichensatz."),
    "entropia-contrasena-2": ("Passwort-Sicherheit (Bits)", "Berechnen Sie die Passwort-Entropie in Bits und die geschätzte Zeit für einen Brute-Force-Angriff."),
    "generador-contrasenas": ("Passwort-Generator", "Erzeugen Sie sichere Passwörter mit wählbarer Länge und Zeichensatz."),
    "numero-aleatorio": ("Zufallszahl-Generator", "Generieren Sie echte Zufallszahlen in einem gewünschten Wertebereich."),
    "lanzador-dados": ("Würfel-Simulator", "Simulieren Sie das Werfen von mehreren Würfeln und sehen Sie die Ergebnisverteilung."),
    "cara-cruz": ("Münzwurf-Simulator", "Simulieren Sie zufällige Münzwürfe und sehen Sie die Kopf/Zahl-Verteilung."),
    
    # Block 14 — Estadistica
    # Already covered: media, mediana, mediana-2, varianza, varianza-2, 
    # desviacion-estandar, desviacion-estandar-2, cuartiles, coeficiente-variacion,
    # intervalo-confianza, puntuacion-z, z-score-percentile, probabilidad
    "sample-size-confidence": ("Stichprobengröße (Konfidenz)", "Berechnen Sie die erforderliche Stichprobengröße für ein gewünschtes Konfidenzniveau."),
    
    # Block 15 — Ciencia
    "velocidad": ("Geschwindigkeits-Rechner", "Berechnen Sie Geschwindigkeit, Strecke oder Zeit aus den beiden anderen Größen — v = s / t."),
    "aceleracion": ("Beschleunigungs-Rechner", "Berechnen Sie die Beschleunigung aus Geschwindigkeitsänderung und Zeit. a = Δv / Δt."),
    "fuerza": ("Kraft-Rechner (Newton)", "Berechnen Sie die Kraft aus Masse und Beschleunigung — F = m × a."),
    "densidad": ("Dichte-Rechner", "Berechnen Sie die Dichte eines Stoffes aus Masse und Volumen — ρ = m / V."),
    "presion": ("Druck-Rechner", "Berechnen Sie den Druck aus Kraft und Fläche — p = F / A."),
    "energia-cinetica": ("Kinetische Energie", "Berechnen Sie die Bewegungsenergie — E = ½ × m × v²."),
    "energia-potencial": ("Potenzielle Energie", "Berechnen Sie die Lageenergie — E = m × g × h."),
    "energia-potencial-elastica": ("Spannenergie (Feder)", "Berechnen Sie die elastische Energie — E = ½ × k × x²."),
    "trabajo-mecanico": ("Mechanische Arbeit", "Berechnen Sie die Arbeit aus Kraft und Weg — W = F × s."),
    "potencia-electrica": ("Elektrische Leistung", "Berechnen Sie die elektrische Leistung aus Spannung und Stromstärke — P = U × I."),
    "ley-ohm": ("Ohmsches Gesetz", "Berechnen Sie Spannung, Stromstärke oder Widerstand — U = R × I."),
    "ohms-law-power": ("Ohmsches Gesetz & Leistung (EN)", "Calculate voltage, current, resistance and power in DC circuits."),
    "fuerza-centripeta": ("Zentripetalkraft", "Berechnen Sie die Zentripetalkraft — F = m × v² / r = m × ω² × r."),
    "fuerza-gravitatoria": ("Gravitationskraft", "Berechnen Sie die Anziehungskraft zwischen zwei Massen nach Newton."),
    "fuerza-coulomb": ("Coulomb-Kraft", "Berechnen Sie die elektrostatische Kraft zwischen zwei Ladungen."),
    "fuerza-magnetica-carga": ("Lorentz-Kraft", "Berechnen Sie die magnetische Kraft auf eine bewegte Ladung im Magnetfeld."),
    "torque-momento-fuerza": ("Drehmoment-Rechner", "Berechnen Sie das Drehmoment aus Kraft und Hebelarm — M = F × r."),
    "momento-angular": ("Drehimpuls", "Berechnen Sie den Drehimpuls — L = I × ω."),
    "movimiento-proyectil": ("Wurfparabel-Rechner", "Berechnen Sie Flugbahn, Reichweite und maximale Höhe eines schiefen Wurfs."),
    "ecuacion-bernoulli": ("Bernoulli-Gleichung", "Berechnen Sie Druck, Geschwindigkeit und Höhe in einem strömenden Fluid nach Bernoulli."),
    "presion-fluido": ("Hydrostatischer Druck", "Berechnen Sie den Druck in einer ruhenden Flüssigkeit — p = ρ × g × h."),
    "efecto-doppler": ("Doppler-Effekt", "Berechnen Sie die wahrgenommene Frequenz einer bewegten Schallquelle."),
    "efecto-doppler-2": ("Doppler-Effekt (erweitert)", "Doppler-Berechnung mit Unterscheidung zwischen bewegter Quelle und bewegtem Beobachter."),
    "ley-snell": ("Snelliussches Brechungsgesetz", "Berechnen Sie den Brechungswinkel beim Übergang zwischen zwei Medien."),
    "ecuacion-lente-delgada": ("Linsengleichung", "Berechnen Sie Brennweite, Bildweite oder Gegenstandsweite mit der Linsengleichung."),
    "ley-stefan-boltzmann": ("Stefan-Boltzmann-Gesetz", "Berechnen Sie die abgestrahlte Leistung eines schwarzen Körpers — P = σ × A × T⁴."),
    "ley-gases-ideales": ("Ideales Gasgesetz", "Berechnen Sie Druck, Volumen, Temperatur oder Stoffmenge — pV = nRT."),
    "ley-gases-ideales-2": ("Gasgesetz (detailliert)", "Detaillierte Berechnung mit dem idealen Gasgesetz und Einheitenumrechnung."),
    "ley-boyle": ("Boyle-Mariotte-Gesetz", "Berechnen Sie die Volumenänderung bei Druckänderung — p₁V₁ = p₂V₂."),
    "ley-charles": ("Gesetz von Charles", "Berechnen Sie die Volumenänderung bei Temperaturänderung — V₁/T₁ = V₂/T₂."),
    "dilatacion-termica": ("Wärmeausdehnung", "Berechnen Sie die Längen- oder Volumenänderung durch Temperaturänderung."),
    "calor-especifico": ("Spezifische Wärmekapazität", "Berechnen Sie die aufgenommene Wärmemenge — Q = m × c × ΔT."),
    "velocidad-onda": ("Wellengeschwindigkeit", "Berechnen Sie die Ausbreitungsgeschwindigkeit einer Welle — v = λ × f."),
    "frecuencia": ("Frequenz & Periodendauer", "Rechnen Sie Frequenz in Periodendauer um — T = 1 / f."),
    "altitud-presion": ("Luftdruck & Höhe", "Berechnen Sie den Luftdruck in Abhängigkeit von der Höhe über dem Meeresspiegel."),
    "newtons-second-law": ("Newtonsches Bewegungsgesetz", "Berechnen Sie Kraft, Masse oder Beschleunigung nach F = m × a."),
    "kinetic-energy": ("Kinetic Energy (EN)", "Calculate kinetic energy — KE = ½mv²."),
    "potential-energy": ("Potential Energy (EN)", "Calculate gravitational potential energy — PE = mgh."),
    "work-power": ("Work & Power (EN)", "Calculate mechanical work and power from force, distance and time."),
    "circuito-rc": ("RC-Schaltkreis", "Berechnen Sie Zeitkonstante, Lade- und Entladekurve eines RC-Glieds."),
    "circuito-rl": ("RL-Schaltkreis", "Berechnen Sie die Zeitkonstante und den Stromverlauf eines RL-Glieds."),
    "nivel-sonoro-distancia": ("Schallpegel & Entfernung", "Berechnen Sie die Schallpegel-Abnahme mit zunehmender Entfernung."),
    "velocidad-casco": ("Rumpfgeschwindigkeit (Boot)", "Berechnen Sie die theoretische Maximalgeschwindigkeit eines Verdrängerrumpfs."),
    
    # Block 16 — Conversion
    "longitud": ("Längeneinheiten umrechnen", "Rechnen Sie zwischen Metern, Zentimetern, Kilometern, Meilen, Fuß, Zoll und Yards um."),
    "peso": ("Gewicht umrechnen", "Rechnen Sie zwischen Kilogramm, Gramm, Pfund, Unzen und Tonnen um."),
    "temperatura": ("Temperatur umrechnen", "Rechnen Sie zwischen Celsius, Fahrenheit und Kelvin um."),
    "temperature-full": ("Temperatur (alle Einheiten)", "Rechnen Sie zwischen Celsius, Fahrenheit, Kelvin, Rankine und Réaumur um."),
    "volumen": ("Volumeneinheiten umrechnen", "Rechnen Sie Liter, Kubikmeter, Gallonen, Quart und Kubikfuß um."),
    "area": ("Flächeneinheiten umrechnen", "Rechnen Sie Quadratmeter, Hektar, Quadratfuß und Acre um."),
    "energia-unidades": ("Energieeinheiten umrechnen", "Rechnen Sie Joule, Kalorien, Kilowattstunden, BTU und Elektronenvolt um."),
    "energy-converter": ("Energy Unit Converter (EN)", "Convert between joules, calories, kWh, BTU and electron-volts."),
    "presion-unidades": ("Druckeinheiten umrechnen", "Rechnen Sie Pascal, Bar, PSI, Atmosphären und Torr um."),
    "velocidad-unidades": ("Geschwindigkeit umrechnen", "Rechnen Sie m/s, km/h, mph, Knoten und Mach um."),
    "tiempo-unidades": ("Zeiteinheiten umrechnen", "Rechnen Sie Sekunden, Minuten, Stunden, Tage, Wochen und Jahre um."),
    "angle-converter": ("Winkeleinheiten umrechnen", "Rechnen Sie zwischen Grad, Bogenmaß (Radiant), Gon und Neugrad um."),
    "datos-digitales": ("Digitale Einheiten umrechnen", "Rechnen Sie Byte, Kilobyte, Megabyte, Gigabyte und Terabyte um."),
    "frequency-converter": ("Frequenzeinheiten umrechnen", "Rechnen Sie Hertz, Kilohertz, Megahertz und Umdrehungen pro Minute um."),
    "potencia": ("Leistungseinheiten umrechnen", "Rechnen Sie Watt, Kilowatt, Pferdestärken (PS) und BTU/h um."),
    
    # Block 17 — Deportes
    "ritmo-carrera": ("Lauftempo-Rechner", "Berechnen Sie Ihr Lauftempo (min/km) und Ihre Geschwindigkeit (km/h) aus Distanz und Zeit."),
    "ritmo-carrera-2": ("Lauftempo & Geschwindigkeit", "Berechnen Sie Pace und Geschwindigkeit für Ihre Laufstrecken."),
    "ritmo-ciclismo": ("Radfahr-Geschwindigkeit", "Berechnen Sie Ihre Radgeschwindigkeit und Fahrzeit aus Distanz und Tempo."),
    "ritmo-natacion": ("Schwimm-Tempo-Rechner", "Berechnen Sie Ihre Schwimm-Pace pro 100 m und die Gesamtzeit."),
    "quemar-calorias-met": ("Kalorienverbrauch (MET)", "Berechnen Sie den Kalorienverbrauch Ihrer Sportart anhand von MET-Werten."),
    "running-pace-predictor": ("Wettkampfzeit-Prognose", "Prognostizieren Sie Ihre Zielzeiten für verschiedene Distanzen aus Ihrer aktuellen Bestzeit."),
    "vo2-max": ("VO2max-Rechner (Sport)", "Schätzen Sie Ihre maximale Sauerstoffaufnahme (VO2max) — der Goldstandard für die Ausdauer."),
    "vo2-max-estimator": ("VO2max-Schätzer (detailliert)", "Detaillierte VO2max-Berechnung aus Lauftests und Leistungsdaten."),
    "handicap-golf": ("Golf-Handicap-Rechner", "Berechnen Sie Ihr Handicap-Differential nach USGA-Formel aus Score, Course- und Slope-Rating."),
    "tiempo-pista": ("Rundenzeit-Rechner", "Berechnen Sie Ihre Rundengeschwindigkeit und Pace auf der Laufbahn."),
    "peso-molecular": ("Molekulargewichts-Rechner", "Berechnen Sie das Molekulargewicht aus der Summenformel."),
    
    # Block 18 — More stats
    "combinations-permutations": ("Kombinatorik-Rechner", "Berechnen Sie die Anzahl von Kombinationen und Permutationen."),
    "coeficiente-variacion": ("Variationskoeffizient-Rechner", "Berechnen Sie den CV = (s / x̄) × 100%."),
    
    # Misc / Cross-block
    "codigo-colores-resistencia": ("Widerstands-Farbcode", "Lesen Sie den Wert eines Widerstands anhand seiner Farbringe ab."),
    "codigo-colores-resistencia-2": ("Widerstands-Farbcode (4-Band)", "Bestimmen Sie den Widerstandswert aus dem 4-Band-Farbcode."),
    "resistencia-paralelo": ("Parallelschaltung (Widerstände)", "Berechnen Sie den Gesamtwiderstand parallel geschalteter Widerstände."),
    "resistencia-serie": ("Reihenschaltung (Widerstände)", "Berechnen Sie den Gesamtwiderstand in Reihe geschalteter Widerstände."),
    "capacitancia-serie": ("Kondensatoren in Reihe", "Berechnen Sie die Gesamtkapazität von in Reihe geschalteten Kondensatoren."),
    "divisor-tension": ("Spannungsteiler", "Berechnen Sie die Ausgangsspannung eines Spannungsteilers."),
    "divisor-voltaje": ("Spannungsteiler-Rechner", "Berechnen Sie V_out = V_in × R2 / (R1 + R2)."),
    "energia-capacitor": ("Kondensator-Energie", "Berechnen Sie die gespeicherte Energie eines Kondensators — E = ½CU²."),
    "energia-condensador": ("Kondensator-Energie (erweitert)", "Berechnen Sie die Energie und Ladung eines Kondensators."),
    "energia-bobina": ("Spulen-Energie", "Berechnen Sie die gespeicherte magnetische Energie einer Spule — E = ½LI²."),
    "constante-tiempo-rc": ("RC-Zeitkonstante", "Berechnen Sie τ = R × C und die Lade-/Entladezeit."),
    "constante-tiempo-rc-2": ("RC-Zeitkonstante (detailliert)", "Detaillierte Berechnung der RC-Zeitkonstante mit 63%-Wert."),
    "puente-wheatstone": ("Wheatstone-Messbrücke", "Berechnen Sie den unbekannten Widerstand — Rx = R2 × R3 / R1."),
    "puente-wheatstone-2": ("Wheatstone-Brücke (erweitert)", "Detaillierte Berechnung mit Messbrückenspannung."),
    "relacion-transformador": ("Transformator-Berechnung", "Berechnen Sie Spannungs-, Strom- und Windungsverhältnis eines Trafos."),
    "ley-ohm": ("Ohmsches Gesetz", "Berechnen Sie U = R × I, P = U × I."),
    "indice-calor": ("Hitzeindex-Rechner", "Berechnen Sie die gefühlte Temperatur aus Lufttemperatur und Luftfeuchtigkeit."),
    "indice-calor-2": ("Hitzeindex (detailliert)", "Detaillierte Hitzeindex-Berechnung mit Risikostufen."),
    "sensacion-frio-viento": ("Windchill-Rechner", "Berechnen Sie die gefühlte Temperatur bei Wind — Windchill."),
    "sensacion-termica-viento": ("Gefühlte Temperatur (Wind)", "Berechnen Sie die Windchill-Temperatur und das Erfrierungsrisiko."),
    "humedad-relativa": ("Relative Luftfeuchtigkeit", "Berechnen Sie die relative Luftfeuchtigkeit aus Taupunkttemperatur."),
    "humedad-relativa-rocio": ("Taupunkt & Feuchte", "Berechnen Sie den Taupunkt aus Temperatur und relativer Luftfeuchtigkeit."),
    "punto-rocio": ("Taupunkt-Rechner", "Berechnen Sie die Taupunkttemperatur aus Lufttemperatur und Feuchte."),
    "indice-calidad-aire": ("Luftqualitätsindex (AQI)", "Bestimmen Sie den Luftqualitätsindex aus Schadstoffkonzentrationen."),
    "evapotranspiracion": ("Evapotranspiration", "Berechnen Sie die potenzielle Evapotranspiration nach verschiedenen Methoden."),
    "volumen-lluvia": ("Regenwasser-Volumen", "Berechnen Sie das gesammelte Regenwasservolumen von einer Dachfläche."),
    "amanecer-atardecer": ("Sonnenauf- & Untergang", "Bestimmen Sie die Sonnenauf- und Untergangszeiten für einen beliebigen Ort und Datum."),
    "dia-del-ano": ("Tag des Jahres", "Berechnen Sie, der wievielte Tag des Jahres ein bestimmtes Datum ist."),
    "dias-habiles": ("Werktage zwischen Daten", "Berechnen Sie die Anzahl der Arbeitstage zwischen zwei Daten."),
    "numero-semana": ("Kalenderwoche", "Bestimmen Sie die Kalenderwoche für ein beliebiges Datum."),
    "edad-en-dias": ("Alter in Tagen", "Berechnen Sie Ihr Alter in Tagen — z.B. für den 10.000-Tage-Geburtstag."),
    "tiempo-exposicion-uv": ("UV-Expositionszeit", "Berechnen Sie die maximale Sonnenzeit ohne Sonnenbrand anhand des UV-Index."),
    "hex-a-rgb": ("Hex zu RGB Konverter", "Konvertieren Sie Farbwerte zwischen Hexadezimal (#FF6600) und RGB (255, 102, 0)."),
    "contador-caracteres-texto": ("Zeichenzähler", "Zählen Sie Zeichen, Wörter, Zeilen und Absätze in Ihrem Text."),
    "valor-exposicion": ("Belichtungswert (EV)", "Berechnen Sie den Belichtungswert für Ihre Kamera aus Blende, ISO und Verschlusszeit."),
    "profundidad-campo": ("Schärfentiefe-Rechner", "Berechnen Sie die Schärfentiefe für Ihre Kamera aus Blende, Brennweite und Entfernung."),
    "profundidad-campo-2": ("Schärfentiefe (detailliert)", "Detaillierte Schärfentiefe-Berechnung mit Abbildungsmaßstab und Zerstreuungskreis."),
    "numero-guia-flash": ("Leitzahl-Rechner (Blitz)", "Berechnen Sie die Leitzahl für Ihr Blitzgerät — LZ = Blende × Entfernung."),
    "distancia-hiperfocal": ("Hyperfokale Distanz", "Berechnen Sie die hyperfokale Entfernung für maximale Schärfentiefe in der Landschaftsfotografie."),
    "relacion-contraste": ("Kontrastverhältnis", "Berechnen Sie das Kontrastverhältnis Ihres Displays oder Druckerzeugnisses."),
    "suma-decibelios": ("Dezibel-Addition", "Addieren Sie Schallpegel korrekt — dB-Werte werden nicht linear addiert."),
    "viento-cruzado": ("Seitenwind-Rechner", "Berechnen Sie die Seitenwindkomponente für Landungen und Flugplanung."),
    "distancia-ortodromica": ("Luftlinien-Entfernung", "Berechnen Sie die Großkreisentfernung zwischen zwei GPS-Koordinaten."),
    "distancia-frenado": ("Bremsweg-Rechner", "Berechnen Sie Reaktionsweg, Bremsweg und Anhalteweg für Ihr Fahrzeug."),
    "consumo-combustible": ("Kraftstoffverbrauch", "Berechnen Sie den Kraftstoffverbrauch in L/100 km und MPG."),
    "consumo-combustible-2": ("Kraftstoffverbrauch (detailliert)", "Detaillierte Spritverbrauchs-Berechnung mit Kosten und CO2-Ausstoß."),
    "cilindrada-motor": ("Hubraum-Rechner", "Berechnen Sie den Hubraum eines Verbrennungsmotors aus Bohrung, Hub und Zylinderzahl."),
    "presion-neumaticos": ("Reifendruck umrechnen", "Rechnen Sie Reifendruck zwischen bar, PSI und kPa um."),
    "tiempo-vuelo-viento": ("Flugzeit mit Wind", "Berechnen Sie die effektive Flugzeit unter Berücksichtigung von Gegen- oder Rückenwind."),
    "velocidad-verdadera": ("True Airspeed (TAS)", "Berechnen Sie die wahre Fluggeschwindigkeit aus IAS und Flughöhe."),
    
    # Quimica / Electronica / Fotografia etc
    "calculadora-ph": ("pH-Rechner", "Berechnen Sie den pH-Wert aus der Wasserstoffionen-Konzentration — pH = −log₁₀[H⁺]."),
    "calculadora-poh": ("pOH-Rechner", "Berechnen Sie den pOH-Wert aus der Hydroxidionen-Konzentration — pOH = −log₁₀[OH⁻]."),
    "ph-hidrogeno": ("pH-Rechner (aus H⁺)", "Berechnen Sie den pH-Wert direkt aus der H⁺-Konzentration."),
    "masa-molar": ("Molare Masse berechnen", "Berechnen Sie die molare Masse aus der Summenformel."),
    "molaridad": ("Molarität berechnen", "Berechnen Sie die Stoffmengenkonzentration — c = n / V."),
    "molaridad-2": ("Molarität (detailliert)", "Detaillierte Molaritätsberechnung mit Massen und Verdünnungen."),
    "dilucion": ("Verdünnungs-Rechner", "Berechnen Sie Konzentration und Volumen bei Verdünnungen — c₁V₁ = c₂V₂."),
    "dilucion-2": ("Verdünnung (detailliert)", "Detaillierte Verdünnungsberechnung mit Serienverdünnungen."),
    "gas-ideal": ("Ideales Gas", "Berechnen Sie Druck, Volumen, Temperatur und Stoffmenge mit dem idealen Gasgesetz."),
    "energia-libre-gibbs": ("Freie Enthalpie (Gibbs)", "Berechnen Sie ΔG = ΔH − TΔS."),
    "titulacion": ("Titration-Rechner", "Berechnen Sie die Konzentration einer unbekannten Lösung aus dem Titrationsvolumen."),
    "resistencia-led": ("LED-Vorwiderstand", "Berechnen Sie den Vorwiderstand für eine LED — R = (U − Uf) / I."),
    "constante-resorte": ("Federkonstante (Hookesches Gesetz)", "Berechnen Sie die Federkonstante k = F / x und die Spannenergie."),
    "numero-reynolds": ("Reynolds-Zahl", "Berechnen Sie die Reynolds-Zahl Re = ρ × v × L / μ."),
    "deflexion-viga": ("Balkendurchbiegung", "Berechnen Sie die maximale Durchbiegung eines Balkens unter Einzellast."),
    "par-apriete-tornillo": ("Anzugsdrehmoment (Schrauben)", "Berechnen Sie das empfohlene Anzugsdrehmoment — M = K × F × d."),
    "impedancia-ac": ("Wechselstrom-Impedanz", "Berechnen Sie die Impedanz Z = √(R² + (XL − XC)²)."),
    "empuje-arquimedes": ("Archimedisches Prinzip", "Berechnen Sie die Auftriebskraft — F = ρ × V × g."),
    "energia-rotacional": ("Rotationsenergie", "Berechnen Sie die kinetische Energie der Rotation — E = ½ × I × ω²."),
    "momento-inercia": ("Trägheitsmoment", "Berechnen Sie das Massenträgheitsmoment verschiedener geometrischer Körper."),
    "poligono-regular-area": ("Regelmäßiges Vieleck (Fläche)", "Berechnen Sie Fläche und Umfang eines beliebigen regelmäßigen Vielecks."),
    "cono-volumen": ("Kegelvolumen", "Berechnen Sie das Volumen und die Oberfläche eines Kegels."),
    
    # Phase 0 calcs (1050-1099) — already handled above
    "poligono-regular-area": ("Regelmäßiges Vieleck", "Berechnen Sie Fläche und Umfang eines beliebigen regelmäßigen Polygons."),
    "cono-volumen": ("Kegel-Rechner (Volumen)", "Berechnen Sie Volumen und Oberfläche eines geraden Kreiskegels."),
    "suma-aritmetica": ("Arithmetische Summe", "Berechnen Sie die Summe arithmetischer Folgen."),
    "suma-geometrica": ("Geometrische Summe", "Berechnen Sie die Summe geometrischer Folgen."),
    "combinaciones": ("Kombinations-Rechner", "Berechnen Sie Kombinationen und Permutationen (nCr, nPr)."),
    
    # Contaminated calc blocks
    "hipoteca": ("Hypotheken-Rechner", "Berechnen Sie die monatliche Rate, Zinskosten und Tilgungsdauer Ihrer Baufinanzierung."),
    "prestamo-afordable": ("Finanzierungsrahmen-Rechner", "Ermitteln Sie den maximalen Kreditbetrag, den Sie sich bei Ihrem Einkommen leisten können."),
}

# Also generate a standardized description fallback
def make_desc(name, slug, calc_data):
    """Generate a fallback German description."""
    inputs = calc_data.get("inputs", [])
    input_count = len(inputs)
    if input_count >= 3:
        return f"{name}. Geben Sie Ihre Werte ein und erhalten Sie sofort das Ergebnis. Kostenlos und ohne Registrierung."
    elif input_count >= 1:
        inp_names = [i.get("id", "").replace("_", " ") for i in inputs[:2]]
        return f"{name}. Geben Sie {', '.join(inp_names)} ein und erhalten Sie sofort das Ergebnis."
    return f"{name}. Schnelle und präzise Online-Berechnung — kostenlos."

# Process all files
fixed = 0
for filename in sorted(os.listdir(CALC_DIR)):
    if not filename.endswith(".json") or "backup" in filename or "monolithic" in filename:
        continue
    if filename == "calculators.json":
        continue
    
    filepath = os.path.join(CALC_DIR, filename)
    with open(filepath, "r", encoding="utf-8") as f:
        calc = json.load(f)
    
    slug = calc.get("slug", "")
    i18n = calc.get("i18n", {})
    de_data = i18n.get("de", {})
    
    if not isinstance(de_data, dict):
        de_data = {}
    
    if slug in DE:
        name, desc = DE[slug]
    else:
        # Fallback: keep existing name but clean it up
        name = de_data.get("name", slug.replace("-", " ").title())
        desc = make_desc(name, slug, calc)
    
    seo_title = f"{name} | CalcToWork"
    if len(name) > 50:
        seo_title = name[:50] + " | CalcToWork"
    
    de_data["name"] = name
    de_data["desc"] = desc
    de_data["seo_title"] = seo_title
    de_data["seo_desc"] = desc[:160].rsplit(".", 1)[0] + "."
    de_data["seo_description"] = desc[:160].rsplit(".", 1)[0] + "."
    
    calc["i18n"]["de"] = de_data
    
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(calc, f, ensure_ascii=False, indent=2)
    
    fixed += 1

print(f"Fixed {fixed} German entries")
