const fs = require('fs');

const raw = fs.readFileSync('src/calculators/calculators.json', 'utf8');
const data = JSON.parse(raw.replace(/^\uFEFF/, ''));
const calculators = data.calculators;

console.log(`Processing ${calculators.length} calculators...`);

const dict = {
    'Calcular': 'Calcolare', 'calcular': 'calcolare',
    'necesario': 'necessario', 'necesaria': 'necessaria', 'necesarios': 'necessari', 'necesarias': 'necessarie',
    'para': 'per', 'una': 'una', 'un': 'un', 'de': 'di', 'del': 'del', 'de la': 'della',
    'la': 'la', 'las': 'le', 'los': 'i', 'y': 'e', 'con': 'con', 'sin': 'senza',
    'en': 'in', 'por': 'per', 'sobre': 'su', 'según': 'secondo',
    'típica': 'tipica', 'típico': 'tipico', 'típicamente': 'tipicamente',
    'mínimo': 'minimo', 'máximo': 'massimo', 'resistencia': 'resistenza', 'estándar': 'standard',
    'estructural': 'strutturale', 'estructurales': 'strutturali', 'críticos': 'critici',
    'cargas': 'carichi', 'ligeras': 'leggere', 'normales': 'normali', 'pesadas': 'pesanti',
    'hormigón': 'calcestruzzo', 'hormigón armado': 'calcestruzzo armato',
    'cemento': 'cemento', 'arena': 'sabbia', 'grava': 'ghiaia', 'acero': 'acciaio',
    'refuerzo': 'rinforzo', 'madera': 'legno', 'ladrillo': 'mattone', 'ladrillos': 'mattoni',
    'bloque': 'blocco', 'bloques': 'blocchi', 'teja': 'tegola', 'tejas': 'tegole',
    'azulejo': 'piastrella', 'azulejos': 'piastrelle', 'pintura': 'vernice',
    'imprimación': 'primer', 'masilla': 'stucco', 'yeso': 'gesso', 'aislamiento': 'isolamento',
    'lana de vidrio': 'lana di vetro', 'poliestireno': 'polistirene', 'asfalto': 'asfalto',
    'impermeabilizante': 'impermeabilizzante', 'membrana': 'membrana', 'geotextil': 'geotessile',
    'losa': 'lastra', 'losa de cimentación': 'lastra di fondazione', 'cimentación': 'fondazione',
    'zapata': 'plinto', 'zapata aislada': 'plinto isolato', 'zapatas': 'plinti',
    'muro': 'muro', 'muro de contención': 'muro di contenimento', 'pilar': 'pilastro',
    'pilares': 'pilastri', 'viga': 'trave', 'vigas': 'travi', 'techo': 'soffitto',
    'cubierta': 'copertura', 'cimentaciones': 'fondazioni', 'encofrado': 'cassero',
    'cimbra': 'ponteggio', 'columna': 'colonna', 'columnas': 'colonne',
    'largo': 'lunghezza', 'ancho': 'larghezza', 'espesor': 'spessore', 'altura': 'altezza',
    'profundidad': 'profondità', 'diámetro': 'diametro', 'radio': 'raggio', 'área': 'area',
    'volumen': 'volume', 'peso': 'peso', 'masa': 'massa', 'longitud': 'lunghezza',
    'distancia': 'distanza', 'pendiente': 'pendenza', 'inclinación': 'inclinazione',
    'ángulo': 'angolo', 'perímetro': 'perimetro', 'superficie': 'superficie',
    'capacidad': 'capacità', 'cantidad': 'quantità', 'número': 'numero', 'total': 'totale',
    'unitario': 'unitario', 'promedio': 'medio', 'medida': 'misura', 'medidas': 'misure',
    'Multiplicar': 'Moltiplicare', 'multiplicar': 'moltiplicare',
    'Dividir': 'Dividere', 'dividir': 'dividere', 'Sumar': 'Sommmare', 'sumar': 'sommmare',
    'Restar': 'Sottrarre', 'restar': 'sottrarre', 'Determinar': 'Determinare',
    'Estimar': 'Stimare', 'Verificar': 'Verificare', 'Considerar': 'Considerare',
    'Incluir': 'Includere', 'Omitir': 'Omettere', 'Usar': 'Usare', 'Aplicar': 'Applicare',
    'Convertir': 'Convertire', 'requiere': 'richiede', 'se necesitan': 'sono necessari',
    'es necesario': 'è necessario', 'debe ser': 'deve essere', 'puede causar': 'può causare',
    'puede reducir': 'può ridurre', 'ayuda a': 'aiuta a', 'permite': 'permette',
    'facilita': 'facilita', 'mejora': 'migliora', 'reduce': 'riduce', 'aumenta': 'aumenta',
    'No considerar': 'Non considerare', 'no considerar': 'non considerare',
    'No incluir': 'Non includere', 'no incluir': 'non includere',
    'No verificar': 'Non verificare', 'no verificar': 'non verificare',
    'No tener en cuenta': 'Non tenere conto', 'Olvidar': 'Dimenticare',
    'Subestimar': 'Sottostimare', 'Sobreestimar': 'Sovrastimare',
    'Confundir': 'Confondere', 'Ignorar': 'Ignorare', 'Evitar': 'Evitare',
    'Prevenir': 'Prevenire',
    'residencial': 'residenziale', 'residenciales': 'residenziali',
    'comercial': 'commerciale', 'comerciales': 'commerciali',
    'industrial': 'industriale', 'industriales': 'industriali',
    'portante': 'portante', 'capacidad portante': 'capacità portante',
    'suelo': 'terreno', 'tierra': 'terra', 'terreno': 'terreno',
    'base': 'base', 'corona': 'corona', 'superior': 'superiore', 'inferior': 'inferiore',
    'lateral': 'laterale', 'laterales': 'laterali', 'transversal': 'trasversale',
    'longitudinal': 'longitudinale', 'horizontal': 'orizzontale', 'vertical': 'verticale',
    'circular': 'circolare', 'rectangular': 'rettangolare', 'cuadrada': 'quadrata',
    'cuadrado': 'quadrato', 'triangular': 'triangolare', 'trapezoidal': 'trapezoidale',
    'construcción': 'costruzione', 'construir': 'costruire', 'excavación': 'scavo',
    'nivelación': 'livellamento', 'compactación': 'compattazione', 'compactar': 'compattare',
    'vibrado': 'vibrazione', 'curado': 'stagionatura', 'secado': 'asciugatura',
    'mezcla': 'miscela', 'mezclar': 'mescolare', 'preparación': 'preparazione',
    'instalación': 'installazione', 'instalar': 'installare', 'colocación': 'posizionamento',
    'fijación': 'fissaggio', 'unión': 'giunzione', 'corte': 'taglio',
    'perforación': 'foratura', 'acabado': 'finitura', 'acabados': 'finiture',
    'grietas': 'crepe', 'grieta': 'crepa', 'fisuras': 'fessurazioni',
    'defecto': 'difetto', 'defectos': 'difetti', 'error': 'errore', 'errores': 'errori',
    'problema': 'problema', 'problemas': 'problemi', 'falla': 'cedimento',
    'derrames': 'versamenti', 'desperdicio': 'spreco', 'pérdida': 'perdita',
    'daño': 'danno', 'daños': 'danni', 'riesgo': 'rischio', 'riesgos': 'rischi',
    'seguridad': 'sicurezza', 'estabilidad': 'stabilità', 'durabilidad': 'durabilità',
    'resistente': 'resistente', 'resistentes': 'resistenti', 'débil': 'debole',
    'fuerte': 'forte', 'fuertes': 'forti',
    'Correcto': 'Corretto', 'valor': 'valore', 'continuo': 'continuo',
    'decimales': 'decimali', 'entero': 'intero', 'selección': 'selezione',
    'opción': 'opzione', 'texto': 'testo', 'campo': 'campo', 'tipo': 'tipo',
    'recomendado': 'consigliato', 'actual': 'attuale',
    'menos': 'meno', 'más': 'più', 'mayor': 'maggiore', 'menor': 'minore',
    'igual': 'uguale', 'aproximado': 'approssimativo', 'aproximadamente': 'approssimativamente',
    'exacto': 'esatto', 'redondear': 'arrotondare', 'redondeado': 'arrotondato',
    'tiempo': 'tempo', 'día': 'giorno', 'días': 'giorni', 'semana': 'settimana',
    'semanas': 'settimane', 'mes': 'mese', 'meses': 'mesi', 'año': 'anno',
    'años': 'anni', 'hora': 'ora', 'horas': 'ore', 'minuto': 'minuto', 'minutos': 'minuti',
    'necesarios': 'necessari', 'necesarias': 'necessarie', 'disponible': 'disponibile',
    'disponibles': 'disponibili', 'requerido': 'richiesto', 'requeridos': 'richiesti',
    'requerida': 'richiesta', 'requeridas': 'richieste', 'adecuado': 'adeguato',
    'adecuada': 'adeguata', 'adecuados': 'adeguati', 'adecuadas': 'adeguate',
    'óptimo': 'ottimo', 'óptima': 'ottima', 'eficiente': 'efficiente',
    'económico': 'economico', 'económica': 'economica', 'práctico': 'pratico',
    'práctica': 'pratica', 'común': 'comune', 'comunes': 'comuni',
    'frecuente': 'frequente', 'frecuentes': 'frequenti',
    'Medida típica': 'Misura tipica', 'Para': 'Per', 'basado en': 'basato su',
    'Vigas': 'Travi', 'Losas': 'Lastre', 'Cimentaciones': 'Fondazioni',
    'según cargas': 'secondo i carichi', 'según cargas y luces': 'secondo carichi e luci',
    'Para losas': 'Per lastre', 'Para vigas': 'Per travi',
    'recubrimiento': 'copertura', 'recubrimiento mínimo': 'copertura minima',
    'barras': 'barre', 'barras verticales': 'barre verticali',
    'barras horizontales': 'barre orizzontali', 'estribos': 'staffe',
    'separación': 'spaziatura', 'separación excesiva': 'spaziatura eccessiva',
    'juntos': 'insieme', 'extremos': 'estremità', 'longitud de solape': 'lunghezza di sovrapposizione',
    'empalmes': 'giunzioni', 'conectar': 'connettere', 'conexión': 'connessione',
    'espera': 'attesa', 'acero de espera': 'acciaio di attesa', 'solado': 'sottofondo',
    'solado de limpieza': 'sottofondo di pulizia', 'debajo': 'sotto', 'encima': 'sopra',
    'alrededor': 'intorno', 'dentro': 'dentro', 'fuera': 'fuori',
    'exterior': 'esterno', 'interior': 'interno', 'exteriores': 'esterni', 'interiores': 'interni',
    'drenaje': 'drenaggio', 'drenajes': 'drenaggi', 'filtro': 'filtro', 'filtros': 'filtri',
    'detrás': 'dietro', 'delante': 'davanti', 'presión': 'pressione',
    'presión hidrostática': 'pressione idrostatica', 'agua': 'acqua', 'lluvia': 'pioggia',
    'humedad': 'umidità', 'húmedo': 'umido', 'seco': 'secco', 'mojado': 'bagnato',
    'impermeabilización': 'impermeabilizzazione', 'filtración': 'infiltrazione',
    'filtraciones': 'infiltrazioni',
    'inclinar': 'inclinare', 'inclinado': 'inclinato', 'ligera': 'leggera',
    'ligero': 'leggero', 'suave': 'dolce', 'empinada': 'ripida', 'empinado': 'ripido',
    'plano': 'piano', 'plana': 'piana', 'horizontalmente': 'orizzontalmente',
    'verticalmente': 'verticalmente',
    'doble cara': 'doppia faccia', 'una cara': 'una faccia', 'caras': 'facce',
    'lado': 'lato', 'lados': 'lati', 'borde': 'bordo', 'bordes': 'bordi',
    'esquina': 'angolo', 'esquinas': 'angoli', 'soporte': 'supporto',
    'soportes': 'supporti',
    'mezcla de': 'miscela di', 'proporción': 'proporzione', 'relación': 'relazione',
    'agua/cemento': 'acqua/cemento', 'resistencia estándar': 'resistenza standard',
    'clase de': 'classe di', 'categoría': 'categoria', 'categorías': 'categorie',
    'especificación': 'specifica', 'especificaciones': 'specifiche', 'norma': 'norma',
    'normas': 'norme', 'requisito': 'requisito', 'requisitos': 'requisiti',
    'recomendación': 'raccomandazione', 'recomendaciones': 'raccomandazioni',
    'nuevo': 'nuovo', 'nueva': 'nuova', 'nuevos': 'nuovi', 'nuevas': 'nuove',
    'grande': 'grande', 'grandes': 'grandi', 'pequeño': 'piccolo', 'pequeña': 'piccola',
    'pequeños': 'piccoli', 'pequeñas': 'piccole', 'alto': 'alto', 'alta': 'alta',
    'altos': 'alti', 'altas': 'alte', 'bajo': 'basso', 'baja': 'bassa',
    'bajos': 'bassi', 'bajas': 'basse', 'grueso': 'spesso', 'gruesa': 'spessa',
    'gruesos': 'spessi', 'gruesas': 'spesse', 'delgado': 'sottile', 'delgada': 'sottile',
    'delgados': 'sottili', 'delgadas': 'sottili', 'pesado': 'pesante', 'pesada': 'pesante',
    'pesados': 'pesanti', 'pesadas': 'pesanti', 'liviano': 'leggero', 'liviana': 'leggera',
    'livianos': 'leggeri', 'livianas': 'leggere', 'duro': 'duro', 'dura': 'dura',
    'duros': 'duri', 'duras': 'dure', 'blando': 'morbido', 'blanda': 'morbida',
    'blandos': 'morbidi', 'blandas': 'morbide', 'rígido': 'rigido', 'rígida': 'rigida',
    'rígidos': 'rigidi', 'rígidas': 'rigide', 'flexible': 'flessibile',
    'flexibles': 'flessibili', 'frágil': 'fragile', 'frágiles': 'fragili',
    'duradero': 'durevole', 'duradera': 'durevole', 'duraderos': 'durevoli',
    'duraderas': 'durevoli', 'temporal': 'temporaneo', 'temporales': 'temporanei',
    'permanente': 'permanente', 'permanentes': 'permanenti', 'fijo': 'fisso',
    'fija': 'fissa', 'fijos': 'fissi', 'fijas': 'fisse',
    'proyecto': 'progetto', 'proyectos': 'progetti', 'obra': 'opera', 'obras': 'opere',
    'trabajo': 'lavoro', 'trabajos': 'lavori', 'tarea': 'compito', 'tareas': 'compiti',
    'actividad': 'attività', 'proceso': 'processo', 'procesos': 'processi',
    'etapa': 'fase', 'etapas': 'fasi', 'paso': 'passo', 'pasos': 'passi',
    'método': 'metodo', 'métodos': 'metodi', 'técnica': 'tecnica', 'técnicas': 'tecniche',
    'sistema': 'sistema', 'sistemas': 'sistemi', 'estructura': 'struttura',
    'estructuras': 'strutture', 'componente': 'componente', 'componentes': 'componenti',
    'elemento': 'elemento', 'elementos': 'elementi', 'parte': 'parte', 'partes': 'parti',
    'sección': 'sezione', 'secciones': 'sezioni', 'unidad': 'unità', 'unidades': 'unità',
    'grupo': 'gruppo', 'grupos': 'gruppi', 'tipo': 'tipo', 'tipos': 'tipi',
    'clase': 'classe', 'clases': 'classi', 'modelo': 'modello', 'modelos': 'modelli',
    'diseño': 'progetto', 'diseños': 'progetti', 'plan': 'piano', 'planes': 'piani',
    'resultado': 'risultato', 'resultados': 'risultati', 'efecto': 'effetto',
    'efectos': 'effetti', 'causa': 'causa', 'causas': 'cause', 'razón': 'ragione',
    'razones': 'ragioni', 'motivo': 'motivo', 'motivos': 'motivi',
    'objetivo': 'obiettivo', 'objetivos': 'obiettivi', 'función': 'funzione',
    'funciones': 'funzioni', 'uso': 'uso', 'usos': 'usi', 'ventaja': 'vantaggio',
    'ventajas': 'vantaggi', 'desventaja': 'svantaggio', 'desventajas': 'svantaggi',
    'beneficio': 'beneficio', 'beneficios': 'benefici', 'costo': 'costo',
    'costos': 'costi', 'precio': 'prezzo', 'precios': 'prezzi', 'valor': 'valore',
    'valores': 'valori', 'inversión': 'investimento', 'gasto': 'spesa',
    'gastos': 'spese', 'ahorro': 'risparmio', 'ahorros': 'risparmi',
    'pérdidas': 'perdite', 'ganancia': 'guadagno', 'ganancias': 'guadagni',
    'además': 'inoltre', 'también': 'anche', 'sin embargo': 'tuttavia',
    'por lo tanto': 'quindi', 'así': 'così', 'así que': 'quindi', 'entonces': 'allora',
    'luego': 'poi', 'después': 'dopo', 'antes': 'prima', 'mientras': 'mentre',
    'durante': 'durante', 'cuando': 'quando', 'donde': 'dove', 'como': 'come',
    'si': 'se', 'no': 'non', 'sí': 'sì', 'quizás': 'forse', 'tal vez': 'forse',
    'probablemente': 'probabilmente', 'posiblemente': 'possibilmente',
    'seguramente': 'sicuramente', 'realmente': 'realmente', 'actualmente': 'attualmente',
    'generalmente': 'generalmente', 'normalmente': 'normalmente', 'usualmente': 'solitamente',
    'siempre': 'sempre', 'nunca': 'mai', 'a veces': 'a volte', 'casi': 'quasi',
    'solamente': 'solamente', 'solo': 'solo', 'principalmente': 'principalmente',
    'especialmente': 'specialmente', 'particularmente': 'particolarmente',
    'exactamente': 'esattamente', 'correctamente': 'correttamente',
    'completamente': 'completamente', 'totalmente': 'totalmente',
    'parcialmente': 'parzialmente', 'muy': 'molto', 'tan': 'così',
    'tanto': 'tanto', 'demasiado': 'troppo', 'bastante': 'abbastanza',
    'suficiente': 'sufficiente', 'suficientes': 'sufficienti', 'importante': 'importante',
    'importantes': 'importanti', 'esencial': 'essenziale', 'esenciales': 'essenziali',
    'fundamental': 'fondamentale', 'fundamentales': 'fondamentali', 'crítico': 'critico',
    'crítica': 'critica', 'críticos': 'critici', 'críticas': 'critiche', 'vital': 'vitale',
    'vitales': 'vitali', 'obligatorio': 'obbligatorio', 'obligatoria': 'obbligatoria',
    'opcional': 'opzionale', 'opcionales': 'opzionali',
    'recomendado': 'raccomandato', 'recomendada': 'raccomandata',
    'recomendados': 'raccomandati', 'recomendadas': 'raccomandate',
    'mampostería': 'muratura', 'albañilería': 'muratura', 'revoque': 'intonaco',
    'enlucido': 'intonaco', 'friso': 'fregio', 'cornisa': 'cornice',
    'zócalo': 'zoccolo', 'rodapié': 'battiscopa', 'umbral': 'soglia',
    'dintel': 'architrave', 'pedestal': 'piedistallo', 'cimiento': 'fondazione',
    'cimientos': 'fondazioni', 'subsuelo': 'sottosuolo', 'estrato': 'strato',
    'estratos': 'strati', 'capa': 'strato', 'capas': 'strati',
    'nivel freático': 'falda acquifera', 'agua subterránea': 'acqua sotterranea',
    'roca': 'roccia', 'rocas': 'rocce', 'piedra': 'pietra', 'piedras': 'pietre',
    'gravilla': 'ghiaia', 'arcilla': 'argilla', 'limo': 'limo',
    'relleno': 'riempimento', 'rellenos': 'riempimenti', 'compactado': 'compattato',
    'compactada': 'compattata', 'suelto': 'sciolto', 'suelta': 'sciolta',
    'denso': 'denso', 'densa': 'densa', 'densos': 'densi', 'densas': 'dense',
    'poroso': 'poroso', 'porosa': 'porosa', 'porosos': 'porosi', 'porosas': 'porose',
    'permeable': 'permeabile', 'permeables': 'permeabili', 'impermeable': 'impermeabile',
    'impermeables': 'impermeabili', 'transpirable': 'traspirante',
    'transpirables': 'traspiranti', 'ventilado': 'ventilato', 'ventilada': 'ventilata',
    'ventilados': 'ventilati', 'ventiladas': 'ventilate', 'ventilación': 'ventilazione',
    'aireación': 'aerazione', 'circulación': 'circolazione', 'flujo': 'flusso',
    'flujos': 'flussi', 'corriente': 'corrente', 'corrientes': 'correnti',
    'caudal': 'portata', 'caudales': 'portate', 'velocidad': 'velocità',
    'aceleración': 'accelerazione', 'fuerza': 'forza', 'fuerzas': 'forze',
    'carga': 'carico', 'carga muerta': 'carico morto', 'carga viva': 'carico vivo',
    'carga permanente': 'carico permanente', 'carga temporal': 'carico temporaneo',
    'carga estática': 'carico statico', 'carga dinámica': 'carico dinamico',
    'sobrecarga': 'sovraccarico', 'sobrecargas': 'sovraccarichi',
    'peso propio': 'peso proprio', 'carga de': 'carico di', 'carga sobre': 'carico su',
    'distribución': 'distribuzione', 'distribuido': 'distribuito',
    'distribuida': 'distribuita', 'distribuidos': 'distribuiti',
    'distribuidas': 'distribuite', 'concentrado': 'concentrato',
    'concentrada': 'concentrata', 'concentrados': 'concentrati',
    'concentradas': 'concentrate', 'uniforme': 'uniforme', 'uniformes': 'uniformi',
    'variable': 'variabile', 'variables': 'variabili', 'constante': 'costante',
    'constantes': 'costanti',
    'tejado': 'tetto', 'techos': 'tetti', 'cobertura': 'copertura',
    'teja cerámica': 'tegola in ceramica', 'teja de barro': 'tegola in argilla',
    'teja de hormigón': 'tegola in calcestruzzo', 'teja metálica': 'tegola metallica',
    'teja asfáltica': 'tegola bituminosa', 'teja de pizarra': 'tegola in ardesia',
    'cumbrera': 'colmo', 'caballete': 'colmo', 'limahoya': 'canale di gronda',
    'limatesa': 'spigolo', 'aguada': 'gronda', 'alero': 'gronda', 'aleros': 'gronde',
    'canalón': 'grondaia', 'canalones': 'grondaie', 'bajante': 'pluviale',
    'bajantes': 'pluviali', 'desagüe': 'scarico', 'desagües': 'scarichi',
    'vertiente': 'versante', 'vertientes': 'versanti', 'faldón': 'falda',
    'faldones': 'falde', 'aguas abajo': 'a valle', 'aguas arriba': 'a monte',
    'barlovento': 'sopravento', 'sotavento': 'sottovento',
    'estructura del techo': 'struttura del tetto', 'armazón': 'intelaiatura',
    'armadura': 'armatura', 'armaduras': 'armature', 'cercha': 'capriata',
    'cerchas': 'capriate', 'viga maestra': 'trave maestra', 'correa': 'corrente',
    'correas': 'correnti', 'cabio': 'travicello', 'cabios': 'travicelli',
    'listón': 'listello', 'listones': 'listelli', 'entablado': 'tavolato',
    'tabla': 'tavola', 'tablas': 'tavole', 'metal': 'metallo', 'metales': 'metalli',
    'hierro': 'ferro', 'aluminio': 'alluminio', 'cobre': 'rame', 'zinc': 'zinco',
    'plomo': 'piombo', 'acero inoxidable': 'acciaio inossidabile',
    'acero galvanizado': 'acciaio galvanizzato',
    'ventana': 'finestra', 'ventanas': 'finestre', 'puerta': 'porta',
    'puertas': 'porte', 'marco': 'telaio', 'marcos': 'telai', 'hoja': 'anta',
    'hojas': 'ante', 'vidrio': 'vetro', 'vidrios': 'vetri', 'cristal': 'vetro',
    'cristales': 'vetri', 'doble acristalamiento': 'doppio vetro',
    'triple acristalamiento': 'triplo vetro', 'aislamiento térmico': 'isolamento termico',
    'aislamiento acústico': 'isolamento acustico', 'persiana': 'persiana',
    'persianas': 'persiane', 'contraventana': 'imposta', 'contraventanas': 'imposte',
    'postigo': 'imposta', 'postigos': 'imposte', 'estor': 'tenda', 'estores': 'tende',
    'cortina': 'tenda', 'cortinas': 'tende', 'veneciana': 'veneziana',
    'venecianas': 'veneziane', 'mosquitero': 'zanzariera',
    'mosquiteros': 'zanzariere', 'cerradura': 'serratura', 'cerraduras': 'serrature',
    'llave': 'chiave', 'llaves': 'chiavi', 'manija': 'maniglia', 'manijas': 'maniglie',
    'tirador': 'maniglia', 'tiradores': 'maniglie', 'pomo': 'pomello',
    'pomos': 'pomelli', 'bisagra': 'cerniera', 'bisagras': 'cerniere',
    'gozne': 'cardine', 'goznes': 'cardini', 'burlete': 'guarnizione',
    'burletes': 'guarnizioni', 'juntas': 'guarnizioni',
    'suelos': 'pavimenti', 'piso': 'pavimento', 'pisos': 'pavimenti',
    'pavimento': 'pavimento', 'pavimentos': 'pavimenti', 'suelo de': 'pavimento di',
    'pavimento de': 'pavimento di', 'parquet': 'parquet', 'parqués': 'parquet',
    'tarima': 'parquet', 'tarimas': 'parquet', 'lamina': 'laminato',
    'laminado': 'laminato', 'laminados': 'laminati', 'moqueta': 'moquette',
    'alfombra': 'moquette', 'alfombras': 'moquette', 'baldosa': 'piastrella',
    'baldosas': 'piastrelle', 'cerámica': 'ceramica', 'cerámicas': 'ceramiche',
    'porcelánico': 'gres', 'porcelánica': 'gres', 'porcelánicos': 'gres',
    'porcelánicas': 'gres', 'terrazo': 'terrazzo', 'mármol': 'marmo',
    'granito': 'granito', 'piedra natural': 'pietra naturale', 'pizarra': 'ardesia',
    'cuarcita': 'quarzite', 'caliza': 'calcare', 'travertino': 'travertino',
    'suelo radiante': 'pavimento radiante', 'calefacción por suelo radiante': 'riscaldamento a pavimento',
    'suelo flotante': 'pavimento flottante', 'suelo pegado': 'pavimento incollato',
    'suelo clavado': 'pavimento chiodato', 'subbase': 'sottofondo',
    'contrapiso': 'massetto', 'maseto': 'massetto', 'regularización': 'livellamento',
    'junta de dilatación': 'giunto di dilatazione', 'junta de construcción': 'giunto di costruzione',
    'aislamientos': 'isolamenti', 'aislar': 'isolare', 'aislado': 'isolato',
    'aislada': 'isolata', 'aislados': 'isolati', 'aisladas': 'isolate',
    'térmico': 'termico', 'térmica': 'termica', 'térmicos': 'termici',
    'térmicas': 'termiche', 'acústico': 'acustico', 'acústica': 'acustica',
    'acústicos': 'acustici', 'acústicas': 'acustiche',
    'fonoaislamiento': 'fonoisolamento', 'fonoabsorción': 'fonoassorbimento',
    'lana mineral': 'lana minerale', 'lana de roca': 'lana di roccia',
    'fibra de vidrio': 'fibra di vetro', 'poliestireno expandido': 'polistirene espanso',
    'poliestireno extruido': 'polistirene estruso', 'poliuretano': 'poliuretano',
    'espuma': 'schiuma', 'espumas': 'schiume', 'corcho': 'sughero',
    'celulosa': 'cellulosa', 'fibra': 'fibra', 'fibras': 'fibre',
    'natural': 'naturale', 'naturales': 'naturali', 'sintético': 'sintetico',
    'sintética': 'sintetica', 'sintéticos': 'sintetici', 'sintéticas': 'sintetiche',
    'ecológico': 'ecologico', 'ecológica': 'ecologica', 'ecológicos': 'ecologici',
    'ecológicas': 'ecologiche', 'sostenible': 'sostenibile',
    'sostenibles': 'sostenibili', 'renovable': 'rinnovabile',
    'renovables': 'rinnovabili', 'reciclado': 'riciclato', 'reciclada': 'riciclata',
    'reciclados': 'riciclati', 'recicladas': 'riciclate', 'reciclable': 'riciclabile',
    'reciclables': 'riciclabili', 'eficiencia energética': 'efficienza energetica',
    'eficiencia': 'efficienza', 'energético': 'energetico', 'energética': 'energetica',
    'energéticos': 'energetici', 'energéticas': 'energetiche', 'consumo': 'consumo',
    'consumos': 'consumi', 'ahorro energético': 'risparmio energetico',
    'pérdida de calor': 'perdita di calore', 'ganancia de calor': 'guadagno di calore',
    'transferencia': 'trasferimento', 'transmisión': 'trasmissione',
    'conductividad': 'conduttività', 'conductividad térmica': 'conduttività termica',
    'resistencia térmica': 'resistenza termica', 'valor R': 'valore R',
    'valor U': 'valore U', 'coeficiente': 'coefficiente',
    'coeficientes': 'coefficienti', 'densidad': 'densità', 'densidades': 'densità',
    'masas': 'masse', 'volúmenes': 'volumi',
    'pinturas': 'vernici', 'pintar': 'dipingere', 'pintado': 'pittura',
    'imprimaciones': 'primer', 'sellador': 'sigillante', 'selladores': 'sigillanti',
    'masillas': 'stucchi', 'estuco': 'stucco', 'estucos': 'stucchi', 'revoques': 'intonaci',
    'enlucidos': 'intonaci', 'yesos': 'gessi', 'pladur': 'cartongesso',
    'drywall': 'cartongesso', 'cartón yeso': 'cartongesso', 'panel': 'pannello',
    'paneles': 'pannelli', 'placa': 'lastra', 'placas': 'lastre',
    'revestimiento': 'rivestimento', 'revestimientos': 'rivestimenti',
    'revestir': 'rivestire', 'revestido': 'rivestito', 'revestida': 'rivestita',
    'revestidos': 'rivestiti', 'revestidas': 'rivestite', 'terminación': 'finitura',
    'terminaciones': 'finiture', 'terminar': 'finire', 'terminado': 'finito',
    'terminada': 'finita', 'terminados': 'finiti', 'terminadas': 'finite',
    'pulido': 'lucidato', 'pulida': 'lucidata', 'pulidos': 'lucidati',
    'pulidas': 'lucidate', 'pulir': 'lucidare', 'lijado': 'carteggiato',
    'lijada': 'carteggiata', 'lijados': 'carteggiati', 'lijadas': 'carteggiate',
    'lijar': 'carteggiare', 'lijadora': 'carteggiatrice',
    'lijadoras': 'carteggiatrici', 'lijas': 'carte vetrate', 'lija': 'carta vetrata',
    'grano': 'grana', 'granos': 'grane', 'fino': 'fine', 'fina': 'fine',
    'finos': 'fini', 'finas': 'fini', 'grueso': 'grosso', 'gruesa': 'grossa',
    'gruesos': 'grossi', 'gruesas': 'grosse', 'medio': 'medio', 'media': 'media',
    'medios': 'medi', 'medias': 'medie', 'mate': 'opaco', 'mates': 'opachi',
    'opaco': 'opaco', 'opaca': 'opaca', 'opacos': 'opachi', 'opacas': 'opache',
    'brillo': 'lucido', 'brillos': 'lucidi', 'brillante': 'lucido',
    'brillantes': 'lucidi', 'semibrillo': 'semilucido', 'semimate': 'semilucido',
    'satinado': 'satinato', 'satinada': 'satinata', 'satinados': 'satinati',
    'satinadas': 'satinate', 'textura': 'trama', 'texturas': 'trame',
    'texturizado': 'testurizzato', 'texturizada': 'testurizzata',
    'texturizados': 'testurizzati', 'texturizadas': 'testurizzate',
    'liso': 'liscio', 'lisa': 'liscia', 'lisos': 'lisci', 'lisas': 'lisce',
    'rugoso': 'ruvido', 'rugosa': 'ruvida', 'rugosos': 'ruvidi', 'rugosas': 'ruvide',
    'suave': 'morbido', 'suaves': 'morbidi', 'áspero': 'ruvido', 'áspera': 'ruvida',
    'ásperos': 'ruvidi', 'ásperas': 'ruvide', 'color': 'colore', 'colores': 'colori',
    'tono': 'tonalità', 'tonos': 'tonalità', 'tintes': 'tinte',
    'tintura': 'tintura', 'tinturas': 'tinture', 'pigmento': 'pigmento',
    'pigmentos': 'pigmenti', 'pigmentado': 'pigmentato', 'pigmentada': 'pigmentata',
    'pigmentados': 'pigmentati', 'pigmentadas': 'pigmentate', 'blanco': 'bianco',
    'blanca': 'bianca', 'blancos': 'bianchi', 'blancas': 'bianche', 'negro': 'nero',
    'negra': 'nera', 'negros': 'neri', 'negras': 'nere', 'gris': 'grigio',
    'grises': 'grigi', 'rojo': 'rosso', 'roja': 'rossa', 'rojos': 'rossi',
    'rojas': 'rosse', 'azul': 'blu', 'azules': 'blu', 'verde': 'verde',
    'verdes': 'verdi', 'amarillo': 'giallo', 'amarilla': 'gialla', 'amarillos': 'gialli',
    'amarillas': 'gialle', 'naranja': 'arancione', 'naranjas': 'arancioni',
    'marrón': 'marrone', 'marrones': 'marroni', 'beige': 'beige', 'crema': 'crema',
    'rosa': 'rosa', 'rosas': 'rosa', 'violeta': 'viola', 'violetas': 'viola',
    'morado': 'viola', 'morada': 'viola', 'morados': 'viola', 'moradas': 'viola',
    'transparente': 'trasparente', 'transparentes': 'trasparenti',
    'translúcido': 'traslucido', 'translúcida': 'traslucida', 'translúcidos': 'traslucidi',
    'translúcidas': 'traslucide',
    'jardín': 'giardino', 'jardines': 'giardini', 'jardinería': 'giardinaggio',
    'paisajismo': 'paesaggistica', 'paisaje': 'paesaggio', 'paisajes': 'paesaggi',
    'diseño de': 'progetto di', 'diseño de jardín': 'progetto di giardino',
    'diseño de paisajismo': 'progetto di paesaggistica', 'diseñar': 'progettare',
    'diseñado': 'progettato', 'diseñada': 'progettata', 'diseñados': 'progettati',
    'diseñadas': 'progettate', 'planta': 'pianta', 'plantas': 'piante',
    'plantar': 'piantare', 'plantado': 'piantato', 'plantada': 'piantata',
    'plantados': 'piantati', 'plantadas': 'piantate', 'plantación': 'piantumazione',
    'plantaciones': 'piantumazioni', 'árbol': 'albero', 'árboles': 'alberi',
    'arbusto': 'arbusto', 'arbustos': 'arbusti', 'flor': 'fiore', 'flores': 'fiori',
    'floración': 'fioritura', 'floraciones': 'fioriture', 'florido': 'fiorito',
    'florida': 'fiorita', 'floridos': 'fioriti', 'floridas': 'fiorite',
    'florero': 'vaso', 'floreros': 'vasi', 'maceta': 'vaso', 'macetas': 'vasi',
    'tiesto': 'vaso', 'tiestos': 'vasi', 'tierra de': 'terra di',
    'tierra de jardín': 'terra da giardino', 'tierra de cultivo': 'terra da coltivo',
    'tierra vegetal': 'terra vegetale', 'tierra para': 'terra per',
    'tierra para plantas': 'terra per piante', 'tierra para macetas': 'terra per vasi',
    'tierra para sembrar': 'terra per seminare', 'tierra para trasplantar': 'terra per trapiantare',
    'sustrato': 'substrato', 'sustratos': 'substrati', 'sustrato de': 'substrato di',
    'sustrato para': 'substrato per', 'compost': 'compost', 'composta': 'compost',
    'abono': 'fertilizzante', 'abonos': 'fertilizzanti', 'abonar': 'fertilizzare',
    'abonado': 'fertilizzato', 'abonada': 'fertilizzata', 'abonados': 'fertilizzati',
    'abonadas': 'fertilizzate', 'fertilizante': 'fertilizzante',
    'fertilizantes': 'fertilizzanti', 'fertilizar': 'fertilizzare',
    'fertilizado': 'fertilizzato', 'fertilizada': 'fertilizzata',
    'fertilizados': 'fertilizzati', 'fertilizadas': 'fertilizzate',
    'fertilización': 'fertilizzazione', 'fertilizaciones': 'fertilizzazioni',
    'nutriente': 'nutriente', 'nutrientes': 'nutrienti', 'nutrición': 'nutrizione',
    'nutriciones': 'nutrizioni', 'nutrir': 'nutrire', 'nutrido': 'nutrito',
    'nutrida': 'nutrita', 'nutridos': 'nutriti', 'nutridas': 'nutrite',
    'nitrógeno': 'azoto', 'fósforo': 'fosforo', 'potasio': 'potassio',
    'magnesio': 'magnesio', 'calcio': 'calcio', 'hierro': 'ferro',
    'manganeso': 'manganese', 'cobre': 'rame', 'zinc': 'zinco', 'boro': 'boro',
    'molibdeno': 'molibdeno', 'cloro': 'cloro', 'azufre': 'zolfo',
    'riego': 'irrigazione', 'riegos': 'irrigazioni', 'regar': 'innaffiare',
    'regado': 'innaffiato', 'regada': 'innaffiata', 'regados': 'innaffiati',
    'regadas': 'innaffiate', 'sistema de riego': 'sistema di irrigazione',
    'sistemas de riego': 'sistemi di irrigazione', 'riego por': 'irrigazione per',
    'riego por goteo': 'irrigazione a goccia', 'riego por aspersión': 'irrigazione ad aspersione',
    'riego por gravedad': 'irrigazione per gravità',
    'riego por inundación': 'irrigazione per inondazione', 'riego por surcos': 'irrigazione per solchi',
    'aspersor': 'irrigatore', 'aspersores': 'irrigatori', 'aspersor de': 'irrigatore di',
    'aspersor de impacto': 'irrigatore a impatto', 'aspersor oscilante': 'irrigatore oscillante',
    'aspersor giratorio': 'irrigatore rotante', 'aspersor fijo': 'irrigatore fisso',
    'aspersor móvil': 'irrigatore mobile', 'aspersor automático': 'irrigatore automatico',
    'aspersor programable': 'irrigatore programmabile', 'goteo': 'goccia',
    'goteos': 'gocce', 'gotero': 'gocciolatore', 'goteros': 'gocciolatori',
    'tubo de': 'tubo di', 'tubo de riego': 'tubo di irrigazione',
    'tubo de goteo': 'tubo di gocciolamento', 'manguera': 'tubo', 'mangueras': 'tubi',
    'manguera de': 'tubo di', 'manguera de riego': 'tubo di irrigazione',
    'manguera de jardín': 'tubo da giardino', 'válvula de': 'valvola di',
    'válvula de riego': 'valvola di irrigazione', 'válvula de control': 'valvola di controllo',
    'válvula de paso': 'valvola di intercettazione', 'válvula de retención': 'valvola di ritegno',
    'válvula de alivio': 'valvola di sfogo', 'válvula de seguridad': 'valvola di sicurezza',
    'válvula solenoide': 'valvola solenoide', 'válvula eléctrica': 'valvola elettrica',
    'válvula hidráulica': 'valvola idraulica', 'válvula neumática': 'valvola pneumatica',
    'válvula manual': 'valvola manuale', 'válvula automática': 'valvola automatica',
    'válvula programable': 'valvola programmabile', 'programador': 'programmatore',
    'programadores': 'programmatori', 'programador de': 'programmatore di',
    'programador de riego': 'programmatore di irrigazione', 'programador para': 'programmatore per',
    'programador para riego': 'programmatore per irrigazione', 'temporizador': 'timer',
    'temporizadores': 'timer', 'temporizador de': 'timer di', 'temporizador para': 'timer per',
    'temporizador para riego': 'timer per irrigazione', 'controlador': 'controllore',
    'controladores': 'controllori', 'controlador de': 'controllore di',
    'controlador de riego': 'controllore di irrigazione', 'controlador central': 'controllore centrale',
    'controlador remoto': 'controllore remoto', 'controlador inalámbrico': 'controllore senza fili',
    'controlador wifi': 'controllore wifi', 'controlador inteligente': 'controllore intelligente',
    'sensor': 'sensore', 'sensores': 'sensori', 'sensor de': 'sensore di',
    'sensor para': 'sensore per', 'sensor de lluvia': 'sensore di pioggia',
    'sensor de humedad': 'sensore di umidità', 'sensor de temperatura': 'sensore di temperatura',
    'detector': 'rilevatore', 'detectores': 'rilevatori', 'detector de': 'rilevatore di',
    'detector para': 'rilevatore per', 'césped': 'prato', 'céspedes': 'prati',
    'pasto': 'prato', 'pastos': 'prati', 'pradera': 'prateria', 'praderas': 'praterie',
    'campo': 'campo', 'campos': 'campi', 'campo de': 'campo di',
    'campo de fútbol': 'campo da calcio', 'campo de golf': 'campo da golf',
    'campo de tenis': 'campo da tennis',
};

function translate(text) {
    if (!text || typeof text !== 'string') return text;
    let result = text;
    const sortedKeys = Object.keys(dict).sort((a, b) => b.length - a.length);
    for (const key of sortedKeys) {
        const regex = new RegExp(key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
        result = result.replace(regex, dict[key]);
    }
    result = result.replace(/\bdi la\b/g, 'della');
    result = result.replace(/\bdi el\b/g, 'del');
    result = result.replace(/\ba la\b/g, 'alla');
    result = result.replace(/\ba el\b/g, 'al');
    result = result.replace(/\bde el\b/g, 'del');
    return result;
}

const translatedCalculators = calculators.map(calc => {
    const translated = { id: calc.id };
    if (calc.example_label) translated.example_label = translate(calc.example_label);
    if (calc.range_hints) {
        translated.range_hints = {};
        for (const [key, value] of Object.entries(calc.range_hints)) {
            translated.range_hints[key] = translate(value);
        }
    }
    if (calc.result_context) translated.result_context = translate(calc.result_context);
    if (calc.formula_display) translated.formula_display = translate(calc.formula_display);
    if (calc.steps && Array.isArray(calc.steps)) translated.steps = calc.steps.map(step => translate(step));
    if (calc.mistakes && Array.isArray(calc.mistakes)) translated.mistakes = calc.mistakes.map(m => translate(m));
    if (calc.input_type_review && Array.isArray(calc.input_type_review)) {
        translated.input_type_review = calc.input_type_review.map(item => ({
            field_id: item.field_id,
            current_type: item.current_type,
            recommended_type: item.recommended_type,
            reason: translate(item.reason)
        }));
    }
    return translated;
});

fs.writeFileSync('i18n_it.json', JSON.stringify(translatedCalculators, null, 2), 'utf8');
console.log(`Translation complete! Output saved to i18n_it.json`);
console.log(`Total calculators processed: ${translatedCalculators.length}`);
