BLOCK_ICONS = {
    "estructuras":   "🏗️",
    "mamposteria":   "🧱",
    "pavimentos":    "🪨",
    "fontaneria":    "🔧",
    "electricidad":  "⚡",
    "climatizacion": "🌡️",
    "carpinteria":   "🪵",
    "pintura":       "🎨",
    "gestion":       "📊",
    "matematicas":   "🔢",
    "ciencia":       "⚛️",
    "salud":         "❤️",
    "finanzas":      "💶",
    "cotidiano":     "🛠️",
    "quimica":       "🧪",
    "electronica":   "🔌",
    "clima":         "🌤️",
    "utilidades":    "🧰",
    "fotografia":    "📷",
    "transporte":    "✈️",
}
