"""
Fix German output labels in calculator JSON files.
Translates output labels from Spanish/English to proper German.
Only touches i18n.de.outputs.
"""
import json, glob, os, re

CALC_DIR = r"C:\Microsaas\obra\src\calculators"

# Comprehensive output label translations (Spanish/English -> German)
# Based on common patterns across the calculator files
OUTPUT_TRANSLATIONS = {
    # English -> German
    "Category": "Kategorie",
    "category": "Kategorie",
    "Glucose": "Glukose",
    "glucose": "Glukose",
    
    # Time/Date
    "Years": "Jahre",
    "years": "Jahre",
    "Months": "Monate",
    "months": "Monate",
    "Days": "Tage",
    "days": "Tage",
    "Hours": "Stunden",
    "hours": "Stunden",
    "Minutes": "Minuten",
    "minutes": "Minuten",
    "Seconds": "Sekunden",
    "seconds": "Sekunden",
    "Weeks": "Wochen",
    "weeks": "Wochen",
    "Days to birthday": "Tage bis Geburtstag",
    "days until birthday": "Tage bis Geburtstag",
    "Years to double": "Jahre bis Verdopplung",
    "Total years": "Gesamtjahre",
    "total years": "Gesamtjahre",
    "Total months": "Gesamtmonate",
    "total months": "Gesamtmonate",
    "Total days": "Gesamttage",
    "total days": "Gesamttage",
    "total hours": "Gesamtstunden",
    "Total hours": "Gesamtstunden",
    "Total minutes": "Gesamtminuten",
    "total minutes": "Gesamtminuten",
    "Total seconds": "Gesamtsekunden",
    "total seconds": "Gesamtsekunden",
    "Age in days": "Alter in Tagen",
    "Age in hours": "Alter in Stunden",
    "Age in minutes": "Alter in Minuten",
    "Age in seconds": "Alter in Sekunden",
    "Age (years)": "Alter (Jahre)",
    "age (years)": "Alter (Jahre)",
    "Total time": "Gesamtzeit",
    "total time": "Gesamtzeit",
    "Time elapsed": "Verstrichene Zeit",
    "time elapsed": "Verstrichene Zeit",
    
    # Physical quantities
    "Volume": "Volumen",
    "volume": "Volumen",
    "volume (m3)": "Volumen (m³)",
    "Volume (m3)": "Volumen (m³)",
    "Volume (m³)": "Volumen (m³)",
    "Volume (L)": "Volumen (L)",
    "volume (L)": "Volumen (L)",
    "Area": "Fläche",
    "area": "Fläche",
    "Area (m2)": "Fläche (m²)",
    "Area (m²)": "Fläche (m²)",
    "area (m2)": "Fläche (m²)",
    "Mass": "Masse",
    "mass": "Masse",
    "Mass (kg)": "Masse (kg)",
    "mass (kg)": "Masse (kg)",
    "Weight": "Gewicht",
    "weight": "Gewicht",
    "Weight (kg)": "Gewicht (kg)",
    "weight (kg)": "Gewicht (kg)",
    "Density": "Dichte",
    "density": "Dichte",
    "Density (kg/m3)": "Dichte (kg/m³)",
    "density (kg/m³)": "Dichte (kg/m³)",
    "Velocity": "Geschwindigkeit",
    "velocity": "Geschwindigkeit",
    "Velocity (m/s)": "Geschwindigkeit (m/s)",
    "velocity (m/s)": "Geschwindigkeit (m/s)",
    "Speed": "Geschwindigkeit",
    "speed": "Geschwindigkeit",
    "Speed (m/s)": "Geschwindigkeit (m/s)",
    "speed (m/s)": "Geschwindigkeit (m/s)",
    "Acceleration": "Beschleunigung",
    "acceleration": "Beschleunigung",
    "Acceleration (m/s2)": "Beschleunigung (m/s²)",
    "Acceleration (m/s²)": "Beschleunigung (m/s²)",
    "acceleration (m/s2)": "Beschleunigung (m/s²)",
    "acceleration (g)": "Beschleunigung (g)",
    "Acceleration (g)": "Beschleunigung (g)",
    "Force": "Kraft",
    "force": "Kraft",
    "Force (N)": "Kraft (N)",
    "force (N)": "Kraft (N)",
    "Energy": "Energie",
    "energy": "Energie",
    "Energy (J)": "Energie (J)",
    "energy (J)": "Energie (J)",
    "Energy (kWh)": "Energie (kWh)",
    "energy (kWh)": "Energie (kWh)",
    "Power": "Leistung",
    "power": "Leistung",
    "Power (W)": "Leistung (W)",
    "power (W)": "Leistung (W)",
    "Pressure": "Druck",
    "pressure": "Druck",
    "Pressure (bar)": "Druck (bar)",
    "pressure (bar)": "Druck (bar)",
    "Pressure (Pa)": "Druck (Pa)",
    "pressure (Pa)": "Druck (Pa)",
    "Temperature": "Temperatur",
    "temperature": "Temperatur",
    "Temperature (°C)": "Temperatur (°C)",
    "temperature (°C)": "Temperatur (°C)",
    "Temperature (°F)": "Temperatur (°F)",
    "temperature (°F)": "Temperatur (°F)",
    "Temperature (K)": "Temperatur (K)",
    "temperature (K)": "Temperatur (K)",
    "Length": "Länge",
    "length": "Länge",
    "Length (m)": "Länge (m)",
    "length (m)": "Länge (m)",
    "Width": "Breite",
    "width": "Breite",
    "Width (m)": "Breite (m)",
    "width (m)": "Breite (m)",
    "Height": "Höhe",
    "height": "Höhe",
    "Height (m)": "Höhe (m)",
    "height (m)": "Höhe (m)",
    "Depth": "Tiefe",
    "depth": "Tiefe",
    "Depth (m)": "Tiefe (m)",
    "depth (m)": "Tiefe (m)",
    "Radius": "Radius",
    "radius": "Radius",
    "Radius (m)": "Radius (m)",
    "radius (m)": "Radius (m)",
    "Diameter": "Durchmesser",
    "diameter": "Durchmesser",
    "Diameter (mm)": "Durchmesser (mm)",
    "diameter (mm)": "Durchmesser (mm)",
    "Circumference": "Umfang",
    "circumference": "Umfang",
    "Frequency": "Frequenz",
    "frequency": "Frequenz",
    "Frequency (Hz)": "Frequenz (Hz)",
    "frequency (Hz)": "Frequenz (Hz)",
    "Voltage": "Spannung",
    "voltage": "Spannung",
    "Voltage (V)": "Spannung (V)",
    "voltage (V)": "Spannung (V)",
    "Current": "Strom",
    "current": "Strom",
    "Current (A)": "Strom (A)",
    "current (A)": "Strom (A)",
    "Resistance": "Widerstand",
    "resistance": "Widerstand",
    "Resistance (Ohm)": "Widerstand (Ω)",
    "Resistance (Ω)": "Widerstand (Ω)",
    "resistance (ohm)": "Widerstand (Ω)",
    "Capacitance": "Kapazität",
    "capacitance": "Kapazität",
    "Inductance": "Induktivität",
    "inductance": "Induktivität",
    "Impedance": "Impedanz",
    "impedance": "Impedanz",
    "Angle": "Winkel",
    "angle": "Winkel",
    "Angle (°)": "Winkel (°)",
    "angle (°)": "Winkel (°)",
    
    # Financial
    "Total payment": "Gesamtzahlung",
    "total payment": "Gesamtzahlung",
    "Monthly payment": "Monatliche Zahlung",
    "monthly payment": "Monatliche Zahlung",
    "Total interest": "Gesamtzins",
    "total interest": "Gesamtzins",
    "Total principal": "Gesamtkapital",
    "total principal": "Gesamtkapital",
    "Net present value": "Kapitalwert",
    "NPV": "Kapitalwert",
    "npv": "Kapitalwert",
    "IRR": "Interner Zinsfuß",
    "irr": "Interner Zinsfuß",
    "ROI": "ROI",
    "roi": "ROI",
    "Profit margin": "Gewinnmarge",
    "profit margin": "Gewinnmarge",
    "Total savings": "Gesamtersparnis",
    "total savings": "Gesamtersparnis",
    "Future value": "Zukunftswert",
    "future value": "Zukunftswert",
    "Present value": "Gegenwartswert",
    "present value": "Gegenwartswert",
    "Payback period": "Amortisationsdauer",
    "payback period": "Amortisationsdauer",
    "Break-even": "Gewinnschwelle",
    "break-even": "Gewinnschwelle",
    "Salary": "Gehalt",
    "salary": "Gehalt",
    "Hourly rate": "Stundensatz",
    "hourly rate": "Stundensatz",
    "Tip amount": "Trinkgeldbetrag",
    "tip amount": "Trinkgeldbetrag",
    "Total with tip": "Gesamt mit Trinkgeld",
    "total with tip": "Gesamt mit Trinkgeld",
    "Per person": "Pro Person",
    "per person": "Pro Person",
    "Discount": "Rabatt",
    "discount": "Rabatt",
    "Final price": "Endpreis",
    "final price": "Endpreis",
    "Tax amount": "Steuerbetrag",
    "tax amount": "Steuerbetrag",
    "Total with tax": "Gesamt mit Steuer",
    "total with tax": "Gesamt mit Steuer",
    "Margin": "Marge",
    "margin": "Marge",
    "Markup": "Aufschlag",
    "markup": "Aufschlag",
    "Commission": "Provision",
    "commission": "Provision",
    "Down payment": "Anzahlung",
    "down payment": "Anzahlung",
    "Loan amount": "Kreditbetrag",
    "loan amount": "Kreditbetrag",
    "Remaining balance": "Restschuld",
    "remaining balance": "Restschuld",
    "Final balance": "Endsaldo",
    "final balance": "Endsaldo",
    "Net salary": "Nettogehalt",
    "net salary": "Nettogehalt",
    "Gross salary": "Bruttogehalt",
    "gross salary": "Bruttogehalt",
    "Interest": "Zinsen",
    "interest": "Zinsen",
    "Principal": "Kapital",
    "principal": "Kapital",
    
    # Health
    "BMI": "BMI",
    "bmi": "BMI",
    "BMI Category": "BMI-Kategorie",
    "bmi category": "BMI-Kategorie",
    "BMR": "Grundumsatz",
    "bmr": "Grundumsatz",
    "BMR (kcal/day)": "Grundumsatz (kcal/Tag)",
    "bmr (kcal/day)": "Grundumsatz (kcal/Tag)",
    "TDEE": "Gesamtumsatz",
    "tdee": "Gesamtumsatz",
    "TDEE (kcal/day)": "Gesamtumsatz (kcal/Tag)",
    "tdee (kcal/day)": "Gesamtumsatz (kcal/Tag)",
    "Ideal weight": "Idealgewicht",
    "ideal weight": "Idealgewicht",
    "Ideal weight (kg)": "Idealgewicht (kg)",
    "ideal weight (kg)": "Idealgewicht (kg)",
    "Body fat": "Körperfett",
    "body fat": "Körperfett",
    "Body fat (%)": "Körperfett (%)",
    "body fat (%)": "Körperfett (%)",
    "Lean mass": "Magermasse",
    "lean mass": "Magermasse",
    "Lean mass (kg)": "Magermasse (kg)",
    "lean mass (kg)": "Magermasse (kg)",
    "Calories": "Kalorien",
    "calories": "Kalorien",
    "Calories (kcal)": "Kalorien (kcal)",
    "calories (kcal)": "Kalorien (kcal)",
    "Protein (g)": "Protein (g)",
    "protein (g)": "Protein (g)",
    "Carbs (g)": "Kohlenhydrate (g)",
    "carbs (g)": "Kohlenhydrate (g)",
    "Fat (g)": "Fett (g)",
    "fat (g)": "Fett (g)",
    "Water (L)": "Wasser (L)",
    "water (L)": "Wasser (L)",
    "Systolic": "Systolisch",
    "systolic": "Systolisch",
    "Diastolic": "Diastolisch",
    "diastolic": "Diastolisch",
    "Blood pressure category": "Blutdruck-Kategorie",
    "blood pressure category": "Blutdruck-Kategorie",
    "Heart rate": "Herzfrequenz",
    "heart rate": "Herzfrequenz",
    "Heart rate (bpm)": "Herzfrequenz (bpm)",
    "heart rate (bpm)": "Herzfrequenz (bpm)",
    "Max heart rate": "Maximale Herzfrequenz",
    "max heart rate": "Maximale Herzfrequenz",
    "VO2 max": "VO₂max",
    "vo2 max": "VO₂max",
    "A1C": "HbA1c",
    "a1c": "HbA1c",
    "A1C (%)": "HbA1c (%)",
    "a1c (%)": "HbA1c (%)",
    "LDL": "LDL",
    "ldl": "LDL",
    "LDL (mg/dL)": "LDL (mg/dL)",
    "ldl (mg/dL)": "LDL (mg/dL)",
    "HDL": "HDL",
    "hdl": "HDL",
    "Cholesterol": "Cholesterin",
    "cholesterol": "Cholesterin",
    "Waist to hip ratio": "Taille-Hüft-Verhältnis",
    "waist to hip ratio": "Taille-Hüft-Verhältnis",
    "Waist to height ratio": "Taille-Größe-Verhältnis",
    "waist to height ratio": "Taille-Größe-Verhältnis",
    "BSA": "Körperoberfläche",
    "bsa": "Körperoberfläche",
    "BSA (m2)": "Körperoberfläche (m²)",
    "bsa (m2)": "Körperoberfläche (m²)",
    "Creatinine clearance": "Kreatinin-Clearance",
    "creatinine clearance": "Kreatinin-Clearance",
    "CrCl": "CrCl",
    "CrCl (mL/min)": "CrCl (mL/min)",
    "crcl (mL/min)": "CrCl (mL/min)",
    "Weight loss": "Gewichtsverlust",
    "weight loss": "Gewichtsverlust",
    "Weight loss (%)": "Gewichtsverlust (%)",
    "weight loss (%)": "Gewichtsverlust (%)",
    
    # Math/Stats
    "Result": "Ergebnis",
    "result": "Ergebnis",
    "Score": "Wert",
    "score": "Wert",
    "Z-score": "Z-Wert",
    "z-score": "Z-Wert",
    "Percentile": "Perzentil",
    "percentile": "Perzentil",
    "Mean": "Mittelwert",
    "mean": "Mittelwert",
    "Median": "Median",
    "median": "Median",
    "Mode": "Modus",
    "mode": "Modus",
    "Standard deviation": "Standardabweichung",
    "standard deviation": "Standardabweichung",
    "Variance": "Varianz",
    "variance": "Varianz",
    "Range": "Spannweite",
    "range": "Spannweite",
    "Sum": "Summe",
    "sum": "Summe",
    "Average": "Durchschnitt",
    "average": "Durchschnitt",
    "Count": "Anzahl",
    "count": "Anzahl",
    "Minimum": "Minimum",
    "minimum": "Minimum",
    "Maximum": "Maximum",
    "maximum": "Maximum",
    "Probability": "Wahrscheinlichkeit",
    "probability": "Wahrscheinlichkeit",
    "Probability (%)": "Wahrscheinlichkeit (%)",
    "probability (%)": "Wahrscheinlichkeit (%)",
    "Combinations": "Kombinationen",
    "combinations": "Kombinationen",
    "Permutations": "Permutationen",
    "permutations": "Permutationen",
    "Factorial": "Fakultät",
    "factorial": "Fakultät",
    "Percentage": "Prozentsatz",
    "percentage": "Prozentsatz",
    "Percentage (%)": "Prozentsatz (%)",
    "percentage (%)": "Prozentsatz (%)",
    "Fraction": "Bruch",
    "fraction": "Bruch",
    "Slope": "Steigung",
    "slope": "Steigung",
    "Slope (%)": "Steigung (%)",
    "slope (%)": "Steigung (%)",
    "Ratio": "Verhältnis",
    "ratio": "Verhältnis",
    "Root": "Wurzel",
    "root": "Wurzel",
    "Square": "Quadrat",
    "square": "Quadrat",
    "Cube": "Kubik",
    "cube": "Kubik",
    "Logarithm": "Logarithmus",
    "logarithm": "Logarithmus",
    "Natural log": "Natürlicher Logarithmus",
    "natural log": "Natürlicher Logarithmus",
    "Log base 10": "Logarithmus Basis 10",
    "log base 10": "Logarithmus Basis 10",
    "GCF": "GGT",
    "gcf": "GGT",
    "GCD": "GGT",
    "gcd": "GGT",
    "LCM": "KGV",
    "lcm": "KGV",
    "Prime factors": "Primfaktoren",
    "prime factors": "Primfaktoren",
    "Scientific notation": "Wissenschaftliche Notation",
    "scientific notation": "Wissenschaftliche Notation",
    "Rounded number": "Gerundete Zahl",
    "rounded number": "Gerundete Zahl",
    "Sample size": "Stichprobenumfang",
    "sample size": "Stichprobenumfang",
    "Confidence interval": "Konfidenzintervall",
    "confidence interval": "Konfidenzintervall",
    "Margin of error": "Fehlerspanne",
    "margin of error": "Fehlerspanne",
    "P-value": "P-Wert",
    "p-value": "P-Wert",
    
    # Construction
    "Total bags": "Gesamtsäcke",
    "total bags": "Gesamtsäcke",
    "Bags": "Säcke",
    "bags": "Säcke",
    "Total cost": "Gesamtkosten",
    "total cost": "Gesamtkosten",
    "Cost": "Kosten",
    "cost": "Kosten",
    "Total volume": "Gesamtvolumen",
    "total volume": "Gesamtvolumen",
    "Total area": "Gesamtfläche",
    "total area": "Gesamtfläche",
    "Total weight": "Gesamtgewicht",
    "total weight": "Gesamtgewicht",
    "Total quantity": "Gesamtmenge",
    "total quantity": "Gesamtmenge",
    "Quantity": "Menge",
    "quantity": "Menge",
    "Materials": "Materialien",
    "materials": "Materialien",
    "Material per m2": "Material pro m²",
    "material per m2": "Material pro m²",
    "Waste": "Verschnitt",
    "waste": "Verschnitt",
    "Waste (%)": "Verschnitt (%)",
    "waste (%)": "Verschnitt (%)",
    "Net": "Netto",
    "net": "Netto",
    "Gross": "Brutto",
    "gross": "Brutto",
    "Dimension": "Abmessung",
    "dimension": "Abmessung",
    "Diameter nominal (DN)": "Nenndurchmesser (DN)",
    "diameter nominal (DN)": "Nenndurchmesser (DN)",
    "Calculated diameter": "Berechneter Durchmesser",
    "calculated diameter": "Berechneter Durchmesser",
    "Flow": "Durchfluss",
    "flow": "Durchfluss",
    "Flow (m3/h)": "Durchfluss (m³/h)",
    "flow (m3/h)": "Durchfluss (m³/h)",
    "Flow (L/s)": "Durchfluss (L/s)",
    "flow (L/s)": "Durchfluss (L/s)",
    "Tiles": "Fliesen",
    "tiles": "Fliesen",
    "Blocks": "Blöcke",
    "blocks": "Blöcke",
    "Bricks": "Ziegel",
    "bricks": "Ziegel",
    "Cement (kg)": "Zement (kg)",
    "cement (kg)": "Zement (kg)",
    "Sand (kg)": "Sand (kg)",
    "sand (kg)": "Sand (kg)",
    "Gravel (kg)": "Kies (kg)",
    "gravel (kg)": "Kies (kg)",
    "Water (L)": "Wasser (L)",
    "Steel (kg)": "Stahl (kg)",
    "steel (kg)": "Stahl (kg)",
    "Rebar weight": "Bewehrungsgewicht",
    "rebar weight": "Bewehrungsgewicht",
    "Rebar weight (kg)": "Bewehrungsgewicht (kg)",
    "rebar weight (kg)": "Bewehrungsgewicht (kg)",
    "Concrete volume": "Betonvolumen",
    "concrete volume": "Betonvolumen",
    "Concrete volume (m3)": "Betonvolumen (m³)",
    "concrete volume (m3)": "Betonvolumen (m³)",
    "Mortar volume": "Mörtelvolumen",
    "mortar volume": "Mörtelvolumen",
    "Paint (L)": "Farbe (L)",
    "paint (L)": "Farbe (L)",
    "Coats": "Anstriche",
    "coats": "Anstriche",
    "Thickness": "Dicke",
    "thickness": "Dicke",
    "Thickness (mm)": "Dicke (mm)",
    "thickness (mm)": "Dicke (mm)",
    "Coverage": "Abdeckung",
    "coverage": "Abdeckung",
    "Consumption": "Verbrauch",
    "consumption": "Verbrauch",
    "Consumption per m2": "Verbrauch pro m²",
    "consumption per m2": "Verbrauch pro m²",
    
    # Spanish -> German
    "Volumen": "Volumen",
    "volumen": "Volumen",
    "Volumen (m3)": "Volumen (m³)",
    "volumen (m3)": "Volumen (m³)",
    "Volumen (L)": "Volumen (L)",
    "volumen (L)": "Volumen (L)",
    "Área": "Fläche",
    "área": "Fläche",
    "Área (m2)": "Fläche (m²)",
    "área (m2)": "Fläche (m²)",
    "Longitud": "Länge",
    "longitud": "Länge",
    "Altura": "Höhe",
    "altura": "Höhe",
    "Anchura": "Breite",
    "anchura": "Breite",
    "Ancho": "Breite",
    "ancho": "Breite",
    "Profundidad": "Tiefe",
    "profundidad": "Tiefe",
    "Peso": "Gewicht",
    "peso": "Gewicht",
    "Masa": "Masse",
    "masa": "Masse",
    "Densidad": "Dichte",
    "densidad": "Dichte",
    "Velocidad": "Geschwindigkeit",
    "velocidad": "Geschwindigkeit",
    "Aceleración": "Beschleunigung",
    "aceleración": "Beschleunigung",
    "Fuerza": "Kraft",
    "fuerza": "Kraft",
    "Energía": "Energie",
    "energía": "Energie",
    "Potencia": "Leistung",
    "potencia": "Leistung",
    "Presión": "Druck",
    "presión": "Druck",
    "Temperatura": "Temperatur",
    "temperatura": "Temperatur",
    "Resultado": "Ergebnis",
    "resultado": "Ergebnis",
    "Total": "Gesamt",
    "total": "Gesamt",
    "Cantidad": "Menge",
    "cantidad": "Menge",
    "Costo": "Kosten",
    "costo": "Kosten",
    "Costo total": "Gesamtkosten",
    "costo total": "Gesamtkosten",
    "Precio": "Preis",
    "precio": "Preis",
    "Precio total": "Gesamtpreis",
    "precio total": "Gesamtpreis",
    "Número": "Anzahl",
    "número": "Anzahl",
    "Porcentaje": "Prozentsatz",
    "porcentaje": "Prozentsatz",
    "Tiempo": "Zeit",
    "tiempo": "Zeit",
    "Distancia": "Entfernung",
    "distancia": "Entfernung",
    "Radio": "Radius",
    "radio": "Radius",
    "Diámetro": "Durchmesser",
    "diámetro": "Durchmesser",
    "Perímetro": "Umfang",
    "perímetro": "Umfang",
    "Superficie": "Fläche",
    "superficie": "Fläche",
    "Litros": "Liter",
    "litros": "Liter",
    "Metros": "Meter",
    "metros": "Meter",
    "Centímetros": "Zentimeter",
    "centímetros": "Zentimeter",
    "Milímetros": "Millimeter",
    "milímetros": "Millimeter",
    "Kilogramos": "Kilogramm",
    "kilogramos": "Kilogramm",
    "Gramos": "Gramm",
    "gramos": "Gramm",
    "Horas": "Stunden",
    "horas": "Stunden",
    "Minutos": "Minuten",
    "minutos": "Minuten",
    "Segundos": "Sekunden",
    "segundos": "Sekunden",
    "Días": "Tage",
    "días": "Tage",
    "Semanas": "Wochen",
    "semanas": "Wochen",
    "Meses": "Monate",
    "meses": "Monate",
    "Años": "Jahre",
    "años": "Jahre",
    "Calorías": "Kalorien",
    "calorías": "Kalorien",
    "IMC": "BMI",
    "imc": "BMI",
    "TMB": "Grundumsatz",
    "tmb": "Grundumsatz",
    "Grasa corporal": "Körperfett",
    "grasa corporal": "Körperfett",
    "Agua": "Wasser",
    "agua": "Wasser",
    "Salario": "Gehalt",
    "salario": "Gehalt",
    "Interés": "Zinsen",
    "interés": "Zinsen",
    "Ahorro": "Ersparnis",
    "ahorro": "Ersparnis",
    "Deuda": "Schulden",
    "deuda": "Schulden",
    "Hipoteca": "Hypothek",
    "hipoteca": "Hypothek",
    "Préstamo": "Kredit",
    "préstamo": "Kredit",
    "Inversión": "Investition",
    "inversión": "Investition",
    "Ganancia": "Gewinn",
    "ganancia": "Gewinn",
    "Pérdida": "Verlust",
    "pérdida": "Verlust",
    "Margen": "Marge",
    "margen": "Marge",
    "Descuento": "Rabatt",
    "descuento": "Rabatt",
    "Impuesto": "Steuer",
    "impuesto": "Steuer",
    "Propina": "Trinkgeld",
    "propina": "Trinkgeld",
    "Cuota mensual": "Monatliche Rate",
    "cuota mensual": "Monatliche Rate",
    "Pago mensual": "Monatliche Zahlung",
    "pago mensual": "Monatliche Zahlung",
    "Combinaciones": "Kombinationen",
    "combinaciones": "Kombinationen",
    "Permutaciones": "Permutationen",
    "permutaciones": "Permutationen",
    "Probabilidad": "Wahrscheinlichkeit",
    "probabilidad": "Wahrscheinlichkeit",
    "Media": "Mittelwert",
    "media": "Mittelwert",
    "Mediana": "Median",
    "mediana": "Median",
    "Moda": "Modus",
    "moda": "Modus",
    "Desviación estándar": "Standardabweichung",
    "desviación estándar": "Standardabweichung",
    "Varianza": "Varianz",
    "varianza": "Varianz",
    "Suma": "Summe",
    "suma": "Summe",
    "Promedio": "Durchschnitt",
    "promedio": "Durchschnitt",
    "Mínimo": "Minimum",
    "mínimo": "Minimum",
    "Máximo": "Maximum",
    "máximo": "Maximum",
    "Rango": "Spannweite",
    "rango": "Spannweite",
    "Pendiente": "Steigung",
    "pendiente": "Steigung",
    "Fracción": "Bruch",
    "fracción": "Bruch",
    "Raíz": "Wurzel",
    "raíz": "Wurzel",
    "Cuadrado": "Quadrat",
    "cuadrado": "Quadrat",
    "Cubo": "Kubik",
    "cubo": "Kubik",
    "Logaritmo": "Logarithmus",
    "logaritmo": "Logarithmus",
    "Exponente": "Exponent",
    "exponente": "Exponent",
    "Factorización": "Faktorisierung",
    "factorización": "Faktorisierung",
    "MCD": "GGT",
    "mcd": "GGT",
    "MCM": "KGV",
    "mcm": "KGV",
    "Notación científica": "Wissenschaftliche Notation",
    "notación científica": "Wissenschaftliche Notation",
    "Redondeo": "Rundung",
    "redondeo": "Rundung",
    "Tamaño de muestra": "Stichprobenumfang",
    "tamaño de muestra": "Stichprobenumfang",
    "Intervalo de confianza": "Konfidenzintervall",
    "intervalo de confianza": "Konfidenzintervall",
    "Margen de error": "Fehlerspanne",
    "margen de error": "Fehlerspanne",
    
    # Running/Sports
    "Pace": "Tempo",
    "pace": "Tempo",
    "Pace (min/km)": "Tempo (min/km)",
    "pace (min/km)": "Tempo (min/km)",
    "Speed (km/h)": "Geschwindigkeit (km/h)",
    "speed (km/h)": "Geschwindigkeit (km/h)",
    "Finish time": "Zielzeit",
    "finish time": "Zielzeit",
    "Finish time (h:mm:ss)": "Zielzeit (h:mm:ss)",
    "finish time (h:mm:ss)": "Zielzeit (h:mm:ss)",
    "Distance (km)": "Distanz (km)",
    "distance (km)": "Distanz (km)",
    "1RM": "1RM",
    "Calories burned": "Kalorienverbrauch",
    "calories burned": "Kalorienverbrauch",
    
    # Conversion
    "Converted value": "Umgerechneter Wert",
    "converted value": "Umgerechneter Wert",
    "Original value": "Originalwert",
    "original value": "Originalwert",
    
    # Science
    "Kinetic energy": "Kinetische Energie",
    "kinetic energy": "Kinetische Energie",
    "Potential energy": "Potentielle Energie",
    "potential energy": "Potentielle Energie",
    "Work": "Arbeit",
    "work": "Arbeit",
    "Momentum": "Impuls",
    "momentum": "Impuls",
    "Wavelength": "Wellenlänge",
    "wavelength": "Wellenlänge",
    "Dew point": "Taupunkt",
    "dew point": "Taupunkt",
    "Wind chill": "Windkälte",
    "wind chill": "Windkälte",
    "Heat index": "Hitzeindex",
    "heat index": "Hitzeindex",
    "Relative humidity": "Relative Luftfeuchtigkeit",
    "relative humidity": "Relative Luftfeuchtigkeit",
    
    # Generic
    "Value": "Wert",
    "value": "Wert",
    "Unit": "Einheit",
    "unit": "Einheit",
    "Number": "Zahl",
    "number": "Zahl",
    "Amount": "Betrag",
    "amount": "Betrag",
    "Rate": "Rate",
    "rate": "Rate",
    "Change": "Änderung",
    "change": "Änderung",
    "Difference": "Differenz",
    "difference": "Differenz",
    "Increase": "Erhöhung",
    "increase": "Erhöhung",
    "Decrease": "Verringerung",
    "decrease": "Verringerung",
    "Status": "Status",
    "status": "Status",
    "Level": "Niveau",
    "level": "Niveau",
    "Type": "Typ",
    "type": "Typ",
    "Label": "Bezeichnung",
    "label": "Bezeichnung",
    "Note": "Hinweis",
    "note": "Hinweis",
    "Description": "Beschreibung",
    "description": "Beschreibung",
    "Breakdown": "Aufschlüsselung",
    "breakdown": "Aufschlüsselung",
    "Summary": "Zusammenfassung",
    "summary": "Zusammenfassung",
    "Details": "Details",
    "details": "Details",
    "Chart": "Diagramm",
    "chart": "Diagramm",
    "Table": "Tabelle",
    "table": "Tabelle",
    "Input": "Eingabe",
    "input": "Eingabe",
    "Output": "Ausgabe",
    "output": "Ausgabe",
    
    # Additional labels found in audit - English/Spanish -> German
    "Surface area": "Oberfläche",
    "surface area": "Oberfläche",
    "Pulse pressure": "Pulsdruck",
    "pulse pressure": "Pulsdruck",
    "Adjusted weight": "Angepasstes Gewicht",
    "adjusted weight": "Angepasstes Gewicht",
    "Total/HDL ratio": "Gesamt/HDL-Verhältnis",
    "Slant height": "Mantellinie",
    "slant height": "Mantellinie",
    "Base area": "Grundfläche",
    "base area": "Grundfläche",
    "Total weeks": "Gesamtwochen",
    "total weeks": "Gesamtwochen",
    "Months to payoff": "Monate bis Tilgung",
    "months to payoff": "Monate bis Tilgung",
    "Total GB": "Gesamt GB",
    "total gb": "Gesamt GB",
    "Payback years": "Amortisationsjahre",
    "payback years": "Amortisationsjahre",
    "Lateral area": "Mantelfläche",
    "lateral area": "Mantelfläche",
    "Speed km/h": "Geschwindigkeit km/h",
    "speed km/h": "Geschwindigkeit km/h",
    "5K time": "5K-Zeit",
    "5k time": "5K-Zeit",
    "10K time": "10K-Zeit",
    "10k time": "10K-Zeit",
    "Final amount": "Endbetrag",
    "final amount": "Endbetrag",
    "Total contributed": "Gesamt eingezahlt",
    "total contributed": "Gesamt eingezahlt",
    "Weight lost": "Gewichtsverlust",
    "weight lost": "Gewichtsverlust",
    "A1c estimated": "HbA1c geschätzt",
    "a1c estimated": "HbA1c geschätzt",
    "Glucose": "Glukose",
    "Est. A1C": "Gesch. HbA1c",
    "Age (years)": "Alter (Jahre)",
    "Age in years": "Alter in Jahren",
    "age in years": "Alter in Jahren",
    
    # Spanish-specific additions
    "Volumen Final": "Endvolumen",
    "volumen final": "Endvolumen",
    "Altura Libre Ok": "Freie Höhe OK",
    "Peso Est Kg": "Geschätztes Gewicht kg",
    "Volumen (Liter)": "Volumen (Liter)",
    "volumen (liter)": "Volumen (Liter)",
    "Espesor Recomendado": "Empfohlene Dicke",
    "espesor recomendado": "Empfohlene Dicke",
    "Agua Recomendada": "Empfohlenes Wasser",
    "agua recomendada": "Empfohlenes Wasser",
}

def translate_output_label(label):
    """Translate a single output label from EN/ES to DE."""
    if not label or not isinstance(label, str):
        return label
    
    # Direct lookup
    if label in OUTPUT_TRANSLATIONS:
        return OUTPUT_TRANSLATIONS[label]
    
    # Try case-insensitive
    if label.lower() in OUTPUT_TRANSLATIONS:
        return OUTPUT_TRANSLATIONS[label.lower()]
    
    return label  # Keep as-is if no translation found


def fix_calculator_outputs(filepath):
    """Fix German output labels in a single calculator JSON file."""
    with open(filepath, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    i18n = data.get('i18n', {})
    de = i18n.get('de', {})
    if not de:
        return False
    
    outputs = de.get('outputs', {})
    if not outputs:
        return False
    
    modified = False
    new_outputs = {}
    for key, val in outputs.items():
        new_val = translate_output_label(val)
        if new_val != val:
            modified = True
        new_outputs[key] = new_val
    
    if modified:
        de['outputs'] = new_outputs
        data['i18n']['de'] = de
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        return True
    
    return False


def main():
    files = sorted(glob.glob(os.path.join(CALC_DIR, "*.json")))
    fixed = 0
    skipped = 0
    
    for f in files:
        if fix_calculator_outputs(f):
            fixed += 1
            print(f"  FIXED: {os.path.basename(f)}")
        else:
            skipped += 1
    
    print(f"\nTotal: {len(files)} | Fixed: {fixed} | Skipped: {skipped}")

if __name__ == '__main__':
    main()
