#!/usr/bin/env python3
"""Fix Italian pseudo-text: remove markers and translate Spanish→Italian patterns."""

import json, os, glob, re

CALC_DIR = r"C:\Microsaas\obra\src\calculators"

REPLACEMENTS = [
    # Articles and prepositions
    (r'\bEl\b', 'Il'), (r'\bel\b', 'il'),
    (r'\bLas\b', 'Le'), (r'\blas\b', 'le'),
    (r'\bLos\b', 'I'), (r'\blos\b', 'i'),
    (r'\bUn\b', 'Un'), (r'\buna\b', 'una'),
    (r'\bdel\b(?!\s+el)', 'del'),
    (r'\bdel el\b', 'del'),
    (r'\bin el\b', 'nel'),
    (r'\bin la\b', 'nella'),
    (r'\bal el\b', 'al'),
    # Verbs
    (r'\bcalcular\b', 'calcolare'),
    (r'\bcalcula\b', 'calcola'),
    (r'\bcalculado\b', 'calcolato'),
    (r'\bcalculada\b', 'calcolata'),
    (r'\bcalculados\b', 'calcolati'),
    (r'\bintroduce\b', 'inserisci'),
    (r'\bintroducir\b', 'inserire'),
    (r'\bobtener\b', 'ottenere'),
    (r'\bobtiene\b', 'ottiene'),
    (r'\bobtenga\b', 'ottenga'),
    (r'\bmedir\b', 'misurare'),
    (r'\bmide\b', 'misura'),
    (r'\busar\b', 'usare'),
    (r'\busa\b', 'usa'),
    (r'\butilice\b', 'utilizzi'),
    (r'\butiliza\b', 'utilizza'),
    (r'\bseleccione\b', 'selezioni'),
    (r'\bselecciona\b', 'seleziona'),
    (r'\belija\b', 'scelga'),
    (r'\belige\b', 'sceglie'),
    (r'\bverifique\b', 'verifichi'),
    (r'\bverifica\b', 'verifica'),
    (r'\bconsidere\b', 'consideri'),
    (r'\bconsidera\b', 'considera'),
    (r'\bconsedira\b', 'considera'),
    (r'\bconsedire\b', 'considerare'),
    (r'\bajusta\b', 'regola'),
    (r'\bajuste\b', 'regoli'),
    (r'\brealice\b', 'esegua'),
    (r'\brealizar\b', 'eseguire'),
    (r'\bhacer\b', 'fare'),
    (r'\bhaga\b', 'faccia'),
    (r'\btiene\b', 'ha'),
    (r'\btienen\b', 'hanno'),
    (r'\bes(?=\s)', '\u00e8'),
    (r'\besta\b', 'questa'),
    (r'\besto\b', 'questo'),
    (r'\bestos\b', 'questi'),
    (r'\bestas\b', 'queste'),
    (r'\beste\b', 'questo'),
    # Conjunctions
    (r'\bque\b', 'che'),
    (r'\by\b', 'e'),
    (r'\bo\b', 'o'),
    (r'\bpero\b', 'ma'),
    (r'\bpara\b', 'per'),
    (r'\bcomo\b', 'come'),
    (r'\bcuando\b', 'quando'),
    (r'\bdonde\b', 'dove'),
    (r'\bporque\b', 'perch\u00e9'),
    (r'\bsi\b', 'se'),
    # Nouns / concepts
    (r'\bresultado\b', 'risultato'),
    (r'\bresultados\b', 'risultati'),
    (r'\bc\u00e1lculo\b', 'calcolo'),
    (r'\bcalculo\b', 'calcolo'),
    (r'\bcalculadora\b', 'calcolatrice'),
    (r'\bherramienta\b', 'strumento'),
    (r'\bherramientas\b', 'strumenti'),
    (r'\bgratis\b', 'gratuito'),
    (r'\bgratuita\b', 'gratuita'),
    (r'\bgratuito\b', 'gratuito'),
    (r'\bvalor\b', 'valore'),
    (r'\bvalores\b', 'valori'),
    (r'\bunidad\b', 'unit\u00e0'),
    (r'\bunidades\b', 'unit\u00e0'),
    (r'\bcantidad\b', 'quantit\u00e0'),
    (r'\bmedida\b', 'misura'),
    (r'\bmedidas\b', 'misure'),
    (r'\bmerma\b', 'sfrido'),
    (r'\bdesperdicio\b', 'spreco'),
    (r'\bpaso\b', 'passo'),
    (r'\bpasos\b', 'passi'),
    (r'\berror\b', 'errore'),
    (r'\berrores\b', 'errori'),
    (r'\bejemplo\b', 'esempio'),
    (r'\bejemplos\b', 'esempi'),
    (r'\bf\u00f3rmula\b', 'formula'),
    (r'\bformula\b', 'formula'),
    (r'\bformulas\b', 'formule'),
    (r'\becuaci\u00f3n\b', 'equazione'),
    (r'\becuacion\b', 'equazione'),
    (r'\bdatos\b', 'dati'),
    (r'\bentrada\b', 'input'),
    (r'\bsalida\b', 'output'),
    (r'\bproyecto\b', 'progetto'),
    (r'\bproyectos\b', 'progetti'),
    (r'\btiempo\b', 'tempo'),
    (r'\bvelocidad\b', 'velocit\u00e0'),
    (r'\bvelocit\u00e1\b', 'velocit\u00e0'),
    (r'\bdistancia\b', 'distanza'),
    (r'\baltura\b', 'altezza'),
    (r'\bpeso\b', 'peso'),
    (r'\bpresi\u00f3n\b', 'pressione'),
    (r'\bpresion\b', 'pressione'),
    (r'\btemperatura\b', 'temperatura'),
    (r'\benerg\u00eda\b', 'energia'),
    (r'\benergia\b', 'energia'),
    (r'\bpotencia\b', 'potenza'),
    (r'\bfuerza\b', 'forza'),
    (r'\bcoste\b', 'costo'),
    (r'\bcostes\b', 'costi'),
    (r'\bprecio\b', 'prezzo'),
    (r'\bprecios\b', 'prezzi'),
    (r'\bdinero\b', 'denaro'),
    (r'\beuros\b', 'euro'),
    (r'\bd\u00f3lares\b', 'dollari'),
    (r'\bdolares\b', 'dollari'),
    (r'\bpago\b', 'pagamento'),
    (r'\bpagos\b', 'pagamenti'),
    (r'\bimpuesto\b', 'imposta'),
    (r'\bimpuestos\b', 'imposte'),
    (r'\bdescuento\b', 'sconto'),
    (r'\bmargen\b', 'margine'),
    (r'\bbeneficio\b', 'profitto'),
    (r'\bingreso\b', 'reddito'),
    (r'\bingresos\b', 'entrate'),
    (r'\bgasto\b', 'spesa'),
    (r'\bgastos\b', 'spese'),
    (r'\bahorro\b', 'risparmio'),
    (r'\bahorros\b', 'risparmi'),
    (r'\bdeuda\b', 'debito'),
    (r'\bdeudas\b', 'debiti'),
    (r'\binter\u00e9s\b', 'interesse'),
    (r'\binteres\b', 'interesse'),
    (r'\btasa\b', 'tasso'),
    (r'\btasas\b', 'tassi'),
    (r'\bporcentaje\b', 'percentuale'),
    (r'\ba\u00f1o\b', 'anno'),
    (r'\ba\u00f1os\b', 'anni'),
    (r'\banos\b', 'anni'),
    (r'\bmes\b', 'mese'),
    (r'\bmeses\b', 'mesi'),
    (r'\bd\u00eda\b', 'giorno'),
    (r'\bdia\b', 'giorno'),
    (r'\bd\u00edas\b', 'giorni'),
    (r'\bdias\b', 'giorni'),
    (r'\bhora\b', 'ora'),
    (r'\bhoras\b', 'ore'),
    (r'\bminuto\b', 'minuto'),
    (r'\bminutos\b', 'minuti'),
    (r'\bsegundo\b', 'secondo'),
    (r'\bsegundos\b', 'secondi'),
    (r'\bagua\b', 'acqua'),
    (r'\baire\b', 'aria'),
    (r'\btierra\b', 'terra'),
    (r'\bfuego\b', 'fuoco'),
    (r'\bluz\b', 'luce'),
    (r'\bsol\b', 'sole'),
    (r'\bluna\b', 'luna'),
    # Adjectives / adverbs
    (r'\bnecesario\b', 'necessario'),
    (r'\bnecesaria\b', 'necessaria'),
    (r'\bnecesarios\b', 'necessari'),
    (r'\bimportante\b', 'importante'),
    (r'\bimportantes\b', 'importanti'),
    (r'\bprincipal\b', 'principale'),
    (r'\bprincipales\b', 'principali'),
    (r'\bb\u00e1sico\b', 'di base'),
    (r'\bbasico\b', 'di base'),
    (r'\bb\u00e1sica\b', 'di base'),
    (r'\bbasica\b', 'di base'),
    (r'\bcorrecto\b', 'corretto'),
    (r'\bcorrecta\b', 'corretta'),
    (r'\bcorrectos\b', 'corretti'),
    (r'\bincorrecto\b', 'errato'),
    (r'\bincorrecta\b', 'errata'),
    (r'\bm\u00e1ximo\b', 'massimo'),
    (r'\bmaximo\b', 'massimo'),
    (r'\bm\u00e1xima\b', 'massima'),
    (r'\bmaxima\b', 'massima'),
    (r'\bm\u00ednimo\b', 'minimo'),
    (r'\bminimo\b', 'minimo'),
    (r'\bm\u00ednima\b', 'minima'),
    (r'\bminima\b', 'minima'),
    (r'\bpromedio\b', 'medio'),
    (r'\btotal\b', 'totale'),
    (r'\btotales\b', 'totali'),
    (r'\bactual\b', 'attuale'),
    (r'\bactuales\b', 'attuali'),
    (r'\binicial\b', 'iniziale'),
    (r'\biniciales\b', 'iniziali'),
    (r'\bfinal\b', 'finale'),
    (r'\bfinales\b', 'finali'),
    (r'\bsiguiente\b', 'seguente'),
    (r'\bsiguientes\b', 'seguenti'),
    (r'\banterior\b', 'precedente'),
    (r'\banteriores\b', 'precedenti'),
    (r'\bgrande\b', 'grande'),
    (r'\bgrandes\b', 'grandi'),
    (r'\bpeque\u00f1o\b', 'piccolo'),
    (r'\bpequeno\b', 'piccolo'),
    (r'\bpeque\u00f1a\b', 'piccola'),
    (r'\bpequena\b', 'piccola'),
    (r'\bnuevo\b', 'nuovo'),
    (r'\bnueva\b', 'nuova'),
    (r'\bnuevos\b', 'nuovi'),
    (r'\br\u00e1pido\b', 'veloce'),
    (r'\brapido\b', 'veloce'),
    (r'\br\u00e1pida\b', 'veloce'),
    (r'\brapida\b', 'veloce'),
    (r'\blento\b', 'lento'),
    (r'\blenta\b', 'lenta'),
    (r'\bf\u00e1cil\b', 'facile'),
    (r'\bfacil\b', 'facile'),
    (r'\bdif\u00edcil\b', 'difficile'),
    (r'\bdificil\b', 'difficile'),
    (r'\bmejor\b', 'migliore'),
    (r'\bpeor\b', 'peggiore'),
    (r'\bmayor\b', 'maggiore'),
    (r'\bmenor\b', 'minore'),
    (r'\balto\b', 'alto'),
    (r'\bbajo\b', 'basso'),
    (r'\bbaja\b', 'bassa'),
    (r'\bdiario\b', 'giornaliero'),
    (r'\bdiaria\b', 'giornaliera'),
    (r'\bmensual\b', 'mensile'),
    (r'\bmensuales\b', 'mensili'),
    (r'\banual\b', 'annuale'),
    (r'\banuales\b', 'annuali'),
    (r'\butilizando\b', 'utilizzando'),
    (r'\busando\b', 'usando'),
    (r'\bbasado\b', 'basato'),
    (r'\bbasada\b', 'basata'),
    (r'\bincluyendo\b', 'includendo'),
    (r'\bincluye\b', 'include'),
    (r'\bincluyen\b', 'includono'),
    # Numbers / quantifiers
    (r'\bm\u00e1s\b', 'pi\u00f9'),
    (r'\bmas\b(?!\s+\w)', 'pi\u00f9'),
    (r'\bmenos\b', 'meno'),
    (r'\bmucho\b', 'molto'),
    (r'\bmucha\b', 'molta'),
    (r'\bmuchos\b', 'molti'),
    (r'\bmuchas\b', 'molte'),
    (r'\bpoco\b', 'poco'),
    (r'\bpoca\b', 'poca'),
    (r'\bpocos\b', 'pochi'),
    (r'\bpocas\b', 'poche'),
    (r'\btodo\b', 'tutto'),
    (r'\btoda\b', 'tutta'),
    (r'\btodos\b', 'tutti'),
    (r'\btodas\b', 'tutte'),
    (r'\bcada\b', 'ogni'),
    (r'\balgunos\b', 'alcuni'),
    (r'\balgunas\b', 'alcune'),
    (r'\bninguno\b', 'nessuno'),
    (r'\bninguna\b', 'nessuna'),
    (r'\botro\b', 'altro'),
    (r'\botra\b', 'altra'),
    (r'\botros\b', 'altri'),
    (r'\botras\b', 'altre'),
    (r'\bmismo\b', 'stesso'),
    (r'\bmisma\b', 'stessa'),
    # Misc common patterns
    (r'\bsegun\b', 'secondo'),
    (r'\bseg\u00fan\b', 'secondo'),
    (r'\breferincia\b', 'riferimento'),
    (r'\brefirencia\b', 'riferimento'),
    (r'\breferencia\b', 'riferimento'),
    (r'\bsirve\b', 'serve'),
    (r'\bsirven\b', 'servono'),
    (r'\bpuede\b', 'pu\u00f2'),
    (r'\bpueden\b', 'possono'),
    (r'\bdebe\b', 'deve'),
    (r'\bdeben\b', 'devono'),
    (r'\bdeber\u00eda\b', 'dovrebbe'),
    (r'\bdeberia\b', 'dovrebbe'),
    (r'\bdeber\u00edan\b', 'dovrebbero'),
    (r'\bdeberian\b', 'dovrebbero'),
    (r'\bhay\b', 'c\'\u00e8'),
    (r'\bhaber\b', 'avere'),
    (r'\bhacer\b', 'fare'),
    (r'\bhecho\b', 'fatto'),
    (r'\bdecir\b', 'dire'),
    (r'\bdice\b', 'dice'),
    (r'\bdicen\b', 'dicono'),
    (r'\bver\b', 'vedere'),
    (r'\bve\b', 'vede'),
    (r'\bven\b', 'vedono'),
    (r'\bsaber\b', 'sapere'),
    (r'\bsabe\b', 'sa'),
    (r'\bsaben\b', 'sanno'),
    (r'\bquerer\b', 'volere'),
    (r'\bquiere\b', 'vuole'),
    (r'\bquieren\b', 'vogliono'),
    (r'\bponer\b', 'mettere'),
    (r'\bpone\b', 'mette'),
    (r'\bponen\b', 'mettono'),
    (r'\bllegar\b', 'arrivare'),
    (r'\bllega\b', 'arriva'),
    (r'\bsalir\b', 'uscire'),
    (r'\bsale\b', 'esce'),
    # Fix pseudo-Italian hybrid words
    (r'\baceleraci\u00f3n\b', 'accelerazione'),
    (r'\baceleracion\b', 'accelerazione'),
    (r'\bvelocit\u00e1\b', 'velocit\u00e0'),
    (r'\bpresi\u00f3n\b', 'pressione'),
    (r'\bopacorial\b', 'materiale'),
    (r'\bopacoriales\b', 'materiali'),
    (r'\bnonrmal\b', 'normale'),
    (r'\brinal\b', 'renale'),
    (r'\binfermedad\b', 'malattia'),
    (r'\bcr\u00f3nica\b', 'cronica'),
    (r'\bcronica\b', 'cronica'),
    (r'\bevaluaci\u00f3n\b', 'valutazione'),
    (r'\bevaluacion\b', 'valutazione'),
    (r'\bm\u00e9dica\b', 'medica'),
    (r'\bmedica\b', 'medica'),
    (r'\bhidrataci\u00f3n\b', 'idratazione'),
    (r'\bhidratacion\b', 'idratazione'),
    (r'\bejercicio\b', 'esercizio'),
    (r'\bejercicios\b', 'esercizi'),
    (r'\bvaso\b', 'bicchiere'),
    (r'\bcontiine\b', 'contiene'),
    (r'\battivit\u00e0\b', 'attivit\u00e0'),
    (r'\battivita\b', 'attivit\u00e0'),
    (r'\bmodirado\b', 'moderato'),
    (r'\bmodirada\b', 'moderata'),
    (r'\bmetab\u00f3lica\b', 'metabolica'),
    (r'\bmetabolica\b', 'metabolica'),
    (r'\bproteina\b', 'proteina'),
    (r'\bprote\u00edna\b', 'proteina'),
    (r'\bcalor\u00eda\b', 'caloria'),
    (r'\bcaloria\b', 'caloria'),
    (r'\bcalor\u00edas\b', 'calorie'),
    (r'\bcalorias\b', 'calorie'),
    (r'\bcarboidrati\b', 'carboidrati'),
    (r'\bgrassi\b', 'grassi'),
    (r'\bgrasa\b', 'grasso'),
    (r'\bgrasas\b', 'grassi'),
    (r'\bvitamina\b', 'vitamina'),
    (r'\bvitaminas\b', 'vitamine'),
    (r'\bmineral\b', 'minerale'),
    (r'\bminerales\b', 'minerali'),
    (r'\bcolesterol\b', 'colesterolo'),
    (r'\bpresi\u00f3n arterial\b', 'pressione arteriosa'),
    (r'\bpresion arterial\b', 'pressione arteriosa'),
    (r'\bdiab\u00e9tico\b', 'diabetico'),
    (r'\bdiabetico\b', 'diabetico'),
    (r'\bprediabetico\b', 'prediabetico'),
    (r'\bprediab\u00e9tico\b', 'prediabetico'),
    (r'\bovulaci\u00f3n\b', 'ovulazione'),
    (r'\bovulacion\b', 'ovulazione'),
    (r'\bperiodo\b', 'periodo'),
    (r'\bperiodos\b', 'periodi'),
    (r'\bf\u00e9rtil\b', 'fertile'),
    (r'\bfertil\b', 'fertile'),
    (r'\bembarazo\b', 'gravidanza'),
    (r'\bembarazada\b', 'incinta'),
    (r'\bparto\b', 'parto'),
    (r'\bnacimiento\b', 'nascita'),
    (r'\bnacer\b', 'nascere'),
    (r'\bnace\b', 'nasce'),
    (r'\bnacen\b', 'nascono'),
    (r'\bmuerte\b', 'morte'),
    (r'\bmorir\b', 'morire'),
    (r'\bmuere\b', 'muore'),
    (r'\bguadagnon\b', 'aumento'),
    (r'\bguadagnar\b', 'guadagnare'),
    (r'\bauminto\b', 'aumento'),
    (r'\baumintar\b', 'aumentare'),
    (r'\bobesedad\b', 'obesit\u00e0'),
    (r'\bobesidad\b', 'obesit\u00e0'),
    (r'\brichiedi\b', 'richiede'),
    (r'\brichieder\b', 'richiedere'),
    (r'\bminsuale\b', 'mensile'),
    (r'\bminsual\b', 'mensile'),
    (r'\balcanzar\b', 'raggiungere'),
    (r'\balcanza\b', 'raggiunge'),
    (r'\bmeta\b', 'obiettivo'),
    (r'\beducativa\b', 'educativo'),
    (r'\beducativo\b', 'educativo'),
    (r'\bimprevistos\b', 'imprevisti'),
    (r'\bimprevisto\b', 'imprevisto'),
    (r'\bestimado\b', 'stimato'),
    (r'\bestimada\b', 'stimata'),
    (r'\bestimar\b', 'stimare'),
    (r'\brepresencos\u00e0\b', 'rappresenta'),
    (r'\brepresencia\b', 'rappresenta'),
    (r'\bmantinimiinto\b', 'mantenimento'),
    (r'\bmantenimiinto\b', 'mantenimento'),
    (r'\binerg\u00eda\b', 'energia'),
    (r'\binergia\b', 'energia'),
    (r'\bperdir\b', 'perdere'),
    (r'\bperder\b', 'perdere'),
    (r'\bganar\b', 'guadagnare'),
    (r'\bgana\b', 'guadagna'),
    (r'\bganan\b', 'guadagnano'),
    (r'\brespectivaminte\b', 'rispettivamente'),
    (r'\brespectivamente\b', 'rispettivamente'),
    (r'\bperosedad\b', 'porosit\u00e0'),
    (r'\bporosidad\b', 'porosit\u00e0'),
    (r'\bsupperto\b', 'supporto'),
    (r'\bsoporte\b', 'supporto'),
    (r'\bcrefondazione\b', 'crescita'),
    (r'\bcrecimiento\b', 'crescita'),
    (r'\bcompuesta\b', 'composta'),
    (r'\bcompuesto\b', 'composto'),
    (r'\binverse\u00f3n\b', 'investimento'),
    (r'\binversi\u00f3n\b', 'investimento'),
    (r'\binversion\b', 'investimento'),
    (r'\bdiferincia\b', 'differenza'),
    (r'\bdiferencia\b', 'differenza'),
    (r'\babsolute\b', 'assoluta'),
    (r'\babsoluta\b', 'assoluta'),
    (r'\brelative\b', 'relativa'),
    (r'\brelativa\b', 'relativa'),
    (r'\bchange\b', 'cambiamento'),
    (r'\bcambio\b', 'cambiamento'),
    (r'\bfinel\b', 'finale'),
    (r'\binitial\b', 'iniziale'),
    (r'\baclaramiinto\b', 'clearance'),
    (r'\bnum\u00e9rico\b', 'numerico'),
    (r'\bnumerico\b', 'numerico'),
    (r'\bnum\u00e9rica\b', 'numerica'),
    (r'\bnumerica\b', 'numerica'),
    (r'\bvol\u00famen\b', 'volume'),
    (r'\bvolumen\b', 'volume'),
    (r'\bvol\u00famenes\b', 'volumi'),
    (r'\bvolumenes\b', 'volumi'),
    (r'\b\u00e1rea\b', 'area'),
    (r'\barea\b', 'area'),
    (r'\b\u00e1reas\b', 'aree'),
    (r'\bareas\b', 'aree'),
    (r'\blongitud\b', 'lunghezza'),
    (r'\banchura\b', 'larghezza'),
    (r'\baltitud\b', 'altitudine'),
    (r'\bprofundidad\b', 'profondit\u00e0'),
    (r'\bdensidad\b', 'densit\u00e0'),
    (r'\bgravedad\b', 'gravit\u00e0'),
    (r'\bhumedad\b', 'umidit\u00e0'),
    (r'\btemperatura\b', 'temperatura'),
    (r'\bcorriente\b', 'corrente'),
    (r'\bvoltaje\b', 'tensione'),
    (r'\bcapacidad\b', 'capacit\u00e0'),
    (r'\bresistencia\b', 'resistenza'),
    (r'\bfrecuencia\b', 'frequenza'),
    (r'\bpotencia\b', 'potenza'),
    (r'\bcantidad\b', 'quantit\u00e0'),
    (r'\bconcentracion\b', 'concentrazione'),
    (r'\bconcentraci\u00f3n\b', 'concentrazione'),
    (r'\bdilucion\b', 'diluizione'),
    (r'\bdiluci\u00f3n\b', 'diluizione'),
    (r'\bmolaridad\b', 'molarit\u00e0'),
    (r'\bnormalidad\b', 'normalit\u00e0'),
    (r'\bacidez\b', 'acidit\u00e0'),
    (r'\bbasicidad\b', 'basicit\u00e0'),
    (r'\bneutro\b', 'neutro'),
    (r'\bneutra\b', 'neutra'),
    (r'\bacido\b', 'acido'),
    (r'\b\u00e1cido\b', 'acido'),
    (r'\bbase\b', 'base'),
    (r'\bbases\b', 'basi'),
    (r'\bsoluci\u00f3n\b', 'soluzione'),
    (r'\bsolucion\b', 'soluzione'),
    (r'\bsoluto\b', 'soluto'),
    (r'\bsolvente\b', 'solvente'),
    (r'\bdisoluci\u00f3n\b', 'soluzione'),
    (r'\bdisolucion\b', 'soluzione'),
    (r'\bprecipitado\b', 'precipitato'),
    (r'\bcatalizador\b', 'catalizzatore'),
    (r'\breacci\u00f3n\b', 'reazione'),
    (r'\breaccion\b', 'reazione'),
    (r'\bproducto\b', 'prodotto'),
    (r'\bproductos\b', 'prodotti'),
    (r'\breactivo\b', 'reagente'),
    (r'\breactivos\b', 'reagenti'),
    (r'\bqu\u00edmico\b', 'chimico'),
    (r'\bquimico\b', 'chimico'),
    (r'\bqu\u00edmica\b', 'chimica'),
    (r'\bquimica\b', 'chimica'),
    (r'\bf\u00edsico\b', 'fisico'),
    (r'\bfisico\b', 'fisico'),
    (r'\bf\u00edsica\b', 'fisica'),
    (r'\bfisica\b', 'fisica'),
    (r'\bbiol\u00f3gico\b', 'biologico'),
    (r'\bbiologico\b', 'biologico'),
    (r'\bel\u00e9ctrico\b', 'elettrico'),
    (r'\belectrico\b', 'elettrico'),
    (r'\bel\u00e9ctrica\b', 'elettrica'),
    (r'\belectrica\b', 'elettrica'),
    (r'\bt\u00e9rmico\b', 'termico'),
    (r'\btermico\b', 'termico'),
    (r'\bt\u00e9rmica\b', 'termica'),
    (r'\btermica\b', 'termica'),
    (r'\bmec\u00e1nico\b', 'meccanico'),
    (r'\bmecanico\b', 'meccanico'),
    (r'\bhidr\u00e1ulico\b', 'idraulico'),
    (r'\bhidraulico\b', 'idraulico'),
    (r'\bneum\u00e1tico\b', 'pneumatico'),
    (r'\bneumatico\b', 'pneumatico'),
    (r'\bestructural\b', 'strutturale'),
    (r'\bestructurales\b', 'strutturali'),
    (r'\barquitect\u00f3nico\b', 'architettonico'),
    (r'\barquitectonico\b', 'architettonico'),
    (r'\bconstrucci\u00f3n\b', 'costruzione'),
    (r'\bconstruccion\b', 'costruzione'),
    (r'\bedificaci\u00f3n\b', 'edificio'),
    (r'\bedificacion\b', 'edificio'),
    (r'\bvivienda\b', 'abitazione'),
    (r'\bviviendas\b', 'abitazioni'),
    (r'\bcasa\b', 'casa'),
    (r'\bcasas\b', 'case'),
    (r'\bedificio\b', 'edificio'),
    (r'\bedificios\b', 'edifici'),
    (r'\bcarretera\b', 'strada'),
    (r'\bcarreteras\b', 'strade'),
    (r'\bpuente\b', 'ponte'),
    (r'\bpuentes\b', 'ponti'),
    (r'\bt\u00fanel\b', 'tunnel'),
    (r'\btunel\b', 'tunnel'),
    (r'\bpresupuesto\b', 'budget'),
    (r'\bpresupuestos\b', 'budget'),
    (r'\bplanificaci\u00f3n\b', 'pianificazione'),
    (r'\bplanificacion\b', 'pianificazione'),
    (r'\bestimaci\u00f3n\b', 'stima'),
    (r'\bestimacion\b', 'stima'),
    (r'\bc\u00e1lculos\b', 'calcoli'),
    (r'\bcalculo\b', 'calcolo'),
    (r'\bcalculos\b', 'calcoli'),
    (r'\bmedici\u00f3n\b', 'misurazione'),
    (r'\bmedicion\b', 'misurazione'),
    (r'\bmediciones\b', 'misurazioni'),
    (r'\bcertificaci\u00f3n\b', 'certificazione'),
    (r'\bcertificacion\b', 'certificazione'),
    (r'\binspecci\u00f3n\b', 'ispezione'),
    (r'\binspeccion\b', 'ispezione'),
    (r'\bcontrol\b', 'controllo'),
    (r'\bcontroles\b', 'controlli'),
    (r'\bcalidad\b', 'qualit\u00e0'),
    (r'\bseguridad\b', 'sicurezza'),
    (r'\bseguro\b', 'sicuro'),
    (r'\briesgo\b', 'rischio'),
    (r'\briesgos\b', 'rischi'),
    (r'\bpeligro\b', 'pericolo'),
    (r'\bpeligros\b', 'pericoli'),
    (r'\bprotecci\u00f3n\b', 'protezione'),
    (r'\bproteccion\b', 'protezione'),
    (r'\bequipo\b', 'attrezzatura'),
    (r'\bequipos\b', 'attrezzature'),
    (r'\bmaquinaria\b', 'macchinario'),
    (r'\bmaquinarias\b', 'macchinari'),
    (r'\bveh\u00edculo\b', 'veicolo'),
    (r'\bvehiculo\b', 'veicolo'),
    (r'\bveh\u00edculos\b', 'veicoli'),
    (r'\bvehiculos\b', 'veicoli'),
    (r'\btransporte\b', 'trasporto'),
    (r'\btransportes\b', 'trasporti'),
    (r'\blog\u00edstica\b', 'logistica'),
    (r'\blogistica\b', 'logistica'),
    (r'\balmac\u00e9n\b', 'magazzino'),
    (r'\balmacen\b', 'magazzino'),
    (r'\binventario\b', 'inventario'),
    (r'\binventarios\b', 'inventari'),
    (r'\bexistencia\b', 'esistenza'),
    (r'\bexistencias\b', 'esistenze'),
    (r'\bdemanda\b', 'domanda'),
    (r'\boferta\b', 'offerta'),
    (r'\bmercado\b', 'mercato'),
    (r'\bmercados\b', 'mercati'),
    (r'\bcliente\b', 'cliente'),
    (r'\bclientes\b', 'clienti'),
    (r'\bproveedor\b', 'fornitore'),
    (r'\bproveedores\b', 'fornitori'),
    (r'\bcompetencia\b', 'concorrenza'),
    (r'\bcompetidor\b', 'concorrente'),
    (r'\bcompetidores\b', 'concorrenti'),
    (r'\bestrategia\b', 'strategia'),
    (r'\bestrategias\b', 'strategie'),
    (r'\bobjetivo\b', 'obiettivo'),
    (r'\bobjetivos\b', 'obiettivi'),
    (r'\bmeta\b', 'obiettivo'),
    (r'\bmetas\b', 'obiettivi'),
    (r'\bindicador\b', 'indicatore'),
    (r'\bindicadores\b', 'indicatori'),
    (r'\ban\u00e1lisis\b', 'analisi'),
    (r'\banalisis\b', 'analisi'),
    (r'\bevaluar\b', 'valutare'),
    (r'\beval\u00faa\b', 'valuta'),
    (r'\bevalua\b', 'valuta'),
    (r'\bcomparar\b', 'confrontare'),
    (r'\bcompara\b', 'confronta'),
    (r'\bcomparaci\u00f3n\b', 'confronto'),
    (r'\bcomparacion\b', 'confronto'),
    (r'\bselecci\u00f3n\b', 'selezione'),
    (r'\bseleccion\b', 'selezione'),
    (r'\bopci\u00f3n\b', 'opzione'),
    (r'\bopcion\b', 'opzione'),
    (r'\bopciones\b', 'opzioni'),
    (r'\balternativa\b', 'alternativa'),
    (r'\balternativas\b', 'alternative'),
    (r'\brecomendaci\u00f3n\b', 'raccomandazione'),
    (r'\brecomendacion\b', 'raccomandazione'),
    (r'\brecomendar\b', 'raccomandare'),
    (r'\bsugerir\b', 'suggerire'),
    (r'\bsugiere\b', 'suggerisce'),
    (r'\bconsejo\b', 'consiglio'),
    (r'\bconsejos\b', 'consigli'),
    (r'\bnota\b', 'nota'),
    (r'\bnotas\b', 'note'),
    (r'\baviso\b', 'avviso'),
    (r'\badvertencia\b', 'avvertenza'),
    (r'\badvertencias\b', 'avvertenze'),
    (r'\bprecauci\u00f3n\b', 'precauzione'),
    (r'\bprecaucion\b', 'precauzione'),
    (r'\bprecauciones\b', 'precauzioni'),
    (r'\bcuidado\b', 'attenzione'),
    (r'\bcuidados\b', 'cure'),
    (r'\batencion\b', 'attenzione'),
    (r'\batenci\u00f3n\b', 'attenzione'),
    (r'\bimportante\b', 'importante'),
    (r'\bfundamental\b', 'fondamentale'),
    (r'\besencial\b', 'essenziale'),
    (r'\besenciales\b', 'essenziali'),
    (r'\bcr\u00edtico\b', 'critico'),
    (r'\bcritico\b', 'critico'),
    (r'\bcr\u00edtica\b', 'critica'),
    (r'\bcritica\b', 'critica'),
    (r'\bcr\u00edticos\b', 'critici'),
    (r'\bcriticos\b', 'critici'),
    (r'\bideal\b', 'ideale'),
    (r'\bideales\b', 'ideali'),
    (r'\b\u00f3ptimo\b', 'ottimale'),
    (r'\boptimo\b', 'ottimale'),
    (r'\b\u00f3ptima\b', 'ottimale'),
    (r'\boptima\b', 'ottimale'),
    (r'\breal\b', 'reale'),
    (r'\breales\b', 'reali'),
    (r'\bte\u00f3rico\b', 'teorico'),
    (r'\bteorico\b', 'teorico'),
    (r'\bte\u00f3rica\b', 'teorica'),
    (r'\bteorica\b', 'teorica'),
    (r'\bpr\u00e1ctico\b', 'pratico'),
    (r'\bpractico\b', 'pratico'),
    (r'\bpr\u00e1ctica\b', 'pratica'),
    (r'\bpractica\b', 'pratica'),
    (r'\baproximado\b', 'approssimato'),
    (r'\baproximada\b', 'approssimata'),
    (r'\bexacto\b', 'esatto'),
    (r'\bexacta\b', 'esatta'),
    (r'\bpreciso\b', 'preciso'),
    (r'\bprecisa\b', 'precisa'),
    (r'\baceptable\b', 'accettabile'),
    (r'\baceptables\b', 'accettabili'),
    (r'\bv\u00e1lido\b', 'valido'),
    (r'\bvalido\b', 'valido'),
    (r'\bv\u00e1lida\b', 'valida'),
    (r'\bvalida\b', 'valida'),
    (r'\bv\u00e1lidos\b', 'validi'),
    (r'\bvalidos\b', 'validi'),
    (r'\bfiable\b', 'affidabile'),
    (r'\bfiables\b', 'affidabili'),
    (r'\bconfiable\b', 'affidabile'),
    (r'\bconfiables\b', 'affidabili'),
    (r'\butil\b', 'utile'),
    (r'\b\u00fatil\b', 'utile'),
    (r'\butiles\b', 'utili'),
    (r'\b\u00fatiles\b', 'utili'),
    (r'\bnecesitas\b', 'necessiti'),
    (r'\bnecesitan\b', 'necessitano'),
    (r'\bnecesitamos\b', 'necessitiamo'),
    (r'\brequiere\b', 'richiede'),
    (r'\brequieren\b', 'richiedono'),
    (r'\bcontiene\b', 'contiene'),
    (r'\bcontienen\b', 'contengono'),
    (r'\bofrece\b', 'offre'),
    (r'\bofrecen\b', 'offrono'),
    (r'\bproporciona\b', 'fornisce'),
    (r'\bproporcionan\b', 'forniscono'),
    (r'\bgenera\b', 'genera'),
    (r'\bgeneran\b', 'generano'),
    (r'\bproduce\b', 'produce'),
    (r'\bproducen\b', 'producono'),
    (r'\bmuestra\b', 'mostra'),
    (r'\bmuestran\b', 'mostrano'),
    (r'\bpermite\b', 'permette'),
    (r'\bpermiten\b', 'permettono'),
    (r'\bgarantiza\b', 'garantisce'),
    (r'\bgarantizan\b', 'garantiscono'),
    (r'\bmejora\b', 'migliora'),
    (r'\bmejoran\b', 'migliorano'),
    (r'\baumenta\b', 'aumenta'),
    (r'\baumentan\b', 'aumentano'),
    (r'\breduce\b', 'riduce'),
    (r'\breducen\b', 'riducono'),
    (r'\belimina\b', 'elimina'),
    (r'\beliminan\b', 'eliminano'),
    (r'\bevita\b', 'evita'),
    (r'\bevitan\b', 'evitano'),
    (r'\bpreviene\b', 'previene'),
    (r'\bprevienen\b', 'prevengono'),
    (r'\bprotege\b', 'protegge'),
    (r'\bprotegen\b', 'proteggono'),
    (r'\bda\u00f1a\b', 'danneggia'),
    (r'\bdana\b', 'danneggia'),
    (r'\bda\u00f1an\b', 'danneggiano'),
    (r'\bdanan\b', 'danneggiano'),
    (r'\bdestruye\b', 'distrugge'),
    (r'\bdestruyen\b', 'distruggono'),
    (r'\brompe\b', 'rompe'),
    (r'\brompen\b', 'rompono'),
    (r'\bquiebra\b', 'rompe'),
    (r'\bquiebran\b', 'rompono'),
    (r'\bfalla\b', 'fallisce'),
    (r'\bfallan\b', 'falliscono'),
    (r'\bfunciona\b', 'funziona'),
    (r'\bfuncionan\b', 'funzionano'),
    (r'\bopera\b', 'opera'),
    (r'\boperan\b', 'operano'),
    (r'\btrabaja\b', 'lavora'),
    (r'\btrabajan\b', 'lavorano'),
    (r'\bact\u00faa\b', 'agisce'),
    (r'\bactua\b', 'agisce'),
    (r'\bact\u00faan\b', 'agiscono'),
    (r'\bactuan\b', 'agiscono'),
    (r'\breacciona\b', 'reagisce'),
    (r'\breaccionan\b', 'reagiscono'),
    (r'\bcalculates\b', 'calcola'),
    (r'\bestimates\b', 'stima'),
    (r'\bdetermines\b', 'determina'),
    (r'\bconverts\b', 'converte'),
    (r'\bmeasures\b', 'misura'),
    (r'\bprovides\b', 'fornisce'),
    (r'\bshows\b', 'mostra'),
    (r'\bdisplays\b', 'mostra'),
    (r'\bcomputes\b', 'calcola'),
    (r'\bevaluates\b', 'valuta'),
    (r'\bcalculating\b', 'calcolando'),
    (r'\bestimating\b', 'stimando'),
    (r'\bcomputing\b', 'calcolando'),
    (r'\bbased on\b', 'basato su'),
    (r'\binput values\b', 'valori inseriti'),
    (r'\bthe\b(?!\s+\w{1,2}\b)', 'il'),
]


def fix_italian_text(text):
    if not isinstance(text, str):
        return text
    
    # Remove marker
    text = text.replace('[IT-NEEDS-FIX] ', '').replace('[IT-NEEDS-FIX]', '')
    
    if not text.strip():
        return text
    
    # Apply replacements
    for pattern, replacement in REPLACEMENTS:
        text = re.sub(pattern, replacement, text)
    
    # Fix capitalization after period
    text = re.sub(r'\.\s+([a-z\u00e0-\u00ff])', lambda m: '. ' + m.group(1).upper(), text)
    
    # Fix multiple spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    # Ensure first letter is uppercase
    if text and text[0].islower() and text[0].isalpha():
        text = text[0].upper() + text[1:]
    
    return text


def main():
    files = sorted(
        f for f in glob.glob(os.path.join(CALC_DIR, "*.json"))
        if os.path.basename(f) not in ("calculators.json",)
        and "bak" not in f and "monolithic" not in f
    )

    fixed_files = 0
    fixed_fields = 0

    for fp in files:
        with open(fp, "r", encoding="utf-8-sig") as f:
            calc = json.load(f)

        it = calc.get("i18n", {}).get("it", {})
        changed = False

        for field in ["steps", "mistakes", "result_context", "formula_display", "example_label", "description"]:
            val = it.get(field, "")
            
            if isinstance(val, list):
                new_val = []
                for item in val:
                    fixed = fix_italian_text(str(item))
                    new_val.append(fixed)
                    if fixed != str(item):
                        changed = True
                        fixed_fields += 1
                if changed:
                    it[field] = new_val
            elif isinstance(val, str) and val:
                fixed = fix_italian_text(val)
                if fixed != val:
                    it[field] = fixed
                    changed = True
                    fixed_fields += 1

        if changed:
            with open(fp, "w", encoding="utf-8", newline="\n") as f:
                json.dump(calc, f, ensure_ascii=False, indent=2)
            fixed_files += 1

    print(f"Fixed Italian text in {fixed_files} files ({fixed_fields} fields)")


if __name__ == "__main__":
    main()
