#!/usr/bin/env python3
"""English narrative batch 4 — finance, health, science, everyday, sports, chemistry, electronics, conversion, statistics, climate, utilities, transport."""

import json, os, glob
CALC = r"C:\Microsaas\obra\src\calculators"
f = {}

# ── FINANCE ──
f["300"] = {"steps":["Enter the loan amount","Enter the annual interest rate","Enter the loan term in years","Calculate monthly rate: annual rate / 12","Calculate monthly payment using the amortization formula","Review total interest paid over the full term"],"mistakes":["Using the annual rate instead of the monthly rate in calculations","Forgetting that longer terms mean more total interest paid","Not accounting for origination fees and closing costs in the total loan cost"],"result_context":"Your monthly payment is {cuota_mensual}. Over {plazo} years you will pay {total_interes} in interest on top of the {monto} principal.","formula_display":"Monthly payment = P x r(1+r)^n / ((1+r)^n - 1) where r = annual rate / 12","example_label":"Monthly payment for a 10,000 loan at 5% over 3 years"}
f["301"] = {"steps":["Enter the initial principal amount","Enter the annual interest rate","Enter the compounding frequency (monthly, quarterly, annually)","Enter the time period in years","Calculate: future value = principal x (1 + rate/frequency)^(frequency x years)","The difference between future value and principal is the compound interest earned"],"mistakes":["Confusing simple interest with compound interest — the difference grows enormously over time","Using the nominal rate instead of the effective annual rate","Not accounting for inflation — real returns are lower than nominal"],"result_context":"Investing {principal} at {tasa}% for {anos} years grows to {monto_final}, earning {interes_ganado} in compound interest.","formula_display":"FV = P x (1 + r/n)^(n x t) where n = compounding periods per year","example_label":"Future value of 5,000 invested at 6% compounded monthly for 10 years"}
f["303"] = {"steps":["Enter the property price","Enter your down payment amount or percentage","Enter the annual interest rate","Enter the loan term (typically 15 or 30 years)","Calculate loan amount: price minus down payment","Calculate monthly principal and interest payment","Estimate property taxes, home insurance, and PMI if applicable"],"mistakes":["Looking only at the monthly payment — total interest over 30 years can exceed the loan amount","Forgetting property taxes and insurance — these add 20-40% to the monthly payment","Not checking if PMI is required — typically needed when down payment is below 20%"],"result_context":"For a {precio} property with {enganche} down, your estimated monthly payment is {pago_mensual}.","formula_display":"Monthly P&I = L x r(1+r)^n / ((1+r)^n - 1); Total = P&I + taxes + insurance","example_label":"Monthly mortgage on a 250,000 home with 20% down at 4.5% for 30 years"}
f["304"] = {"steps":["Enter the amount (net or gross)","Enter the applicable VAT rate","To add VAT: net x (1 + rate/100) = gross","To remove VAT: gross / (1 + rate/100) = net","The VAT amount is the difference between net and gross"],"mistakes":["Applying VAT to an already gross amount — effectively taxing the tax","Using the wrong VAT rate — different goods and services have different rates","Forgetting that VAT-registered businesses can reclaim VAT on purchases"],"result_context":"Net: {neto}, VAT ({tasa}%): {iva}, Gross total: {bruto}.","formula_display":"Gross = net x (1 + rate/100); Net = gross / (1 + rate/100)","example_label":"VAT on a 1,200 net invoice at 21%"}
f["306"] = {"steps":["Enter your gross salary or income","Enter total tax and deduction percentages","Calculate total deductions: gross x (total deduction% / 100)","Net salary = gross minus total deductions","Review the breakdown of taxes, social security, and other deductions"],"mistakes":["Not including all mandatory deductions — social security, health insurance, pension","Confusing marginal tax rate with effective tax rate — they are very different","Forgetting that bonuses and overtime may be taxed at different rates"],"result_context":"From a gross salary of {salario_bruto}, your net take-home pay is {salario_neto} after {deducciones} in deductions.","formula_display":"Net = gross x (1 - total deductions% / 100)","example_label":"Net salary from a 3,000 gross monthly salary with 28% total deductions"}
f["307"] = {"steps":["Enter the initial investment amount","Enter the final value (what the investment is worth now)","Calculate gain: final value minus initial investment","ROI% = (gain / initial investment) x 100","Consider the time period — a 20% ROI over 5 years is different from 20% over 1 year"],"mistakes":["Not annualizing the ROI — 20% over 5 years is about 3.7% per year","Forgetting transaction costs and fees in the initial investment","Comparing ROIs across different time periods without adjusting"],"result_context":"Your investment returned {roi}% — a gain of {ganancia} on an initial investment of {inversion}.","formula_display":"ROI% = (final value - initial cost) / initial cost x 100","example_label":"ROI on a 10,000 investment now worth 13,500"}
f["309"] = {"steps":["Enter the total bill amount","Choose a tip percentage (15-20% is standard for good service)","Calculate tip: bill x (tip% / 100)","Calculate total: bill + tip","Optionally split by number of people: total divided by guests"],"mistakes":["Calculating tip on the post-tax amount — tip should be on the pre-tax subtotal","Forgetting to account for large party service charges already included","Rounding down too aggressively — a few cents matters to service staff"],"result_context":"On a bill of {cuenta}, a {propina}% tip comes to {propina_monto}, for a total of {total}.","formula_display":"Tip = bill x tip%; Total = bill + tip; Per person = total / guests","example_label":"Tip on an 85 bill with 18% gratuity, split 3 ways"}
f["315"] = {"steps":["Enter the beginning value of the investment","Enter the ending value","Enter the number of years between start and end","CAGR = (ending / beginning)^(1/years) - 1","Multiply by 100 for percentage","CAGR smooths out volatility to show the average annual growth rate"],"mistakes":["Using CAGR to predict future returns — past performance does not guarantee future results","Comparing CAGR of a 2-year period with a 10-year period — volatility affects short-term CAGR more","Not checking if dividends are included in the ending value"],"result_context":"The CAGR (Compound Annual Growth Rate) over {anos} years is {cagr}%.","formula_display":"CAGR = (ending/beginning)^(1/years) - 1","example_label":"CAGR of an investment growing from 10,000 to 18,000 over 5 years"}
f["311"] = {"steps":["Enter the annual interest rate or expected return","Divide 72 by the interest rate: years to double = 72 / rate","Example: at 8% annual return, 72 / 8 = 9 years to double","The rule works best for rates between 6% and 10%","For more precision, use 69.3 for continuous compounding"],"mistakes":["Applying the rule to interest rates above 15% — it loses accuracy","Forgetting that taxes and fees reduce your effective return","Confusing nominal rate with real rate after inflation"],"result_context":"At a {tasa}% annual return, your money will double in approximately {anos} years.","formula_display":"Years to double = 72 / annual interest rate (%)","example_label":"How long to double money at 7% annual return?"}
f["312"] = {"steps":["Enter the deposit amount","Enter the annual interest rate","Enter the term in months or years","For simple interest: interest = deposit x rate x years","For compound: maturity = deposit x (1 + rate/n)^(n x years)","The maturity value is what you receive at the end of the term"],"mistakes":["Not checking whether interest is simple or compound — the difference can be substantial","Withdrawing before maturity — penalties can wipe out interest earned","Not comparing fixed deposit rates across banks — they vary significantly"],"result_context":"A fixed deposit of {deposito} at {tasa}% for {plazo} will mature at {monto_final}.","formula_display":"Maturity = deposit x (1 + rate x years) for simple; = deposit x (1 + rate/n)^(nt) for compound","example_label":"Maturity value of a 5,000 fixed deposit at 3.5% for 2 years"}
f["326"] = {"steps":["Enter the total debt balance","Enter the annual interest rate (APR)","Enter your monthly payment amount","Calculate months to payoff: complex iterative formula","Total interest paid over the payoff period","Payoff date is today plus the calculated months"],"mistakes":["Making only minimum payments — it takes years longer and costs thousands more in interest","Not accounting for annual fees and late payment charges","Continuing to use the card while trying to pay it off"],"result_context":"With monthly payments of {pago}, you will pay off {deuda} at {tasa}% in {meses} months, paying {interes_total} in interest.","formula_display":"Months = log(payment / (payment - debt x r/12)) / log(1 + r/12)","example_label":"Payoff time for 5,000 credit card debt at 18% APR with 200 monthly payments"}
f["327"] = {"steps":["Enter the credit card balance","Enter the APR (annual percentage rate)","Enter your fixed monthly payment","Calculate: months to payoff using the debt formula","Total interest = (monthly payment x months) minus balance","To pay off faster, increase the monthly payment or transfer to a lower-rate card"],"mistakes":["Paying only the minimum — it can take 10+ years to clear a modest balance","Missing a payment — late fees and penalty APRs make the debt grow faster","Not considering balance transfer fees when moving debt to a 0% card"],"result_context":"Paying {pago} per month on a {saldo} balance at {tasa}% APR will take {meses} months to clear.","formula_display":"Months = -log(1 - balance x r/12 / payment) / log(1 + r/12)","example_label":"Payoff time for 3,000 at 22% APR with 150 monthly payments"}
f["330"] = {"steps":["Enter your gross monthly income","Enter your total monthly debt payments","Enter desired housing payment","Calculate debt-to-income ratio: (debts + housing) / income x 100","Lenders typically want DTI below 36% for conventional loans","Maximum affordable payment = income x max DTI% - existing debts"],"mistakes":["Underestimating property taxes and insurance — they are part of the housing payment","Not including all debts — student loans, car payments, minimum credit card payments all count","Forgetting that lenders use gross income, but YOU pay from net income"],"result_context":"With monthly income of {ingreso}, your maximum affordable loan payment is approximately {pago_maximo}.","formula_display":"Max payment = income x max DTI% - existing monthly debts","example_label":"Affordable home payment for someone earning 5,000/month with 500 in existing debts"}

# ── HEALTH ──
f["400"] = {"steps":["Enter your weight in kilograms","Enter your height in meters","Calculate: BMI = weight / (height x height)","Compare result to categories: under 18.5 = underweight, 18.5-25 = normal, 25-30 = overweight, over 30 = obese","BMI is a screening tool, not a diagnosis"],"mistakes":["Using pounds and inches without converting to metric","Treating BMI as a definitive measure of health — it does not account for muscle mass","Applying adult BMI categories to children — pediatric BMI uses percentile charts"],"result_context":"With a weight of {peso} kg and height of {altura} m, your BMI is {bmi}, which falls in the {categoria} range.","formula_display":"BMI = weight (kg) / height (m)²","example_label":"Calculate BMI for a person weighing 70 kg at 1.75 m tall"}
f["403"] = {"steps":["Enter your body weight in kg","Enter your activity level (sedentary to very active)","Base recommendation: 30-35 ml per kg of body weight","Add extra for exercise: 350-700 ml per hour of moderate activity","Add extra for hot climates: 500-1000 ml additional","Total daily water intake = base + exercise + climate adjustment"],"mistakes":["Drinking too much water too quickly — the kidneys can only process about 800-1000 ml per hour","Counting coffee and soda as water — caffeine is a diuretic","Ignoring water content in food — fruits and vegetables contribute significantly"],"result_context":"Based on your weight of {peso} kg, you should drink approximately {agua_diaria} liters of water per day.","formula_display":"Water (L) = weight (kg) x 0.033 + exercise adjustment","example_label":"Daily water intake for a 70 kg person with moderate activity"}
f["405"] = {"steps":["Enter your weight, height, age, and select gender","The Harris-Benedict formula calculates BMR differently for men and women","Men: BMR = 88.362 + (13.397 x weight) + (4.799 x height) - (5.677 x age)","Women: BMR = 447.593 + (9.247 x weight) + (3.098 x height) - (4.330 x age)","BMR is the calories your body burns at complete rest","TDEE = BMR x activity factor (1.2 to 1.9)"],"mistakes":["Using BMR as your total calorie needs — it is only your resting metabolism","Not updating BMR as weight changes — even 5 kg changes BMR noticeably","Applying the formula to athletes or very muscular people — it underestimates their needs"],"result_context":"Your Basal Metabolic Rate is approximately {bmr} calories per day at complete rest.","formula_display":"BMR (male) = 88.362 + 13.397W + 4.799H - 5.677A; BMR (female) = 447.593 + 9.247W + 3.098H - 4.330A","example_label":"BMR for a 30 year old male, 80 kg, 180 cm"}
f["419"] = {"steps":["Enter your pre-pregnancy weight and height to calculate BMI","Recommended total weight gain depends on pre-pregnancy BMI","Underweight (BMI <18.5): gain 12.5-18 kg","Normal weight (BMI 18.5-25): gain 11.5-16 kg","Overweight (BMI 25-30): gain 7-11.5 kg","Obese (BMI >30): gain 5-9 kg"],"mistakes":["Trying to lose weight during pregnancy — can harm the baby","Comparing weight gain to non-pregnant friends — pregnancy weight gain is mostly baby, placenta, fluids, and blood volume","Not accounting for carrying twins or multiples — weight gain recommendations are higher"],"result_context":"Based on your pre-pregnancy BMI of {imc}, the recommended total weight gain is {ganancia_min} to {ganancia_max} kg.","formula_display":"Gain range based on pre-pregnancy BMI category","example_label":"Recommended weight gain for someone starting at BMI 22"}
f["422"] = {"steps":["Enter your age in years","The simplest formula: max heart rate = 220 minus age","Alternative Tanaka formula: MHR = 208 - (0.7 x age) for better accuracy","Your training zones are percentages of your MHR","Fat burn zone: 60-70% of MHR; Cardio: 70-80%; Peak: 80-95%"],"mistakes":["Using 220 minus age for everyone — it can be off by 10-15 beats for many people","Training at maximum heart rate — it is called maximum for a reason, do not sustain it","Forgetting that certain medications (beta blockers) lower maximum heart rate"],"result_context":"Your estimated maximum heart rate is {fcm} bpm. Your fat-burning zone is {zona_quema} bpm.","formula_display":"MHR = 220 - age (standard) or MHR = 208 - 0.7 x age (Tanaka)","example_label":"Max heart rate and training zones for a 35 year old"}
f["423"] = {"steps":["Enter your maximum heart rate or calculate it from age","Zone 1 (Recovery): 50-60% of MHR — very light activity","Zone 2 (Fat burn): 60-70% — best for endurance and fat metabolism","Zone 3 (Cardio): 70-80% — improves aerobic capacity","Zone 4 (Threshold): 80-90% — improves lactate threshold","Zone 5 (Maximum): 90-100% — sprint and peak performance"],"mistakes":["Spending all training time in zone 3 — zone 2 builds the aerobic base needed for progress","Not using a heart rate monitor — perceived effort is often inaccurate","Training at high intensity every day — the body needs recovery in zones 1 and 2"],"result_context":"Your five training zones range from {z1} to {z5} bpm based on your maximum heart rate of {fcm}.","formula_display":"Zone N = MHR x (lower% to upper%)","example_label":"Heart rate training zones for someone with MHR of 185 bpm"}
f["424"] = {"steps":["Measure your true resting heart rate first thing in the morning","Enter your resting heart rate and maximum heart rate","Heart rate reserve (HRR) = MHR minus resting HR","Karvonen target = (HRR x intensity%) + resting HR","This formula accounts for your fitness level, unlike simple % of MHR"],"mistakes":["Using an estimated resting heart rate — measure it for accuracy","Applying the same zones as simple MHR percentages — Karvonen zones are different","Not re-measuring resting HR as fitness improves — it drops with better conditioning"],"result_context":"Using the Karvonen method with resting HR of {fc_reposo}, your target heart rate at {intensidad}% is {fc_objetivo} bpm.","formula_display":"Target HR = ((MHR - resting HR) x intensity%) + resting HR","example_label":"Karvonen target at 70% intensity with resting HR 60 and MHR 185"}
f["429"] = {"steps":["Enter your body weight","Select the exercise type from the list","Enter the duration in minutes","Calories burned = MET value x weight (kg) x duration (hours)","MET values: walking 3.5, jogging 7, cycling 8, swimming 6, weight training 5","The heavier you are, the more calories you burn for the same exercise"],"mistakes":["Overestimating intensity — casual cycling is not the same as vigorous cycling","Not accounting for rest periods during exercise","Using exercise calories as an excuse to overeat — weight loss comes from diet, not exercise"],"result_context":"{duracion} minutes of {actividad} burns approximately {calorias} calories for someone weighing {peso} kg.","formula_display":"Calories = MET x weight (kg) x hours","example_label":"Calories burned in 30 minutes of jogging at 70 kg"}
f["439"] = {"steps":["Enter your systolic (top) reading and diastolic (bottom) reading","Normal: systolic <120 AND diastolic <80 mmHg","Elevated: systolic 120-129 AND diastolic <80","Stage 1 hypertension: systolic 130-139 OR diastolic 80-89","Stage 2 hypertension: systolic >=140 OR diastolic >=90","Hypertensive crisis: systolic >180 OR diastolic >120 — seek medical help"],"mistakes":["Taking a single reading and panicking — blood pressure varies throughout the day","Using a cuff that is the wrong size — too small overestimates, too large underestimates","Measuring right after exercise, coffee, or stress — rest for 5 minutes first"],"result_context":"A reading of {sistolica}/{diastolica} mmHg is classified as {categoria}. Your mean arterial pressure is {map} mmHg.","formula_display":"MAP = diastolic + (systolic - diastolic) / 3","example_label":"Classify a blood pressure reading of 135/85 mmHg"}
f["443"] = {"steps":["Sleep cycles last approximately 90 minutes each","Waking up mid-cycle leaves you groggy","To wake at 7:00 AM, go to bed at 9:45 PM (6 cycles), 11:15 PM (5 cycles), or 12:45 AM (4 cycles)","The average person needs 5-6 full sleep cycles (7.5-9 hours)","Sleep onset takes about 15 minutes — add this to your bedtime calculation"],"mistakes":["Hitting snooze repeatedly — you start a new sleep cycle you will not finish","Using screens right before bed — blue light suppresses melatonin for 1-2 hours","Drinking alcohol before bed — it fragments sleep cycles even if you fall asleep faster"],"result_context":"For {ciclos} complete sleep cycles, plan to sleep for {horas} hours. Suggested bedtimes: {horarios}.","formula_display":"Sleep time = number of cycles x 90 minutes; Wake time = bedtime + sleep time + 15 min onset","example_label":"Best bedtime to wake up at 6:30 AM feeling refreshed"}

# ── SCIENCE ──
f["503"] = {"steps":["Enter the mass in kilograms","Enter the acceleration in m/s²","Apply Newton's Second Law: F = m x a","The result is in Newtons (N)","1 N is the force needed to accelerate 1 kg at 1 m/s²","Multiple forces add as vectors, not simple numbers"],"mistakes":["Using weight (in kg-force) instead of mass (in kg) — they are different concepts","Confusing Newtons with kilograms — weight is mass x gravity, force is mass x acceleration","Adding forces without considering direction — forces are vector quantities"],"result_context":"A mass of {masa} kg accelerating at {aceleracion} m/s² experiences a force of {fuerza} N.","formula_display":"F = m x a (Newton's Second Law)","example_label":"Force needed to accelerate a 1,200 kg car at 3 m/s²"}
f["504"] = {"steps":["Enter the mass of the object in kg","Enter the velocity in m/s","Kinetic energy = 0.5 x mass x velocity²","The result is in Joules (J)","Kinetic energy increases with the square of velocity — doubling speed quadruples energy","This is why high-speed collisions are so much more destructive"],"mistakes":["Using km/h instead of m/s — divide km/h by 3.6 to convert","Forgetting to square the velocity before multiplying","Confusing kinetic energy with momentum — they scale differently with velocity"],"result_context":"An object with mass {masa} kg moving at {velocidad} m/s has a kinetic energy of {energia} J.","formula_display":"KE = ½mv²","example_label":"Kinetic energy of a 1,500 kg car traveling at 20 m/s (72 km/h)"}
f["514"] = {"steps":["Enter the initial velocity in m/s","Enter the launch angle in degrees (from horizontal)","Maximum height = (v² x sin²(angle)) / (2 x g)","Range = (v² x sin(2 x angle)) / g","Flight time = (2 x v x sin(angle)) / g","g = 9.81 m/s² (standard gravity)","Optimal angle for maximum range is 45 degrees"],"mistakes":["Using degrees instead of radians in the sine function","Forgetting air resistance — real projectiles travel shorter than calculated","Assuming flat ground — launching from or to different elevations changes the trajectory"],"result_context":"A projectile launched at {vi} m/s at {angulo} degrees reaches {altura_max} m high and lands {alcance} m away after {tiempo_vuelo} seconds.","formula_display":"Range = v²sin(2θ)/g; Height = v²sin²(θ)/(2g); Time = 2vsin(θ)/g","example_label":"Trajectory of a ball thrown at 25 m/s at a 40 degree angle"}

# ── COTIDIANO ──
f["601"] = {"steps":["Enter the start date (day, month, year)","Enter the end date (day, month, year)","The calculator counts the total days between the two dates","Use this for project duration, age calculation, countdown to events","Result can be shown in days, weeks, or months","Accounting for leap years is automatic"],"mistakes":["Counting the start date as day 1 when it should be day 0","Forgetting that months have different numbers of days","Not accounting for time zones when calculating across international date lines"],"result_context":"There are {dias} days between {fecha_inicio} and {fecha_fin}.","formula_display":"Days = end date - start date","example_label":"Days between January 15 and March 10 of the same year"}
f["604"] = {"steps":["Enter the start date and end date","The calculator identifies all weekdays (Mon-Fri)","Subtracts weekends automatically","Optionally add holiday dates to exclude","Result is the number of business/working days","Use for project planning, payroll, and delivery estimates"],"mistakes":["Not checking for regional public holidays — they vary by country and region","Assuming all weekdays are working days — some countries have different work weeks","Forgetting that some businesses close between Christmas and New Year"],"result_context":"There are {dias_habiles} working days between {fecha_inicio} and {fecha_fin}, excluding weekends.","formula_display":"Working days = total days - weekend days - holidays","example_label":"Working days in January 2026"}
f["610"] = {"steps":["Enter the password to test","Password strength depends on length and character variety","Entropy in bits = length x log2(possible characters)","Lowercase only = 26 chars, +uppercase = 52, +digits = 62, +symbols = 95","Under 40 bits = weak, 40-60 = moderate, 60-80 = strong, 80+ = very strong","Crack time estimate based on 10 billion guesses per second"],"mistakes":["Using dictionary words — attackers try these first with variations","Thinking adding '1!' at the end makes a password strong — pattern-based attacks check these","Reusing passwords across sites — one breach exposes all accounts"],"result_context":"Your password has approximately {entropia} bits of entropy. Estimated crack time: {tiempo_crack}.","formula_display":"Entropy = length x log2(charset size); Crack time = 2^(entropy-1) / guesses per second","example_label":"Test password strength of 'Tr0ub4dor&3'"}
f["611"] = {"steps":["Select the desired password length (12-16 recommended)","Choose character types: lowercase, uppercase, digits, symbols","The generator creates a random password from the selected set","Each character is independently random — no patterns or words","Copy the password to a password manager immediately"],"mistakes":["Writing passwords on paper or in unencrypted files","Generating a password and then memorizing it — use a password manager instead","Choosing too short — 8 characters can be cracked in minutes, 16 takes years"],"result_context":"Your randomly generated password is {contrasena}. Store it securely in a password manager.","formula_display":"Random selection from charset of size N for L positions = N^L combinations","example_label":"Generate a 16-character password with all character types"}
f["614"] = {"steps":["Enter the file size and select the current unit (bytes, KB, MB, etc.)","The calculator converts between all digital storage units","1 KB = 1024 bytes, 1 MB = 1024 KB, 1 GB = 1024 MB, 1 TB = 1024 GB","Note: hard drive manufacturers often use 1000 instead of 1024","Result shows the file size in all common units"],"mistakes":["Confusing MB (megabytes) with Mb (megabits) — 1 MB = 8 Mb","Using 1000-based conversion when your OS uses 1024-based","Not accounting for file system overhead — files take slightly more space on disk"],"result_context":"{tamano} converts to {resultado}.","formula_display":"Divide by 1024 for each step up: B -> KB -> MB -> GB -> TB","example_label":"Convert 500 MB to GB, KB, and bytes"}
f["628"] = {"steps":["Enter the distance traveled in km or miles","Enter the amount of fuel used in liters or gallons","Calculate: consumption = fuel used / distance x 100 (L/100km)","Alternative: fuel economy = distance / fuel used (MPG or km/L)","Lower L/100km means better efficiency","Typical car: 6-8 L/100km; SUV: 9-12 L/100km"],"mistakes":["Calculating from a single trip — fill the tank, record distance, fill again for accuracy","Comparing L/100km with MPG without converting — they are inversely related","Not accounting for different driving conditions — city vs highway consumption differs significantly"],"result_context":"Your vehicle consumes {consumo} L per 100 km, which equals {rendimiento} km per liter.","formula_display":"Consumption (L/100km) = fuel used / distance x 100","example_label":"Fuel consumption over 450 km using 36 liters"}

# ── ELECTRONICS ──
f["900"] = {"steps":["Ohm's Law: V = I x R (voltage = current x resistance)","Enter any two known values to find the third","To find voltage: V = I x R","To find current: I = V / R","To find resistance: R = V / I","Units: volts (V), amps (A), ohms (Ω)"],"mistakes":["Using the wrong units — milliamps must be converted to amps first","Applying Ohm's law to non-linear components like diodes and transistors","Forgetting that real wires have resistance too — especially in long runs"],"result_context":"With {voltaje} V and {corriente} A, the resistance is {resistencia} Ω.","formula_display":"V = I x R; I = V / R; R = V / I","example_label":"Find the current through a 220 Ω resistor with 5 V applied"}
f["902"] = {"steps":["Enter the supply voltage (from your power source)","Enter the forward voltage of the LED (typically 2 V for red, 3.2 V for blue/white)","Enter the desired LED current (typically 20 mA = 0.02 A)","Calculate: resistor = (supply V - LED V) / current","Round up to the nearest standard resistor value","Higher resistance = dimmer LED; lower resistance = brighter but may burn out"],"mistakes":["Connecting the LED without a current-limiting resistor — it will burn out instantly","Using the supply voltage alone in the calculation — subtract the LED forward voltage","Forgetting that different LED colors have different forward voltages"],"result_context":"For a {voltaje_fuente} V supply with a {voltaje_led} V LED at {corriente} mA, use a {resistencia} Ω resistor.","formula_display":"R = (Vsupply - Vled) / Iled","example_label":"Resistor for a red LED (2V, 20mA) on a 9V battery"}
f["903"] = {"steps":["Identify the colored bands on the resistor (4, 5, or 6 bands)","First band = first digit, second band = second digit","Third band = multiplier (number of zeros)","Fourth band = tolerance (gold = 5%, silver = 10%, none = 20%)","5-band resistors have three significant digits","6-band adds a temperature coefficient"],"mistakes":["Reading the bands in the wrong direction — the tolerance band has a wider gap","Confusing brown (1) with red (2) or orange (3) in poor lighting","Assuming a 4-band resistor when it is actually 5-band"],"result_context":"The resistor color code decodes to {resistencia} Ω with {tolerancia}% tolerance.","formula_display":"Value = (digit1 digit2) x 10^multiplier Ω","example_label":"Decode a 4-band resistor: brown, black, red, gold"}
f["906"] = {"steps":["Enter the input voltage (Vin)","Enter the values of R1 (top resistor) and R2 (bottom resistor)","Output voltage: Vout = Vin x R2 / (R1 + R2)","The divider splits voltage in proportion to the resistor values","If R1 = R2, Vout = Vin / 2","Used for level shifting, reference voltages, and sensor circuits"],"mistakes":["Not accounting for the load connected to Vout — it changes the effective R2","Using very high resistor values — noise becomes significant above 1 MΩ","Using very low values — wastes power through the divider"],"result_context":"With {vin} V input and R1={r1}Ω, R2={r2}Ω, the output voltage is {vout} V.","formula_display":"Vout = Vin x R2 / (R1 + R2)","example_label":"Output of a divider with 12V in, R1=10kΩ, R2=5kΩ"}

# ── CONVERSION ──
f["1000"] = {"steps":["Enter the value to convert","Select the source unit (meters, feet, inches, miles, etc.)","Select the target unit","The calculator converts using standard conversion factors","Results are shown with appropriate decimal precision"],"mistakes":["Confusing miles with nautical miles — they are different","Using the wrong conversion factor — 1 inch = 2.54 cm exactly","Forgetting that some conversions are approximate (e.g., survey foot vs international foot)"],"result_context":"{valor} {unidad_origen} equals {resultado} {unidad_destino}.","formula_display":"Target value = source value x conversion factor","example_label":"Convert 5.5 feet to meters"}
f["1004"] = {"steps":["Enter the temperature value","Select the source scale (Celsius, Fahrenheit, Kelvin)","Select the target scale","Celsius to Fahrenheit: °F = °C x 9/5 + 32","Fahrenheit to Celsius: °C = (°F - 32) x 5/9","Celsius to Kelvin: K = °C + 273.15"],"mistakes":["Using the wrong formula direction — adding 32 when going from Fahrenheit to Celsius","Forgetting that Kelvin does not use the degree symbol — it is just 'K', not '°K'","Rounding intermediate results — keep full precision until the final answer"],"result_context":"{valor}°{origen} equals {resultado}°{destino}.","formula_display":"°F = °C x 9/5 + 32; °C = (°F - 32) x 5/9; K = °C + 273.15","example_label":"Convert 25°C to Fahrenheit"}

# ── STATISTICS ──
f["110_"+"\"0"] = f.get("1100",{})  # skip
f["1100"] = {"steps":["Enter a set of numbers separated by commas","The mean is the sum of all values divided by the count","Add all numbers together, then divide by how many there are","The mean is the most common measure of central tendency","It is sensitive to outliers — one extreme value can shift the mean","Use median for skewed distributions"],"mistakes":["Using the mean when the data has extreme outliers — the median is more appropriate","Calculating the mean of categorical data — it requires numerical values","Forgetting that the mean of rates or ratios needs special handling (harmonic mean)"],"result_context":"The mean of your {n} values is {media}.","formula_display":"Mean = (sum of all values) / (number of values)","example_label":"Find the mean of: 12, 15, 18, 22, 25, 30"}
f["1101"] = {"steps":["Sort the numbers from smallest to largest","If the count is odd, the median is the middle value","If the count is even, the median is the average of the two middle values","The median splits the data into two equal halves","It is resistant to outliers — extreme values do not affect it"],"mistakes":["Forgetting to sort the numbers first — without sorting, the 'middle' is meaningless","Confusing median with mode — median is the middle value, mode is the most frequent","Using median when you need to know the actual middle income, not the average income"],"result_context":"The median of your {n} values is {mediana}. Half the values are below this, half above.","formula_display":"Median = middle value(s) of sorted data","example_label":"Find the median of: 8, 3, 12, 6, 9, 15, 7"}
f["1102"] = {"steps":["Enter your dataset as comma-separated numbers","Calculate the mean first","For each value: subtract the mean, square the result","Sum all the squared differences","For population std dev: divide by N, then take square root","For sample std dev: divide by (N-1), then take square root"],"mistakes":["Using population formula when you have a sample — dividing by N instead of N-1","Reporting standard deviation without the mean — they belong together","Confusing standard deviation with standard error — SE = SD / sqrt(n)"],"result_context":"The standard deviation is {desviacion}. About 68% of values fall within {rango}.","formula_display":"σ = sqrt(Σ(x-μ)²/N) population; s = sqrt(Σ(x-x̄)²/(n-1)) sample","example_label":"Standard deviation of: 10, 12, 23, 23, 16, 23, 21, 16"}
f["1105"] = {"steps":["Enter the individual value (X)","Enter the population mean (μ)","Enter the population standard deviation (σ)","Z-score = (X - μ) / σ","Positive z-score: value is above the mean","Negative z-score: value is below the mean","The magnitude tells you how many standard deviations away from average"],"mistakes":["Using sample standard deviation instead of population standard deviation","Forgetting that z-scores assume a normal distribution","Comparing z-scores from different distributions"],"result_context":"A score of {valor} is {z} standard deviations {direccion} the mean of {media}.","formula_display":"z = (X - μ) / σ","example_label":"Z-score for a test result of 85 with class average 72 and std dev 8"}

def apply():
    updated = 0
    for fp in sorted(glob.glob(os.path.join(CALC, "*.json"))):
        if "bak" in fp or "monolithic" in fp or os.path.basename(fp) == "calculators.json": continue
        with open(fp, "r", encoding="utf-8-sig") as fh: calc = json.load(fh)
        cid = calc.get("id", "")
        if cid not in f: continue
        en = calc.setdefault("i18n", {}).setdefault("en", {})
        changed = False
        for k, v in f[cid].items():
            if not v: continue
            en[k] = v
            changed = True
        if changed:
            with open(fp, "w", encoding="utf-8", newline="\n") as fh:
                json.dump(calc, fh, ensure_ascii=False, indent=2)
            updated += 1
    print(f"Updated {updated}")

apply()
