#!/usr/bin/env python3
"""Fix remaining German input labels with proper translations."""

import json, os, glob, re

CALC_DIR = r"C:\Microsaas\obra\src\calculators"

DE_TRANSLATIONS = {
    "anio": "Jahr",
    "anio1": "Jahr 1", "anio2": "Jahr 2",
    "mes": "Monat", "mes1": "Monat 1", "mes2": "Monat 2",
    "dia": "Tag", "dia1": "Tag 1", "dia2": "Tag 2",
    "decimales": "Dezimalstellen",
    "porcentaje": "Prozentsatz",
    "proporcion": "Verhältnis",
    "objetivo": "Ziel", "Objetivo": "Ziel",
    "valor": "Wert",
    "distancia": "Entfernung", "Distancia": "Entfernung",
    "pendiente": "Steigung",
    "Slope": "Steigung",
    "constante": "Konstante",
    "gravedad": "Schwerkraft",
    "gravedad_m2": "Schwerkraft (m/s²)",
    "temperatura": "Temperatur",
    "velocidad": "Geschwindigkeit",
    "velocidad_inicial": "Anfangsgeschwindigkeit",
    "precio_original": "Originalpreis",
    "precio_descuento": "Rabattpreis",
    "confianza": "Konfidenz",
    "Significancia": "Signifikanz",
    "duracion": "Dauer",
    "frecuencia": "Frequenz",
    "habitaciones": "Zimmer",
    "personas": "Personen",
    "profundidad": "Tiefe",
    "Profundidad": "Tiefe",
    "superficie": "Fläche",
    "Potencia": "Leistung",
    "potencia": "Leistung",
    "Carga": "Ladung",
    "Voltaje": "Spannung",
    "voltaje": "Spannung",
    "Resistencia": "Widerstand",
    "resistencia": "Widerstand",
    "Inductancia": "Induktivität",
    "inductancia": "Induktivität",
    "Capacitancia": "Kapazität",
    "capacitancia": "Kapazität",
    "Corriente": "Strom",
    "corriente": "Strom",
    "Impedancia": "Impedanz",
    "Frecuencia": "Frequenz",
    "Energia": "Energie",
    "energia": "Energie",
    "Fuerza": "Kraft",
    "fuerza": "Kraft",
    "Presion": "Druck",
    "presion": "Druck",
    "Densidad": "Dichte",
    "densidad": "Dichte",
    "Masa": "Masse",
    "masa": "Masse",
    "Peso": "Gewicht",
    "peso": "Gewicht",
    "Longitud": "Länge",
    "longitud": "Länge",
    "Anchura": "Breite",
    "Altura": "Höhe",
    "altura": "Höhe",
    "Temperatura": "Temperatur",
    "temperatura_f": "Temperatur (°F)",
    "Temperatura F": "Temperatur (°F)",
    "Volumen": "Volumen",
    "volumen": "Volumen",
    "volumen_gas": "Gasvolumen",
    "Volumen Gas": "Gasvolumen",
    "volumen_inicial": "Anfangsvolumen",
    "Volumen Inicial": "Anfangsvolumen",
    "volumen_final": "Endvolumen",
    "Volumen Final": "Endvolumen",
    "Volumen (m³)": "Volumen (m³)",
    "Radio": "Radius",
    "radio": "Radius",
    "Diametro": "Durchmesser",
    "Diametro Cilindro": "Zylinderdurchmesser",
    "Perimetro": "Umfang",
    "Area": "Fläche",
    "area": "Fläche",
    "Caudal": "Durchfluss",
    "caudal": "Durchfluss",
    "Tiempo": "Zeit",
    "tiempo": "Zeit",
    "tiempo_min": "Zeit (min)",
    "tiempo_ejercicio": "Trainingsdauer",
    "Tiempo Ejercicio": "Trainingsdauer",
    "Tiempo Min": "Zeit (min)",
    "duracion_min": "Dauer (min)",
    "Duracion Min": "Dauer (min)",
    "Velocidad": "Geschwindigkeit",
    "Velocidad Angular": "Winkelgeschwindigkeit",
    "Velocidad Avion": "Fluggeschwindigkeit",
    "Velocidad Fuente": "Quellengeschwindigkeit",
    "Velocidad Ms": "Geschwindigkeit (m/s)",
    "Velocidad Sonido": "Schallgeschwindigkeit",
    "Aceleracion": "Beschleunigung",
    "aceleracion": "Beschleunigung",
    "Tasa": "Rate",
    "tasa": "Rate",
    "tasa_impuesto": "Steuersatz",
    "Tasa Impuesto": "Steuersatz",
    "Interes": "Zinsen",
    "interes": "Zinsen",
    "Inflacion": "Inflation",
    "Tipo Cambio": "Wechselkurs",
    "Comision": "Provision",
    "Descuento": "Rabatt",
    "Margen": "Marge",
    "Beneficio": "Gewinn",
    "Coste": "Kosten",
    "coste": "Kosten",
    "Costes Fijos": "Fixkosten",
    "Costo": "Kosten",
    "Coste Variable": "Variable Kosten",
    "Ingreso": "Einnahmen",
    "Gasto": "Ausgaben",
    "Saldo": "Saldo",
    "Monto": "Betrag",
    "deuda_total": "Gesamtschulden",
    "inversion": "Investition",
    "inversion_inicial": "Anfangsinvestition",
    "Inversion Inicial": "Anfangsinvestition",
    "ahorro_mensual": "Monatliche Ersparnis",
    "ahorro_meses": "Sparmonate",
    "flujo_anual": "Jährlicher Cashflow",
    "Flujo Anual": "Jährlicher Cashflow",
    "rendimiento": "Rendite",
    "Rendimiento": "Rendite",
    "dividendo_anual": "Jährliche Dividende",
    "Dividendo Anual": "Jährliche Dividende",
    "Precio Accion": "Aktienkurs",
    "Precio Compra": "Kaufpreis",
    "precio_compra": "Kaufpreis",
    "Presupuesto": "Budget",
    "Impuesto": "Steuer",
    "impuesto": "Steuer",
    "salario": "Gehalt",
    "Salario": "Gehalt",
    "Prestamo": "Darlehen",
    "prestamo": "Darlehen",
    "Hipoteca": "Hypothek",
    "Alquiler": "Miete",
    "Seguro": "Versicherung",
    "Pago": "Zahlung",
    "pago": "Zahlung",
    "Cuota": "Rate",
    "Subsidio": "Zuschuss",
    "Deposito": "Einlage",
    "deposito": "Einlage",
    "Retiro": "Auszahlung",
    "Capital": "Kapital",
    "capital": "Kapital",
    "Amortizacion": "Tilgung",
    "Garantia": "Garantie",
    "Liquidez": "Liquidität",
    "Solvencia": "Solvenz",
    "Rentabilidad": "Rentabilität",
    "Patrimonio": "Vermögen",
    "Pasivo": "Verbindlichkeiten",
    "Activo": "Aktiva",
    "Cantidad": "Menge",
    "cantidad": "Menge",
    "Numero": "Anzahl",
    "Unidades": "Einheiten",
    "unidades": "Einheiten",
    "factor": "Faktor",
    "Factor": "Faktor",
    "indice": "Index",
    "Indice": "Index",
    "coeficiente": "Koeffizient",
    "Coeficiente": "Koeffizient",
    "modulo": "Modul",
    "Modulo": "Modul",
    "Modulo Elastico": "Elastizitätsmodul",
    "Momento Inercia": "Trägheitsmoment",
    "Carga Extra": "Zusatzlast",
    "Carga Precarga": "Vorspannung",
    "factor_seguridad": "Sicherheitsfaktor",
    "Presion Base": "Basisdruck",
    "Punto Rocio": "Taupunkt",
    "Concentracion": "Konzentration",
    "Concentracion Inicial": "Anfangskonzentration",
    "Concentracion Final": "Endkonzentration",
    "Concentracion H": "H⁺-Konzentration",
    "Masa Solvente": "Lösungsmittelmasse",
    "Masa Soluto": "Lösungsstoffmasse",
    "Disolucion": "Lösung",
    "Dilucion": "Verdünnung",
    "Ph": "pH-Wert",
    "Acido": "Säure",
    "Base": "Base",
    "base": "Base",
    "Neutro": "Neutral",
    "Reaccion": "Reaktion",
    "Catalizador": "Katalysator",
    "Electrolito": "Elektrolyt",
    "Oxidacion": "Oxidation",
    "Reduccion": "Reduktion",
    "kcal": "kcal",
    "Calorias": "Kalorien",
    "calorias": "Kalorien",
    "Grasa": "Fett",
    "grasa": "Fett",
    "Proteina": "Protein",
    "proteina": "Protein",
    "Carbohidrato": "Kohlenhydrate",
    "Fibra": "Ballaststoffe",
    "Agua": "Wasser",
    "agua": "Wasser",
    "Sodio": "Natrium",
    "Potasio": "Kalium",
    "Calcio": "Kalzium",
    "Hierro": "Eisen",
    "Vitamina": "Vitamin",
    "Sueno": "Schlaf",
    "Ejercicio": "Training",
    "ejercicio_hrs": "Training (Std)",
    "Actividad": "Aktivität",
    "actividad": "Aktivität",
    "Consumo": "Verbrauch",
    "consumo": "Verbrauch",
    "Emision": "Emission",
    "Contaminacion": "Verschmutzung",
    "Piscina": "Pool",
    "Jardin": "Garten",
    "Tierra": "Erde",
    "Planta": "Pflanze",
    "Riego": "Bewässerung",
    "Cosecha": "Ernte",
    "Siembra": "Aussaat",
    "Abono": "Dünger",
    "Fertilizante": "Düngemittel",
    "Pesticida": "Pestizid",
    "Herbicida": "Herbizid",
    "Bitrate": "Bitrate",
    "Duracion": "Dauer",
    "Resolucion": "Auflösung",
    "Compresion": "Komprimierung",
    "Latencia": "Latenz",
    "Ancho Banda": "Bandbreite",
    "Datos": "Daten",
    "Archivo": "Datei",
    "Tamano": "Größe",
    "Tamaño Muestra": "Stichprobengröße",
    "tamano_muestra": "Stichprobengröße",
    "Muestra": "Stichprobe",
    "Media": "Mittelwert",
    "Mediana": "Median",
    "Moda": "Modus",
    "Varianza": "Varianz",
    "Desviacion": "Abweichung",
    "Desviacion Estandar": "Standardabweichung",
    "Error": "Fehler",
    "Intervalo": "Intervall",
    "Probabilidad": "Wahrscheinlichkeit",
    "probabilidad": "Wahrscheinlichkeit",
    "Aleatorio": "Zufällig",
    "Distribucion": "Verteilung",
    "Normal": "Normal",
    "Uniforme": "Gleichförmig",
    "Exponencial": "Exponentiell",
    "glucosa": "Glukose",
    "glucosa_mgdl": "Glukose (mg/dL)",
    "hdl": "HDL",
    "ldl": "LDL",
    "colesterol": "Cholesterin",
    "colesterol_total": "Gesamtcholesterin",
    "trigliceridos": "Triglyceride",
    "presion_arterial": "Blutdruck",
    "presion_sistolica": "Systolischer Druck",
    "presion_diastolica": "Diastolischer Druck",
    "frecuencia_cardiaca": "Herzfrequenz",
    "frecuencia_respiratoria": "Atemfrequenz",
    "saturacion_oxigeno": "Sauerstoffsättigung",
    "fc_reposo": "Ruhepuls",
    "peso_actual": "Aktuelles Gewicht",
    "cintura_cm": "Taille (cm)",
    "cadera_cm": "Hüfte (cm)",
    "cuello": "Hals",
    "Cuello": "Hals",
    "altura_cm": "Körpergröße (cm)",
    "edad": "Alter",
    "Edad": "Alter",
    "sexo": "Geschlecht",
    "Sexo": "Geschlecht",
    "Genero": "Geschlecht",
    "Hombre": "Mann",
    "Mujer": "Frau",
    "metros_cuadrados": "Quadratmeter",
    "m2": "m²",
    "metros_cubicos": "Kubikmeter",
    "m3": "m³",
    "litros": "Liter",
    "Litros": "Liter",
    "ml": "ml",
    "kg": "kg",
    "g": "g",
    "mg": "mg",
    "km": "km",
    "Km": "km",
    "metros": "Meter",
    "cm": "cm",
    "mm": "mm",
    "pulgadas": "Zoll",
    "pies": "Fuß",
    "yardas": "Yard",
    "millas": "Meilen",
    "dias_totales": "Gesamttage",
    "Dias Totales": "Gesamttage",
    "Dias": "Tage",
    "Semanas": "Wochen",
    "Meses": "Monate",
    "Años": "Jahre",
    "Horas": "Stunden",
    "Minutos": "Minuten",
    "Segundos": "Sekunden",
    "festivos": "Feiertage",
    "Festivos": "Feiertage",
    "fines_semana": "Wochenenden",
    "laborables": "Werktage",
    "festivos_nacionales": "Nationale Feiertage",
    "festivos_locales": "Lokale Feiertage",
    "Banda1": "Band 1",
    "Banda2": "Band 2",
    "Banda3": "Band 3",
    "Numero Cilindros": "Zylinderzahl",
    "lado_b": "Seite B",
    "lado_c": "Seite C",
    "rating": "Bewertung",
    "Rating": "Bewertung",
    "score": "Punktzahl",
    "Score": "Punktzahl",
    "IAS": "IAS",
    "ISO": "ISO",
    "Met": "MET",
    "METs": "METs",
    "Ph": "pH",
    "PM2.5": "PM2,5",
    "R": "R", "r": "r", "n": "n", "a": "a", "b": "b",
    "r1": "R₁", "r2": "R₂", "r3": "R₃",
    "c1": "C₁", "c2": "C₂",
    "a1": "A₁",
    "D": "D",
    "V": "V",
    "x1": "x₁",
    "V LED": "V LED",
    "I LED": "I LED",
    "R1": "R₁",
    "R2": "R₂",
    "R3": "R₃",
    "C1": "C₁",
    "C2": "C₂",
}


def main():
    files = sorted(
        f for f in glob.glob(os.path.join(CALC_DIR, "*.json"))
        if os.path.basename(f) not in ("calculators.json",)
        and "bak" not in f and "monolithic" not in f
    )

    updated = 0
    fixed = 0

    for fp in files:
        with open(fp, "r", encoding="utf-8-sig") as f:
            calc = json.load(f)

        de = calc.get("i18n", {}).get("de", {})
        de_inputs = de.get("inputs", {})
        es_inputs = calc.get("i18n", {}).get("es", {}).get("inputs", {})

        changed = False
        for inp_id, label in list(de_inputs.items()):
            if not isinstance(label, str) or not label:
                continue
            # Only fix if it still matches Spanish
            es_label = es_inputs.get(inp_id, "")
            if label != es_label:
                continue

            # Try exact match first, then case-insensitive
            if label in DE_TRANSLATIONS:
                de_inputs[inp_id] = DE_TRANSLATIONS[label]
                changed = True
                fixed += 1
            elif label.upper() in {k.upper(): k for k in DE_TRANSLATIONS}:
                for tk, tv in DE_TRANSLATIONS.items():
                    if tk.upper() == label.upper():
                        de_inputs[inp_id] = tv
                        changed = True
                        fixed += 1
                        break

        if changed:
            with open(fp, "w", encoding="utf-8", newline="\n") as f:
                json.dump(calc, f, ensure_ascii=False, indent=2)
            updated += 1

    print(f"Fixed {fixed} German labels in {updated}/{len(files)} files")


if __name__ == "__main__":
    main()
