"""
Patch seo_title + seo_desc for calcs 1000-1049 in all 6 i18n JSON files.
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
I18N = ROOT / "src" / "i18n"

# ── SEO data per calc  {cid: {lang: (title, desc)}}  ─────────────────────────
# Title pattern: "{name} – {tagline} | CalcToWork"
# Desc pattern:  specific formula + example usage, 140-160 chars

SEO = {
    "1000": {
        "es": ("Calculadora de pH – Fórmula y Ejemplos | CalcToWork",
               "Calcula el pH a partir de la concentración de iones H⁺. Fórmula: pH = −log₁₀[H⁺]. Ejemplo: [H⁺]=0.001 mol/L → pH=3. Gratis e instantáneo."),
        "en": ("pH Calculator – Formula & Examples | CalcToWork",
               "Calculate pH from hydrogen ion concentration. Formula: pH = −log₁₀[H⁺]. Example: [H⁺]=0.001 mol/L → pH=3. Free and instant."),
        "fr": ("Calculateur de pH – Formule et Exemples | CalcToWork",
               "Calculez le pH à partir de la concentration en ions H⁺. Formule: pH = −log₁₀[H⁺]. Exemple: [H⁺]=0.001 mol/L → pH=3. Gratuit et instantané."),
        "pt": ("Calculadora de pH – Fórmula e Exemplos | CalcToWork",
               "Calcule o pH a partir da concentração de iões H⁺. Fórmula: pH = −log₁₀[H⁺]. Exemplo: [H⁺]=0.001 mol/L → pH=3. Grátis e instantâneo."),
        "de": ("pH-Rechner – Formel und Beispiele | CalcToWork",
               "Berechne den pH-Wert aus der H⁺-Konzentration. Formel: pH = −log₁₀[H⁺]. Beispiel: [H⁺]=0.001 mol/L → pH=3. Kostenlos und sofort."),
        "it": ("Calcolatore di pH – Formula ed Esempi | CalcToWork",
               "Calcola il pH dalla concentrazione di ioni H⁺. Formula: pH = −log₁₀[H⁺]. Esempio: [H⁺]=0.001 mol/L → pH=3. Gratuito e immediato."),
    },
    "1001": {
        "es": ("Calculadora de pOH – Fórmula y Conversión pH | CalcToWork",
               "Calcula pOH y pH a partir de [OH⁻]. Fórmula: pOH = −log₁₀[OH⁻], pH = 14 − pOH. Ejemplo: [OH⁻]=0.01 → pOH=2, pH=12. Gratis."),
        "en": ("pOH Calculator – Formula & pH Conversion | CalcToWork",
               "Calculate pOH and pH from hydroxide concentration. Formula: pOH = −log₁₀[OH⁻], pH = 14 − pOH. Example: [OH⁻]=0.01 → pOH=2, pH=12. Free."),
        "fr": ("Calculateur de pOH – Formule et Conversion pH | CalcToWork",
               "Calculez pOH et pH à partir de [OH⁻]. Formule: pOH = −log₁₀[OH⁻], pH = 14 − pOH. Exemple: [OH⁻]=0.01 → pOH=2, pH=12. Gratuit."),
        "pt": ("Calculadora de pOH – Fórmula e Conversão pH | CalcToWork",
               "Calcule pOH e pH a partir de [OH⁻]. Fórmula: pOH = −log₁₀[OH⁻], pH = 14 − pOH. Exemplo: [OH⁻]=0.01 → pOH=2, pH=12. Grátis."),
        "de": ("pOH-Rechner – Formel und pH-Umrechnung | CalcToWork",
               "Berechne pOH und pH aus der OH⁻-Konzentration. Formel: pOH = −log₁₀[OH⁻], pH = 14 − pOH. Beispiel: [OH⁻]=0.01 → pOH=2. Kostenlos."),
        "it": ("Calcolatore di pOH – Formula e Conversione pH | CalcToWork",
               "Calcola pOH e pH dalla concentrazione di OH⁻. Formula: pOH = −log₁₀[OH⁻], pH = 14 − pOH. Esempio: [OH⁻]=0.01 → pOH=2. Gratuito."),
    },
    "1002": {
        "es": ("Calculadora de Molaridad – mol/L y Concentración | CalcToWork",
               "Calcula la molaridad (mol/L) de una solución. Fórmula: M = moles / volumen(L). Ejemplo: 0.5 mol en 0.25 L → M=2 mol/L. Gratis y precisa."),
        "en": ("Molarity Calculator – mol/L & Concentration | CalcToWork",
               "Calculate molarity (mol/L) of a solution. Formula: M = moles / volume(L). Example: 0.5 mol in 0.25 L → M=2 mol/L. Free and accurate."),
        "fr": ("Calculateur de Molarité – mol/L et Concentration | CalcToWork",
               "Calculez la molarité (mol/L) d'une solution. Formule: M = moles / volume(L). Exemple: 0.5 mol dans 0.25 L → M=2 mol/L. Gratuit."),
        "pt": ("Calculadora de Molaridade – mol/L e Concentração | CalcToWork",
               "Calcule a molaridade (mol/L) de uma solução. Fórmula: M = moles / volume(L). Exemplo: 0.5 mol em 0.25 L → M=2 mol/L. Grátis."),
        "de": ("Molaritäts-Rechner – mol/L und Konzentration | CalcToWork",
               "Berechne die Molarität (mol/L) einer Lösung. Formel: M = Mol / Volumen(L). Beispiel: 0.5 mol in 0.25 L → M=2 mol/L. Kostenlos."),
        "it": ("Calcolatore di Molarità – mol/L e Concentrazione | CalcToWork",
               "Calcola la molarità (mol/L) di una soluzione. Formula: M = moli / volume(L). Esempio: 0.5 mol in 0.25 L → M=2 mol/L. Gratuito."),
    },
    "1003": {
        "es": ("Calculadora de Dilución – C₁V₁ = C₂V₂ | CalcToWork",
               "Calcula la concentración o volumen final tras una dilución. Fórmula: C₁V₁ = C₂V₂. Ejemplo: 1M × 50mL = C₂ × 250mL → C₂=0.2 M. Gratis."),
        "en": ("Dilution Calculator – C₁V₁ = C₂V₂ Formula | CalcToWork",
               "Calculate final concentration or volume after dilution. Formula: C₁V₁ = C₂V₂. Example: 1M × 50mL = C₂ × 250mL → C₂=0.2 M. Free."),
        "fr": ("Calculateur de Dilution – C₁V₁ = C₂V₂ | CalcToWork",
               "Calculez la concentration ou le volume final après dilution. Formule: C₁V₁ = C₂V₂. Exemple: 1M × 50mL = C₂ × 250mL → C₂=0.2 M."),
        "pt": ("Calculadora de Diluição – C₁V₁ = C₂V₂ | CalcToWork",
               "Calcule a concentração ou volume final após diluição. Fórmula: C₁V₁ = C₂V₂. Exemplo: 1M × 50mL = C₂ × 250mL → C₂=0.2 M. Grátis."),
        "de": ("Verdünnungs-Rechner – C₁V₁ = C₂V₂ | CalcToWork",
               "Berechne die Konzentration oder das Volumen nach der Verdünnung. Formel: C₁V₁ = C₂V₂. Beispiel: 1M × 50mL → C₂=0.2 M. Kostenlos."),
        "it": ("Calcolatore di Diluizione – C₁V₁ = C₂V₂ | CalcToWork",
               "Calcola la concentrazione o il volume finale dopo la diluizione. Formula: C₁V₁ = C₂V₂. Esempio: 1M × 50mL → C₂=0.2 M. Gratuito."),
    },
    "1004": {
        "es": ("Ley de Gases Ideales – PV = nRT Calculadora | CalcToWork",
               "Calcula presión, volumen, moles o temperatura de un gas ideal. Fórmula: PV = nRT. Ejemplo: 2 mol a 300 K en 10 L → P=4.99 atm. Gratis."),
        "en": ("Ideal Gas Law Calculator – PV = nRT | CalcToWork",
               "Calculate pressure, volume, moles, or temperature for an ideal gas. Formula: PV = nRT. Example: 2 mol at 300 K in 10 L → P=4.99 atm. Free."),
        "fr": ("Loi des Gaz Parfaits – Calculateur PV = nRT | CalcToWork",
               "Calculez pression, volume, moles ou température d'un gaz idéal. Formule: PV = nRT. Exemple: 2 mol à 300 K dans 10 L → P=4.99 atm."),
        "pt": ("Lei dos Gases Ideais – Calculadora PV = nRT | CalcToWork",
               "Calcule pressão, volume, moles ou temperatura de um gás ideal. Fórmula: PV = nRT. Exemplo: 2 mol a 300 K em 10 L → P=4.99 atm. Grátis."),
        "de": ("Ideales Gasgesetz – PV = nRT Rechner | CalcToWork",
               "Berechne Druck, Volumen, Mol oder Temperatur eines idealen Gases. Formel: PV = nRT. Beispiel: 2 mol bei 300 K in 10 L → P=4.99 atm."),
        "it": ("Legge dei Gas Ideali – Calcolatore PV = nRT | CalcToWork",
               "Calcola pressione, volume, moli o temperatura di un gas ideale. Formula: PV = nRT. Esempio: 2 mol a 300 K in 10 L → P=4.99 atm. Gratuito."),
    },
    "1005": {
        "es": ("Ley de Boyle – Calculadora P₁V₁ = P₂V₂ | CalcToWork",
               "Calcula presión o volumen de un gas a temperatura constante. Fórmula: P₁V₁ = P₂V₂. Ejemplo: 2 atm × 5 L = P₂ × 2 L → P₂=5 atm. Gratis."),
        "en": ("Boyle's Law Calculator – P₁V₁ = P₂V₂ | CalcToWork",
               "Calculate gas pressure or volume at constant temperature. Formula: P₁V₁ = P₂V₂. Example: 2 atm × 5 L = P₂ × 2 L → P₂=5 atm. Free."),
        "fr": ("Loi de Boyle – Calculateur P₁V₁ = P₂V₂ | CalcToWork",
               "Calculez la pression ou le volume d'un gaz à température constante. Formule: P₁V₁ = P₂V₂. Exemple: 2 atm × 5 L → P₂=5 atm. Gratuit."),
        "pt": ("Lei de Boyle – Calculadora P₁V₁ = P₂V₂ | CalcToWork",
               "Calcule pressão ou volume de um gás a temperatura constante. Fórmula: P₁V₁ = P₂V₂. Exemplo: 2 atm × 5 L → P₂=5 atm. Grátis."),
        "de": ("Boyle'sches Gesetz – P₁V₁ = P₂V₂ Rechner | CalcToWork",
               "Berechne Druck oder Volumen eines Gases bei konstanter Temperatur. Formel: P₁V₁ = P₂V₂. Beispiel: 2 atm × 5 L → P₂=5 atm. Kostenlos."),
        "it": ("Legge di Boyle – Calcolatore P₁V₁ = P₂V₂ | CalcToWork",
               "Calcola pressione o volume di un gas a temperatura costante. Formula: P₁V₁ = P₂V₂. Esempio: 2 atm × 5 L → P₂=5 atm. Gratuito."),
    },
    "1006": {
        "es": ("Ley de Charles – V₁/T₁ = V₂/T₂ Calculadora | CalcToWork",
               "Calcula volumen o temperatura de un gas a presión constante. Fórmula: V₁/T₁ = V₂/T₂. Ejemplo: 2 L a 300 K → V₂=2.67 L a 400 K. Gratis."),
        "en": ("Charles's Law Calculator – V₁/T₁ = V₂/T₂ | CalcToWork",
               "Calculate gas volume or temperature at constant pressure. Formula: V₁/T₁ = V₂/T₂. Example: 2 L at 300 K → V₂=2.67 L at 400 K. Free."),
        "fr": ("Loi de Charles – Calculateur V₁/T₁ = V₂/T₂ | CalcToWork",
               "Calculez le volume ou la température d'un gaz à pression constante. Formule: V₁/T₁ = V₂/T₂. Exemple: 2 L à 300 K → V₂=2.67 L. Gratuit."),
        "pt": ("Lei de Charles – Calculadora V₁/T₁ = V₂/T₂ | CalcToWork",
               "Calcule volume ou temperatura de um gás a pressão constante. Fórmula: V₁/T₁ = V₂/T₂. Exemplo: 2 L a 300 K → V₂=2.67 L a 400 K. Grátis."),
        "de": ("Charles'sches Gesetz – V₁/T₁ = V₂/T₂ Rechner | CalcToWork",
               "Berechne Gasvolumen oder Temperatur bei konstantem Druck. Formel: V₁/T₁ = V₂/T₂. Beispiel: 2 L bei 300 K → V₂=2.67 L bei 400 K. Kostenlos."),
        "it": ("Legge di Charles – Calcolatore V₁/T₁ = V₂/T₂ | CalcToWork",
               "Calcola volume o temperatura di un gas a pressione costante. Formula: V₁/T₁ = V₂/T₂. Esempio: 2 L a 300 K → V₂=2.67 L a 400 K. Gratuito."),
    },
    "1007": {
        "es": ("Energía Libre de Gibbs – ΔG = ΔH − TΔS | CalcToWork",
               "Determina si una reacción es espontánea con ΔG. Fórmula: ΔG = ΔH − TΔS. Ejemplo: ΔH=−100 kJ, T=298 K, ΔS=−200 J/K → ΔG=−40.4 kJ. Gratis."),
        "en": ("Gibbs Free Energy Calculator – ΔG = ΔH − TΔS | CalcToWork",
               "Determine if a reaction is spontaneous using ΔG. Formula: ΔG = ΔH − TΔS. Example: ΔH=−100 kJ, T=298 K, ΔS=−200 J/K → ΔG=−40.4 kJ. Free."),
        "fr": ("Énergie Libre de Gibbs – ΔG = ΔH − TΔS | CalcToWork",
               "Déterminez si une réaction est spontanée avec ΔG. Formule: ΔG = ΔH − TΔS. Exemple: ΔH=−100 kJ, T=298 K, ΔS=−200 J/K → ΔG=−40 kJ."),
        "pt": ("Energia Livre de Gibbs – ΔG = ΔH − TΔS | CalcToWork",
               "Determine se uma reação é espontânea com ΔG. Fórmula: ΔG = ΔH − TΔS. Exemplo: ΔH=−100 kJ, T=298 K, ΔS=−200 J/K → ΔG=−40 kJ. Grátis."),
        "de": ("Gibbs'sche Freie Energie – ΔG = ΔH − TΔS Rechner | CalcToWork",
               "Bestimme, ob eine Reaktion spontan abläuft. Formel: ΔG = ΔH − TΔS. Beispiel: ΔH=−100 kJ, T=298 K, ΔS=−200 J/K → ΔG=−40.4 kJ. Kostenlos."),
        "it": ("Energia Libera di Gibbs – ΔG = ΔH − TΔS | CalcToWork",
               "Determina se una reazione è spontanea con ΔG. Formula: ΔG = ΔH − TΔS. Esempio: ΔH=−100 kJ, T=298 K, ΔS=−200 J/K → ΔG=−40 kJ. Gratuito."),
    },
    "1008": {
        "es": ("Calculadora de Peso Molecular – g/mol | CalcToWork",
               "Calcula el peso molecular de un compuesto sumando las masas atómicas. Ejemplo: H₂O = 2×1 + 16 = 18 g/mol. Calculadora gratuita y precisa."),
        "en": ("Molecular Weight Calculator – g/mol | CalcToWork",
               "Calculate molecular weight of a compound by adding atomic masses. Example: H₂O = 2×1 + 16 = 18 g/mol. Free and accurate calculator."),
        "fr": ("Calculateur de Masse Molaire – g/mol | CalcToWork",
               "Calculez la masse molaire d'un composé en additionnant les masses atomiques. Exemple: H₂O = 2×1 + 16 = 18 g/mol. Gratuit et précis."),
        "pt": ("Calculadora de Peso Molecular – g/mol | CalcToWork",
               "Calcule o peso molecular de um composto somando as massas atômicas. Exemplo: H₂O = 2×1 + 16 = 18 g/mol. Calculadora gratuita e precisa."),
        "de": ("Molekulargewicht-Rechner – g/mol | CalcToWork",
               "Berechne die Molmasse einer Verbindung durch Addition der Atommassen. Beispiel: H₂O = 2×1 + 16 = 18 g/mol. Kostenloser Rechner."),
        "it": ("Calcolatore di Peso Molecolare – g/mol | CalcToWork",
               "Calcola il peso molecolare sommando le masse atomiche. Esempio: H₂O = 2×1 + 16 = 18 g/mol. Calcolatore gratuito e preciso."),
    },
    "1009": {
        "es": ("Calculadora de Titulación – Punto de Equivalencia | CalcToWork",
               "Calcula el volumen de titulante en la neutralización ácido-base. Fórmula: C₁V₁ = C₂V₂. Ejemplo: 0.1M HCl + 0.1M NaOH → 1:1. Gratis."),
        "en": ("Titration Calculator – Equivalence Point | CalcToWork",
               "Calculate titrant volume at acid-base neutralization. Formula: C₁V₁ = C₂V₂. Example: 0.1M HCl + 0.1M NaOH → equivalence at equal volumes. Free."),
        "fr": ("Calculateur de Titration – Point d'Équivalence | CalcToWork",
               "Calculez le volume de titrant pour la neutralisation acide-base. Formule: C₁V₁ = C₂V₂. Exemple: 0.1M HCl + 0.1M NaOH → 1:1. Gratuit."),
        "pt": ("Calculadora de Titulação – Ponto de Equivalência | CalcToWork",
               "Calcule o volume de titulante na neutralização ácido-base. Fórmula: C₁V₁ = C₂V₂. Exemplo: 0.1M HCl + 0.1M NaOH → volumes iguais. Grátis."),
        "de": ("Titrations-Rechner – Äquivalenzpunkt | CalcToWork",
               "Berechne das Titrantvolumen bei der Säure-Base-Neutralisation. Formel: C₁V₁ = C₂V₂. Beispiel: 0.1M HCl + 0.1M NaOH → gleiche Volumina. Kostenlos."),
        "it": ("Calcolatore di Titolazione – Punto di Equivalenza | CalcToWork",
               "Calcola il volume di titolante nella neutralizzazione acido-base. Formula: C₁V₁ = C₂V₂. Esempio: 0.1M HCl + 0.1M NaOH → volumi uguali."),
    },
    "1010": {
        "es": ("Divisor de Tensión – Calculadora Vout | CalcToWork",
               "Calcula la tensión de salida de un divisor resistivo. Fórmula: Vout = Vin × R2/(R1+R2). Ejemplo: 12V, R1=1kΩ, R2=2kΩ → Vout=8V. Gratis."),
        "en": ("Voltage Divider Calculator – Vout Formula | CalcToWork",
               "Calculate output voltage of a resistive voltage divider. Formula: Vout = Vin × R2/(R1+R2). Example: 12V, R1=1kΩ, R2=2kΩ → Vout=8V. Free."),
        "fr": ("Diviseur de Tension – Calculateur Vout | CalcToWork",
               "Calculez la tension de sortie d'un pont diviseur résistif. Formule: Vout = Vin × R2/(R1+R2). Exemple: 12V, R1=1kΩ, R2=2kΩ → Vout=8V."),
        "pt": ("Divisor de Tensão – Calculadora Vout | CalcToWork",
               "Calcule a tensão de saída de um divisor resistivo. Fórmula: Vout = Vin × R2/(R1+R2). Exemplo: 12V, R1=1kΩ, R2=2kΩ → Vout=8V. Grátis."),
        "de": ("Spannungsteiler – Rechner für Vout | CalcToWork",
               "Berechne die Ausgangsspannung eines Widerstandsteilers. Formel: Vout = Vin × R2/(R1+R2). Beispiel: 12V, R1=1kΩ, R2=2kΩ → Vout=8V. Kostenlos."),
        "it": ("Partitore di Tensione – Calcolatore Vout | CalcToWork",
               "Calcola la tensione di uscita di un partitore resistivo. Formula: Vout = Vin × R2/(R1+R2). Esempio: 12V, R1=1kΩ, R2=2kΩ → Vout=8V. Gratuito."),
    },
    "1011": {
        "es": ("Resistencia para LED – Calculadora y Fórmula | CalcToWork",
               "Calcula la resistencia limitadora de corriente para un LED. Fórmula: R = (Vcc − Vled) / Iled. Ejemplo: 5V, Vled=2V, 20mA → R=150Ω. Gratis."),
        "en": ("LED Resistor Calculator – Current Limiting Formula | CalcToWork",
               "Calculate the current limiting resistor for an LED. Formula: R = (Vcc − Vled) / Iled. Example: 5V, Vled=2V, 20mA → R=150Ω. Free and instant."),
        "fr": ("Résistance pour LED – Calculateur et Formule | CalcToWork",
               "Calculez la résistance de limitation de courant pour une LED. Formule: R = (Vcc − Vled) / Iled. Exemple: 5V, Vled=2V, 20mA → R=150Ω."),
        "pt": ("Resistência para LED – Calculadora e Fórmula | CalcToWork",
               "Calcule a resistência limitadora de corrente para um LED. Fórmula: R = (Vcc − Vled) / Iled. Exemplo: 5V, Vled=2V, 20mA → R=150Ω. Grátis."),
        "de": ("LED-Vorwiderstand – Rechner und Formel | CalcToWork",
               "Berechne den Vorwiderstand für eine LED. Formel: R = (Vcc − Vled) / Iled. Beispiel: 5V, Vled=2V, 20mA → R=150Ω. Kostenlos und sofort."),
        "it": ("Resistenza per LED – Calcolatore e Formula | CalcToWork",
               "Calcola la resistenza limitatrice di corrente per un LED. Formula: R = (Vcc − Vled) / Iled. Esempio: 5V, Vled=2V, 20mA → R=150Ω. Gratuito."),
    },
    "1012": {
        "es": ("Resistencia en Paralelo – Calculadora y Fórmula | CalcToWork",
               "Calcula la resistencia equivalente de resistores en paralelo. Fórmula: 1/Req = 1/R1 + 1/R2 + … Ejemplo: 100Ω ∥ 100Ω = 50Ω. Gratis."),
        "en": ("Parallel Resistance Calculator – Formula & Examples | CalcToWork",
               "Calculate equivalent resistance of parallel resistors. Formula: 1/Req = 1/R1 + 1/R2 + … Example: 100Ω ∥ 100Ω = 50Ω. Free and accurate."),
        "fr": ("Résistance en Parallèle – Calculateur et Formule | CalcToWork",
               "Calculez la résistance équivalente de résistances en parallèle. Formule: 1/Req = 1/R1 + 1/R2 + … Exemple: 100Ω ∥ 100Ω = 50Ω. Gratuit."),
        "pt": ("Resistência em Paralelo – Calculadora e Fórmula | CalcToWork",
               "Calcule a resistência equivalente de resistores em paralelo. Fórmula: 1/Req = 1/R1 + 1/R2 + … Exemplo: 100Ω ∥ 100Ω = 50Ω. Grátis."),
        "de": ("Parallelwiderstand – Rechner und Formel | CalcToWork",
               "Berechne den Ersatzwiderstand paralleler Widerstände. Formel: 1/Req = 1/R1 + 1/R2 + … Beispiel: 100Ω ∥ 100Ω = 50Ω. Kostenlos."),
        "it": ("Resistenza in Parallelo – Calcolatore e Formula | CalcToWork",
               "Calcola la resistenza equivalente di resistori in parallelo. Formula: 1/Req = 1/R1 + 1/R2 + … Esempio: 100Ω ∥ 100Ω = 50Ω. Gratuito."),
    },
    "1013": {
        "es": ("Energía en Condensador – E = ½CV² | CalcToWork",
               "Calcula la energía almacenada en un condensador. Fórmula: E = ½ × C × V². Ejemplo: C=100µF, V=12V → E=7.2 mJ. Calculadora gratuita."),
        "en": ("Capacitor Energy Calculator – E = ½CV² | CalcToWork",
               "Calculate energy stored in a capacitor. Formula: E = ½ × C × V². Example: C=100µF, V=12V → E=7.2 mJ. Free and accurate calculator."),
        "fr": ("Énergie dans un Condensateur – E = ½CV² | CalcToWork",
               "Calculez l'énergie stockée dans un condensateur. Formule: E = ½ × C × V². Exemple: C=100µF, V=12V → E=7.2 mJ. Calculateur gratuit."),
        "pt": ("Energia em Condensador – E = ½CV² | CalcToWork",
               "Calcule a energia armazenada num condensador. Fórmula: E = ½ × C × V². Exemplo: C=100µF, V=12V → E=7.2 mJ. Calculadora gratuita."),
        "de": ("Kondensator-Energie – E = ½CV² Rechner | CalcToWork",
               "Berechne die gespeicherte Energie in einem Kondensator. Formel: E = ½ × C × V². Beispiel: C=100µF, V=12V → E=7.2 mJ. Kostenlos."),
        "it": ("Energia nel Condensatore – E = ½CV² | CalcToWork",
               "Calcola l'energia immagazzinata in un condensatore. Formula: E = ½ × C × V². Esempio: C=100µF, V=12V → E=7.2 mJ. Gratuito."),
    },
    "1014": {
        "es": ("Energía en Bobina – E = ½LI² | CalcToWork",
               "Calcula la energía almacenada en una inductancia. Fórmula: E = ½ × L × I². Ejemplo: L=50mH, I=2A → E=0.1 J. Calculadora gratuita."),
        "en": ("Inductor Energy Calculator – E = ½LI² | CalcToWork",
               "Calculate energy stored in an inductor. Formula: E = ½ × L × I². Example: L=50mH, I=2A → E=0.1 J. Free and accurate calculator."),
        "fr": ("Énergie dans une Bobine – E = ½LI² | CalcToWork",
               "Calculez l'énergie stockée dans une inductance. Formule: E = ½ × L × I². Exemple: L=50mH, I=2A → E=0.1 J. Calculateur gratuit."),
        "pt": ("Energia em Bobina – E = ½LI² | CalcToWork",
               "Calcule a energia armazenada num indutor. Fórmula: E = ½ × L × I². Exemplo: L=50mH, I=2A → E=0.1 J. Calculadora gratuita."),
        "de": ("Spulen-Energie – E = ½LI² Rechner | CalcToWork",
               "Berechne die gespeicherte Energie in einer Induktivität. Formel: E = ½ × L × I². Beispiel: L=50mH, I=2A → E=0.1 J. Kostenlos."),
        "it": ("Energia nella Bobina – E = ½LI² | CalcToWork",
               "Calcola l'energia immagazzinata in un'induttanza. Formula: E = ½ × L × I². Esempio: L=50mH, I=2A → E=0.1 J. Gratuito."),
    },
    "1015": {
        "es": ("Relación de Transformador – V₁/V₂ = N₁/N₂ | CalcToWork",
               "Calcula la tensión secundaria o la relación de espiras de un transformador. Fórmula: V₁/V₂ = N₁/N₂. Ejemplo: 230V, 1000:100 espiras → V₂=23V. Gratis."),
        "en": ("Transformer Ratio Calculator – V₁/V₂ = N₁/N₂ | CalcToWork",
               "Calculate secondary voltage or turns ratio of a transformer. Formula: V₁/V₂ = N₁/N₂. Example: 230V, 1000:100 turns → V₂=23V. Free."),
        "fr": ("Rapport de Transformateur – V₁/V₂ = N₁/N₂ | CalcToWork",
               "Calculez la tension secondaire ou le rapport de spires d'un transformateur. Formule: V₁/V₂ = N₁/N₂. Exemple: 230V, 1000:100 → V₂=23V."),
        "pt": ("Relação de Transformador – V₁/V₂ = N₁/N₂ | CalcToWork",
               "Calcule a tensão secundária ou relação de espiras de um transformador. Fórmula: V₁/V₂ = N₁/N₂. Exemplo: 230V, 1000:100 → V₂=23V. Grátis."),
        "de": ("Transformator-Verhältnis – V₁/V₂ = N₁/N₂ | CalcToWork",
               "Berechne die Sekundärspannung oder das Wicklungsverhältnis eines Transformators. Formel: V₁/V₂ = N₁/N₂. Beispiel: 230V, 1000:100 → V₂=23V."),
        "it": ("Rapporto del Trasformatore – V₁/V₂ = N₁/N₂ | CalcToWork",
               "Calcola la tensione secondaria o il rapporto spire di un trasformatore. Formula: V₁/V₂ = N₁/N₂. Esempio: 230V, 1000:100 → V₂=23V. Gratuito."),
    },
    "1016": {
        "es": ("Constante de Tiempo RC – τ = R×C | CalcToWork",
               "Calcula la constante de tiempo de un circuito RC. Fórmula: τ = R × C. Ejemplo: R=10kΩ, C=100µF → τ=1 s. Calculadora gratuita e instantánea."),
        "en": ("RC Time Constant Calculator – τ = R×C | CalcToWork",
               "Calculate the time constant of an RC circuit. Formula: τ = R × C. Example: R=10kΩ, C=100µF → τ=1 s. Free and instant calculator."),
        "fr": ("Constante de Temps RC – Calculateur τ = R×C | CalcToWork",
               "Calculez la constante de temps d'un circuit RC. Formule: τ = R × C. Exemple: R=10kΩ, C=100µF → τ=1 s. Calculateur gratuit et instantané."),
        "pt": ("Constante de Tempo RC – τ = R×C | CalcToWork",
               "Calcule a constante de tempo de um circuito RC. Fórmula: τ = R × C. Exemplo: R=10kΩ, C=100µF → τ=1 s. Calculadora gratuita e instantânea."),
        "de": ("RC-Zeitkonstante – τ = R×C Rechner | CalcToWork",
               "Berechne die Zeitkonstante eines RC-Schaltkreises. Formel: τ = R × C. Beispiel: R=10kΩ, C=100µF → τ=1 s. Kostenloser Rechner."),
        "it": ("Costante di Tempo RC – τ = R×C | CalcToWork",
               "Calcola la costante di tempo di un circuito RC. Formula: τ = R × C. Esempio: R=10kΩ, C=100µF → τ=1 s. Calcolatore gratuito e immediato."),
    },
    "1017": {
        "es": ("Puente de Wheatstone – Calculadora de Resistencia | CalcToWork",
               "Calcula la resistencia desconocida en un puente de Wheatstone. Fórmula: Rx = R2×R3/R1. Ejemplo: R1=100Ω, R2=200Ω, R3=150Ω → Rx=300Ω. Gratis."),
        "en": ("Wheatstone Bridge Calculator – Unknown Resistance | CalcToWork",
               "Calculate unknown resistance using a Wheatstone bridge. Formula: Rx = R2×R3/R1. Example: R1=100Ω, R2=200Ω, R3=150Ω → Rx=300Ω. Free."),
        "fr": ("Pont de Wheatstone – Calculateur de Résistance | CalcToWork",
               "Calculez la résistance inconnue avec un pont de Wheatstone. Formule: Rx = R2×R3/R1. Exemple: R1=100Ω, R2=200Ω, R3=150Ω → Rx=300Ω."),
        "pt": ("Ponte de Wheatstone – Calculadora de Resistência | CalcToWork",
               "Calcule a resistência desconhecida num ponte de Wheatstone. Fórmula: Rx = R2×R3/R1. Exemplo: R1=100Ω, R2=200Ω, R3=150Ω → Rx=300Ω. Grátis."),
        "de": ("Wheatstone-Brücke – Widerstandsrechner | CalcToWork",
               "Berechne den unbekannten Widerstand mit einer Wheatstone-Brücke. Formel: Rx = R2×R3/R1. Beispiel: R1=100Ω, R2=200Ω, R3=150Ω → Rx=300Ω."),
        "it": ("Ponte di Wheatstone – Calcolatore di Resistenza | CalcToWork",
               "Calcola la resistenza sconosciuta con un ponte di Wheatstone. Formula: Rx = R2×R3/R1. Esempio: R1=100Ω, R2=200Ω, R3=150Ω → Rx=300Ω."),
    },
    "1018": {
        "es": ("Capacitancia en Serie – 1/Ct = 1/C1 + 1/C2 | CalcToWork",
               "Calcula la capacitancia equivalente de condensadores en serie. Fórmula: 1/Ct = 1/C1 + 1/C2. Ejemplo: 100µF + 100µF → Ct=50µF. Gratis."),
        "en": ("Series Capacitance Calculator – 1/Ct = 1/C1 + 1/C2 | CalcToWork",
               "Calculate equivalent capacitance of capacitors in series. Formula: 1/Ct = 1/C1 + 1/C2. Example: 100µF + 100µF → Ct=50µF. Free."),
        "fr": ("Capacitance en Série – 1/Ct = 1/C1 + 1/C2 | CalcToWork",
               "Calculez la capacité équivalente de condensateurs en série. Formule: 1/Ct = 1/C1 + 1/C2. Exemple: 100µF + 100µF → Ct=50µF. Gratuit."),
        "pt": ("Capacitância em Série – 1/Ct = 1/C1 + 1/C2 | CalcToWork",
               "Calcule a capacitância equivalente de condensadores em série. Fórmula: 1/Ct = 1/C1 + 1/C2. Exemplo: 100µF + 100µF → Ct=50µF. Grátis."),
        "de": ("Reihenschaltung Kondensatoren – 1/Ct = 1/C1 + 1/C2 | CalcToWork",
               "Berechne die Gesamtkapazität von Kondensatoren in Reihe. Formel: 1/Ct = 1/C1 + 1/C2. Beispiel: 100µF + 100µF → Ct=50µF. Kostenlos."),
        "it": ("Capacitanza in Serie – 1/Ct = 1/C1 + 1/C2 | CalcToWork",
               "Calcola la capacitanza equivalente di condensatori in serie. Formula: 1/Ct = 1/C1 + 1/C2. Esempio: 100µF + 100µF → Ct=50µF. Gratuito."),
    },
    "1019": {
        "es": ("Código de Colores de Resistencia – Calculadora | CalcToWork",
               "Decodifica el valor de una resistencia a partir de sus bandas de colores. Estándar IEC 60062. Ejemplo: marrón-negro-rojo → 1000Ω ±5%. Gratis."),
        "en": ("Resistor Color Code Calculator – IEC 60062 | CalcToWork",
               "Decode resistor value from color bands. IEC 60062 standard. Example: brown-black-red → 1000Ω ±5%. Free and instant resistor calculator."),
        "fr": ("Code Couleur des Résistances – Calculateur | CalcToWork",
               "Décodez la valeur d'une résistance à partir de ses bandes de couleur. Norme IEC 60062. Exemple: brun-noir-rouge → 1000Ω ±5%. Gratuit."),
        "pt": ("Código de Cores de Resistor – Calculadora | CalcToWork",
               "Decodifique o valor de um resistor a partir das bandas de cor. Norma IEC 60062. Exemplo: castanho-preto-vermelho → 1000Ω ±5%. Grátis."),
        "de": ("Widerstandsfarbcode – Rechner nach IEC 60062 | CalcToWork",
               "Dekodiere den Widerstandswert anhand der Farbcodes. IEC 60062-Standard. Beispiel: braun-schwarz-rot → 1000Ω ±5%. Kostenloser Rechner."),
        "it": ("Codice Colori Resistore – Calcolatore IEC 60062 | CalcToWork",
               "Decodifica il valore di un resistore dalle bande di colore. Norma IEC 60062. Esempio: marrone-nero-rosso → 1000Ω ±5%. Gratuito."),
    },
    "1020": {
        "es": ("Calculadora de Punto de Rocío – Fórmula y Temperatura | CalcToWork",
               "Calcula el punto de rocío a partir de temperatura y humedad relativa. Ejemplo: 25°C y 70% HR → punto de rocío ≈ 19.2°C. Gratis e instantáneo."),
        "en": ("Dew Point Calculator – Temperature & Humidity | CalcToWork",
               "Calculate dew point from temperature and relative humidity. Example: 25°C and 70% RH → dew point ≈ 19.2°C. Free and instant calculator."),
        "fr": ("Calculateur de Point de Rosée – Température et Humidité | CalcToWork",
               "Calculez le point de rosée à partir de la température et l'humidité relative. Exemple: 25°C et 70% HR → point de rosée ≈ 19.2°C. Gratuit."),
        "pt": ("Calculadora de Ponto de Orvalho – Temperatura e Humidade | CalcToWork",
               "Calcule o ponto de orvalho a partir da temperatura e humidade relativa. Exemplo: 25°C e 70% HR → ponto de orvalho ≈ 19.2°C. Grátis."),
        "de": ("Taupunkt-Rechner – Temperatur und Luftfeuchtigkeit | CalcToWork",
               "Berechne den Taupunkt aus Temperatur und relativer Luftfeuchtigkeit. Beispiel: 25°C und 70% rF → Taupunkt ≈ 19.2°C. Kostenloser Rechner."),
        "it": ("Calcolatore del Punto di Rugiada – Temperatura e Umidità | CalcToWork",
               "Calcola il punto di rugiada da temperatura e umidità relativa. Esempio: 25°C e 70% UR → punto di rugiada ≈ 19.2°C. Gratuito."),
    },
    "1021": {
        "es": ("Índice de Calor – Sensación Térmica por Humedad | CalcToWork",
               "Calcula la sensación térmica real considerando temperatura y humedad. Fórmula Rothfusz. Ejemplo: 35°C y 70% HR → índice de calor ≈ 45°C. Gratis."),
        "en": ("Heat Index Calculator – Apparent Temperature & Humidity | CalcToWork",
               "Calculate apparent temperature combining heat and humidity. Rothfusz formula. Example: 35°C and 70% RH → heat index ≈ 45°C. Free calculator."),
        "fr": ("Indice de Chaleur – Température Ressentie et Humidité | CalcToWork",
               "Calculez la température ressentie en combinant chaleur et humidité. Formule Rothfusz. Exemple: 35°C et 70% HR → indice de chaleur ≈ 45°C."),
        "pt": ("Índice de Calor – Sensação Térmica e Humidade | CalcToWork",
               "Calcule a temperatura aparente combinando calor e humidade. Fórmula Rothfusz. Exemplo: 35°C e 70% HR → índice de calor ≈ 45°C. Grátis."),
        "de": ("Hitzeindex – Gefühlte Temperatur und Luftfeuchtigkeit | CalcToWork",
               "Berechne die gefühlte Temperatur aus Hitze und Luftfeuchtigkeit. Rothfusz-Formel. Beispiel: 35°C und 70% rF → Hitzeindex ≈ 45°C. Kostenlos."),
        "it": ("Indice di Calore – Temperatura Percepita e Umidità | CalcToWork",
               "Calcola la temperatura percepita combinando calore e umidità. Formula Rothfusz. Esempio: 35°C e 70% UR → indice di calore ≈ 45°C. Gratuito."),
    },
    "1022": {
        "es": ("Sensación Térmica por Viento – Wind Chill | CalcToWork",
               "Calcula la sensación térmica por efecto del viento. Fórmula NWS. Ejemplo: −5°C y viento de 30 km/h → sensación de −15°C. Gratis e instantáneo."),
        "en": ("Wind Chill Calculator – Wind Speed & Temperature | CalcToWork",
               "Calculate wind chill (apparent temperature) from wind speed and temperature. NWS formula. Example: −5°C + 30 km/h → feels like −15°C. Free."),
        "fr": ("Refroidissement Éolien – Calculateur de Température Ressentie | CalcToWork",
               "Calculez la sensation de froid due au vent. Formule NWS. Exemple: −5°C avec vent de 30 km/h → sensation de −15°C. Calculateur gratuit."),
        "pt": ("Sensação Térmica pelo Vento – Wind Chill | CalcToWork",
               "Calcule a sensação térmica pelo efeito do vento. Fórmula NWS. Exemplo: −5°C e vento de 30 km/h → sensação de −15°C. Grátis e instantâneo."),
        "de": ("Windkälte – Gefühlte Temperatur bei Wind | CalcToWork",
               "Berechne die gefühlte Temperatur durch Windkühlung. NWS-Formel. Beispiel: −5°C bei 30 km/h Wind → gefühlte −15°C. Kostenloser Rechner."),
        "it": ("Sensazione Termica da Vento – Wind Chill | CalcToWork",
               "Calcola la sensazione termica dovuta al vento. Formula NWS. Esempio: −5°C e vento di 30 km/h → sensazione di −15°C. Gratuito."),
    },
    "1023": {
        "es": ("Calculadora de Humedad Relativa – Fórmula y Ejemplos | CalcToWork",
               "Calcula la humedad relativa a partir de temperatura de bulbo seco y húmedo. Ejemplo: 25°C y 20°C bulbo húmedo → HR ≈ 68%. Gratis e instantáneo."),
        "en": ("Relative Humidity Calculator – Formula & Examples | CalcToWork",
               "Calculate relative humidity from dry-bulb and wet-bulb temperatures. Example: 25°C dry, 20°C wet → RH ≈ 68%. Free and instant calculator."),
        "fr": ("Calculateur d'Humidité Relative – Formule et Exemples | CalcToWork",
               "Calculez l'humidité relative à partir des températures sèche et humide. Exemple: 25°C sec, 20°C humide → HR ≈ 68%. Calculateur gratuit."),
        "pt": ("Calculadora de Humidade Relativa – Fórmula e Exemplos | CalcToWork",
               "Calcule a humidade relativa a partir das temperaturas de bolbo seco e húmido. Exemplo: 25°C e 20°C húmido → HR ≈ 68%. Grátis."),
        "de": ("Relative Luftfeuchtigkeit – Rechner und Formel | CalcToWork",
               "Berechne die relative Luftfeuchtigkeit aus Trocken- und Feuchttemperatur. Beispiel: 25°C trocken, 20°C feucht → rF ≈ 68%. Kostenloser Rechner."),
        "it": ("Calcolatore di Umidità Relativa – Formula ed Esempi | CalcToWork",
               "Calcola l'umidità relativa da temperatura bulbo secco e bulbo umido. Esempio: 25°C secco, 20°C umido → UR ≈ 68%. Gratuito e immediato."),
    },
    "1024": {
        "es": ("Índice de Calidad del Aire – AQI Calculadora | CalcToWork",
               "Calcula el Índice de Calidad del Aire (AQI) a partir de la concentración de contaminantes. Ejemplo: PM2.5=35 µg/m³ → AQI=100 (Moderado). Gratis."),
        "en": ("Air Quality Index Calculator – AQI from Pollutant Levels | CalcToWork",
               "Calculate Air Quality Index (AQI) from pollutant concentrations. Example: PM2.5=35 µg/m³ → AQI=100 (Moderate). Free and instant calculator."),
        "fr": ("Indice de Qualité de l'Air – Calculateur AQI | CalcToWork",
               "Calculez l'Indice de Qualité de l'Air (IQA) à partir des concentrations de polluants. Exemple: PM2.5=35 µg/m³ → AQI=100. Gratuit."),
        "pt": ("Índice de Qualidade do Ar – Calculadora AQI | CalcToWork",
               "Calcule o Índice de Qualidade do Ar (IQA) a partir das concentrações de poluentes. Exemplo: PM2.5=35 µg/m³ → AQI=100. Grátis."),
        "de": ("Luftqualitätsindex – AQI Rechner | CalcToWork",
               "Berechne den Luftqualitätsindex (AQI) aus Schadstoffkonzentrationen. Beispiel: PM2.5=35 µg/m³ → AQI=100 (Moderat). Kostenloser Rechner."),
        "it": ("Indice di Qualità dell'Aria – Calcolatore AQI | CalcToWork",
               "Calcola l'Indice di Qualità dell'Aria (AQI) dalle concentrazioni di inquinanti. Esempio: PM2.5=35 µg/m³ → AQI=100. Gratuito."),
    },
    "1025": {
        "es": ("Duración del Día – Calculadora de Horas de Luz Solar | CalcToWork",
               "Calcula las horas de luz solar según latitud y día del año. Ejemplo: Madrid, 21 de junio → 14 h 53 min de luz. Calculadora gratuita e instantánea."),
        "en": ("Day Length Calculator – Daylight Hours by Latitude | CalcToWork",
               "Calculate daylight hours based on latitude and day of year. Example: Madrid, June 21 → 14 h 53 min of sunlight. Free and instant calculator."),
        "fr": ("Durée du Jour – Calculateur d'Heures d'Ensoleillement | CalcToWork",
               "Calculez les heures de lumière solaire selon la latitude et le jour de l'année. Exemple: Paris, 21 juin → 16 h de lumière. Calculateur gratuit."),
        "pt": ("Duração do Dia – Calculadora de Horas de Luz Solar | CalcToWork",
               "Calcule as horas de luz solar por latitude e dia do ano. Exemplo: Lisboa, 21 de junho → 14 h 45 min de luz. Calculadora gratuita."),
        "de": ("Tageslänge – Rechner für Sonnenstunden | CalcToWork",
               "Berechne die Tageslänge nach Breitengrad und Tag des Jahres. Beispiel: Berlin, 21. Juni → 16 h 42 min Tageslicht. Kostenloser Rechner."),
        "it": ("Durata del Giorno – Calcolatore delle Ore di Luce Solare | CalcToWork",
               "Calcola le ore di luce solare in base a latitudine e giorno dell'anno. Esempio: Roma, 21 giugno → 14 h 58 min di luce. Gratuito."),
    },
    "1026": {
        "es": ("Tiempo de Exposición UV – Calculadora de Rayos UV | CalcToWork",
               "Calcula el tiempo seguro de exposición solar según índice UV y tipo de piel. Ejemplo: UV=8, piel clara → máximo 15 minutos. Gratis e instantáneo."),
        "en": ("UV Exposure Time Calculator – Safe Sun Exposure | CalcToWork",
               "Calculate safe sun exposure time based on UV index and skin type. Example: UV=8, fair skin → max 15 minutes. Free and instant calculator."),
        "fr": ("Temps d'Exposition UV – Calculateur de Rayons UV | CalcToWork",
               "Calculez le temps d'exposition solaire sûre selon l'indice UV et le type de peau. Exemple: UV=8, peau claire → max 15 min. Gratuit."),
        "pt": ("Tempo de Exposição UV – Calculadora de Raios UV | CalcToWork",
               "Calcule o tempo seguro de exposição solar segundo índice UV e tipo de pele. Exemplo: UV=8, pele clara → máximo 15 minutos. Grátis."),
        "de": ("UV-Expositionszeit – Rechner für sichere Sonneneinstrahlung | CalcToWork",
               "Berechne die sichere Sonnenexposition nach UV-Index und Hauttyp. Beispiel: UV=8, helle Haut → max. 15 Minuten. Kostenloser Rechner."),
        "it": ("Tempo di Esposizione UV – Calcolatore Raggi UV | CalcToWork",
               "Calcola il tempo sicuro di esposizione solare in base all'indice UV e al tipo di pelle. Esempio: UV=8, pelle chiara → max 15 min. Gratuito."),
    },
    "1027": {
        "es": ("Altitud por Presión – Calculadora de Altitud Barométrica | CalcToWork",
               "Calcula la altitud a partir de la presión atmosférica. Fórmula barométrica estándar. Ejemplo: 850 hPa → altitud ≈ 1457 m. Gratis e instantáneo."),
        "en": ("Altitude from Pressure – Barometric Altitude Calculator | CalcToWork",
               "Calculate altitude from atmospheric pressure using the barometric formula. Example: 850 hPa → altitude ≈ 1457 m. Free and instant calculator."),
        "fr": ("Altitude par Pression – Calculateur Barométrique | CalcToWork",
               "Calculez l'altitude à partir de la pression atmosphérique. Formule barométrique. Exemple: 850 hPa → altitude ≈ 1457 m. Calculateur gratuit."),
        "pt": ("Altitude pela Pressão – Calculadora Barométrica | CalcToWork",
               "Calcule a altitude a partir da pressão atmosférica. Fórmula barométrica padrão. Exemplo: 850 hPa → altitude ≈ 1457 m. Grátis."),
        "de": ("Höhe aus Luftdruck – Barometrischer Höhenrechner | CalcToWork",
               "Berechne die Höhe aus dem Luftdruck mit der barometrischen Höhenformel. Beispiel: 850 hPa → Höhe ≈ 1457 m. Kostenloser Rechner."),
        "it": ("Altitudine dalla Pressione – Calcolatore Barometrico | CalcToWork",
               "Calcola l'altitudine dalla pressione atmosferica. Formula barometrica. Esempio: 850 hPa → altitudine ≈ 1457 m. Gratuito e immediato."),
    },
    "1028": {
        "es": ("Volumen de Lluvia – Calculadora de Agua Recogida | CalcToWork",
               "Calcula el volumen de agua recogida en una superficie. Fórmula: V = precipitación(mm) × área(m²). Ejemplo: 20 mm en 50 m² → 1000 L. Gratis."),
        "en": ("Rainfall Volume Calculator – Water Collection | CalcToWork",
               "Calculate rainwater volume collected on a surface. Formula: V = rainfall(mm) × area(m²). Example: 20 mm on 50 m² → 1000 L. Free calculator."),
        "fr": ("Volume de Pluie – Calculateur de Collecte d'Eau | CalcToWork",
               "Calculez le volume d'eau de pluie collecté sur une surface. Formule: V = pluie(mm) × surface(m²). Exemple: 20 mm sur 50 m² → 1000 L."),
        "pt": ("Volume de Chuva – Calculadora de Água Recolhida | CalcToWork",
               "Calcule o volume de água de chuva recolhido numa superfície. Fórmula: V = precipitação(mm) × área(m²). Exemplo: 20 mm em 50 m² → 1000 L."),
        "de": ("Regenvolumen – Rechner für gesammeltes Regenwasser | CalcToWork",
               "Berechne das gesammelte Regenwasser auf einer Fläche. Formel: V = Niederschlag(mm) × Fläche(m²). Beispiel: 20 mm auf 50 m² → 1000 L."),
        "it": ("Volume di Pioggia – Calcolatore di Acqua Raccolta | CalcToWork",
               "Calcola il volume di acqua piovana raccolta su una superficie. Formula: V = pioggia(mm) × area(m²). Esempio: 20 mm su 50 m² → 1000 L."),
    },
    "1029": {
        "es": ("Evapotranspiración – Calculadora de Agua para Riego | CalcToWork",
               "Calcula la evapotranspiración de referencia (ETo) para planificar el riego. Método Hargreaves simplificado. Gratis e instantáneo para ingenieros agrícolas."),
        "en": ("Evapotranspiration Calculator – Irrigation Water Demand | CalcToWork",
               "Calculate reference evapotranspiration (ETo) to plan irrigation needs. Simplified Hargreaves method. Free and instant for agronomists and farmers."),
        "fr": ("Évapotranspiration – Calculateur de Besoins en Irrigation | CalcToWork",
               "Calculez l'évapotranspiration de référence (ETo) pour planifier l'irrigation. Méthode Hargreaves simplifiée. Gratuit et instantané."),
        "pt": ("Evapotranspiração – Calculadora de Necessidades de Rega | CalcToWork",
               "Calcule a evapotranspiração de referência (ETo) para planear a rega. Método Hargreaves simplificado. Grátis e instantâneo."),
        "de": ("Evapotranspiration – Rechner für Bewässerungsbedarf | CalcToWork",
               "Berechne die Referenz-Evapotranspiration (ETo) zur Bewässerungsplanung. Vereinfachte Hargreaves-Methode. Kostenloser Rechner."),
        "it": ("Evapotraspirazione – Calcolatore di Fabbisogno Irriguo | CalcToWork",
               "Calcola l'evapotraspirazione di riferimento (ETo) per pianificare l'irrigazione. Metodo Hargreaves semplificato. Gratuito e immediato."),
    },
    "1030": {
        "es": ("Día del Año – Calculadora de Número de Día | CalcToWork",
               "Calcula el número de día del año (1–366) para cualquier fecha. Ejemplo: 15 de marzo → día 74 (año no bisiesto) o día 75 (bisiesto). Gratis."),
        "en": ("Day of Year Calculator – Day Number for Any Date | CalcToWork",
               "Calculate the day of year number (1–366) for any date. Example: March 15 → day 74 (non-leap) or day 75 (leap year). Free and instant."),
        "fr": ("Jour de l'Année – Calculateur de Numéro de Jour | CalcToWork",
               "Calculez le numéro du jour de l'année (1–366) pour toute date. Exemple: 15 mars → jour 74 (non bissextile) ou 75 (bissextile). Gratuit."),
        "pt": ("Dia do Ano – Calculadora de Número de Dia | CalcToWork",
               "Calcule o número do dia do ano (1–366) para qualquer data. Exemplo: 15 de março → dia 74 (ano normal) ou dia 75 (bissexto). Grátis."),
        "de": ("Tag des Jahres – Rechner für Tagnummer | CalcToWork",
               "Berechne die Tagnummer im Jahr (1–366) für jedes Datum. Beispiel: 15. März → Tag 74 (kein Schaltjahr) oder Tag 75 (Schaltjahr). Kostenlos."),
        "it": ("Giorno dell'Anno – Calcolatore del Numero di Giorno | CalcToWork",
               "Calcola il numero del giorno dell'anno (1–366) per qualsiasi data. Esempio: 15 marzo → giorno 74 (non bisestile) o 75 (bisestile). Gratuito."),
    },
    "1031": {
        "es": ("Número de Semana – Calculadora ISO 8601 | CalcToWork",
               "Calcula el número de semana ISO 8601 para cualquier fecha. Ejemplo: 15 de marzo de 2025 → semana 11. Calculadora gratuita e instantánea."),
        "en": ("Week Number Calculator – ISO 8601 | CalcToWork",
               "Calculate the ISO 8601 week number for any date. Example: March 15, 2025 → week 11. Free and instant week number calculator."),
        "fr": ("Numéro de Semaine – Calculateur ISO 8601 | CalcToWork",
               "Calculez le numéro de semaine ISO 8601 pour toute date. Exemple: 15 mars 2025 → semaine 11. Calculateur gratuit et instantané."),
        "pt": ("Número de Semana – Calculadora ISO 8601 | CalcToWork",
               "Calcule o número de semana ISO 8601 para qualquer data. Exemplo: 15 de março de 2025 → semana 11. Calculadora gratuita e instantânea."),
        "de": ("Wochennummer – ISO 8601 Rechner | CalcToWork",
               "Berechne die ISO-8601-Wochennummer für jedes Datum. Beispiel: 15. März 2025 → Woche 11. Kostenloser und sofortiger Rechner."),
        "it": ("Numero di Settimana – Calcolatore ISO 8601 | CalcToWork",
               "Calcola il numero di settimana ISO 8601 per qualsiasi data. Esempio: 15 marzo 2025 → settimana 11. Calcolatore gratuito e immediato."),
    },
    "1032": {
        "es": ("Edad en Días – Calculadora de Días Vividos | CalcToWork",
               "Calcula cuántos días llevas vivo o la diferencia en días entre dos fechas. Ejemplo: nacido el 01/01/1990 → más de 12.000 días vividos. Gratis."),
        "en": ("Age in Days Calculator – Days Lived Since Birth | CalcToWork",
               "Calculate how many days you have been alive or the difference between two dates. Example: born Jan 1, 1990 → over 12,000 days lived. Free."),
        "fr": ("Âge en Jours – Calculateur de Jours Vécus | CalcToWork",
               "Calculez combien de jours vous avez vécu ou la différence entre deux dates. Exemple: né le 01/01/1990 → plus de 12.000 jours vécus. Gratuit."),
        "pt": ("Idade em Dias – Calculadora de Dias Vividos | CalcToWork",
               "Calcule quantos dias você viveu ou a diferença em dias entre duas datas. Exemplo: nascido em 01/01/1990 → mais de 12.000 dias. Grátis."),
        "de": ("Alter in Tagen – Rechner für gelebte Tage | CalcToWork",
               "Berechne, wie viele Tage du gelebt hast oder die Differenz zwischen zwei Daten. Beispiel: geboren am 01.01.1990 → über 12.000 Tage. Kostenlos."),
        "it": ("Età in Giorni – Calcolatore dei Giorni Vissuti | CalcToWork",
               "Calcola quanti giorni hai vissuto o la differenza tra due date. Esempio: nato il 01/01/1990 → oltre 12.000 giorni vissuti. Gratuito."),
    },
    "1033": {
        "es": ("Tiempo de Lectura – Calculadora de Minutos por Texto | CalcToWork",
               "Estima el tiempo de lectura de un texto según el número de palabras. Velocidad promedio: 200-250 palabras/minuto. Ejemplo: 1000 palabras → 4-5 min."),
        "en": ("Reading Time Calculator – Minutes per Text | CalcToWork",
               "Estimate reading time for a text based on word count. Average reading speed: 200-250 words/minute. Example: 1000 words → 4-5 min. Free."),
        "fr": ("Temps de Lecture – Calculateur de Minutes par Texte | CalcToWork",
               "Estimez le temps de lecture d'un texte selon le nombre de mots. Vitesse moyenne: 200-250 mots/minute. Exemple: 1000 mots → 4-5 min. Gratuit."),
        "pt": ("Tempo de Leitura – Calculadora de Minutos por Texto | CalcToWork",
               "Estime o tempo de leitura de um texto pelo número de palavras. Velocidade média: 200-250 palavras/minuto. Exemplo: 1000 palavras → 4-5 min."),
        "de": ("Lesezeit – Rechner für Minuten pro Text | CalcToWork",
               "Schätze die Lesezeit eines Textes anhand der Wörteranzahl. Durchschnittliche Lesegeschwindigkeit: 200-250 Wörter/Minute. Kostenloser Rechner."),
        "it": ("Tempo di Lettura – Calcolatore di Minuti per Testo | CalcToWork",
               "Stima il tempo di lettura di un testo in base al numero di parole. Velocità media: 200-250 parole/minuto. Esempio: 1000 parole → 4-5 min."),
    },
    "1034": {
        "es": ("Generador de Contraseñas – Segura y Aleatoria | CalcToWork",
               "Genera contraseñas seguras y aleatorias con letras, números y símbolos. Configura longitud y tipo de caracteres. Sin registro, 100% privado. Gratis."),
        "en": ("Password Generator – Secure & Random | CalcToWork",
               "Generate strong random passwords with letters, numbers, and symbols. Configure length and character types. No signup, 100% private. Free."),
        "fr": ("Générateur de Mots de Passe – Sécurisé et Aléatoire | CalcToWork",
               "Générez des mots de passe forts et aléatoires avec lettres, chiffres et symboles. Configurez la longueur et les types de caractères. Gratuit."),
        "pt": ("Gerador de Senhas – Segura e Aleatória | CalcToWork",
               "Gere senhas fortes e aleatórias com letras, números e símbolos. Configure comprimento e tipo de caracteres. Sem registo, 100% privado. Grátis."),
        "de": ("Passwort-Generator – Sicher und Zufällig | CalcToWork",
               "Generiere starke, zufällige Passwörter mit Buchstaben, Zahlen und Symbolen. Konfiguriere Länge und Zeichentypen. Kein Anmeldung, 100% privat."),
        "it": ("Generatore di Password – Sicura e Casuale | CalcToWork",
               "Genera password sicure e casuali con lettere, numeri e simboli. Configura lunghezza e tipi di caratteri. Senza registrazione, 100% privato."),
    },
    "1035": {
        "es": ("Número Aleatorio – Generador entre Mínimo y Máximo | CalcToWork",
               "Genera un número entero o decimal aleatorio entre dos valores. Ejemplo: mínimo 1, máximo 100 → genera 47. Calculadora gratuita e instantánea."),
        "en": ("Random Number Generator – Between Min and Max | CalcToWork",
               "Generate a random integer or decimal between two values. Example: min 1, max 100 → generates 47. Free and instant random number generator."),
        "fr": ("Générateur de Nombre Aléatoire – Entre Min et Max | CalcToWork",
               "Générez un nombre entier ou décimal aléatoire entre deux valeurs. Exemple: min 1, max 100 → génère 47. Générateur gratuit et instantané."),
        "pt": ("Número Aleatório – Gerador entre Mínimo e Máximo | CalcToWork",
               "Gere um número inteiro ou decimal aleatório entre dois valores. Exemplo: mínimo 1, máximo 100 → gera 47. Calculadora gratuita e instantânea."),
        "de": ("Zufallszahlen-Generator – Zwischen Min und Max | CalcToWork",
               "Generiere eine zufällige ganze oder Dezimalzahl zwischen zwei Werten. Beispiel: min 1, max 100 → erzeugt 47. Kostenloser Zufallszahlengenerator."),
        "it": ("Generatore di Numeri Casuali – Tra Min e Max | CalcToWork",
               "Genera un numero intero o decimale casuale tra due valori. Esempio: min 1, max 100 → genera 47. Generatore gratuito e immediato."),
    },
    "1036": {
        "es": ("Lanzador de Dados – Simulador de 1 a 6 Dados | CalcToWork",
               "Simula el lanzamiento de 1 a 6 dados de 4, 6, 8, 10, 12 o 20 caras. Resultado instantáneo. Perfecto para juegos de rol y mesa. Gratis."),
        "en": ("Dice Roller – 1 to 6 Dice Simulator | CalcToWork",
               "Simulate rolling 1 to 6 dice with 4, 6, 8, 10, 12, or 20 sides. Instant results. Perfect for tabletop RPGs and board games. Free."),
        "fr": ("Lanceur de Dés – Simulateur de 1 à 6 Dés | CalcToWork",
               "Simulez le lancer de 1 à 6 dés à 4, 6, 8, 10, 12 ou 20 faces. Résultat instantané. Parfait pour les jeux de rôle et de plateau. Gratuit."),
        "pt": ("Lançador de Dados – Simulador de 1 a 6 Dados | CalcToWork",
               "Simule o lançamento de 1 a 6 dados de 4, 6, 8, 10, 12 ou 20 faces. Resultado instantâneo. Perfeito para RPG e jogos de tabuleiro. Grátis."),
        "de": ("Würfelwurf-Simulator – 1 bis 6 Würfel | CalcToWork",
               "Simuliere das Würfeln mit 1 bis 6 Würfeln mit 4, 6, 8, 10, 12 oder 20 Seiten. Sofortiges Ergebnis. Ideal für Rollenspiele und Brettspiele."),
        "it": ("Lancio di Dadi – Simulatore da 1 a 6 Dadi | CalcToWork",
               "Simula il lancio di 1-6 dadi a 4, 6, 8, 10, 12 o 20 facce. Risultato immediato. Perfetto per giochi di ruolo e da tavolo. Gratuito."),
    },
    "1037": {
        "es": ("Lanzar Moneda – Simulador de Cara o Cruz | CalcToWork",
               "Simula el lanzamiento de una moneda para obtener cara o cruz de forma aleatoria. Estadísticas acumuladas. Gratis e instantáneo. Sin registro."),
        "en": ("Coin Flip Simulator – Heads or Tails | CalcToWork",
               "Simulate a coin toss to get heads or tails randomly. Cumulative statistics. Free and instant. No registration needed."),
        "fr": ("Lancer une Pièce – Simulateur Pile ou Face | CalcToWork",
               "Simulez le lancer d'une pièce pour obtenir pile ou face de manière aléatoire. Statistiques cumulées. Gratuit et instantané. Sans inscription."),
        "pt": ("Lançar Moeda – Simulador de Cara ou Coroa | CalcToWork",
               "Simule o lançamento de uma moeda para obter cara ou coroa aleatoriamente. Estatísticas acumuladas. Grátis e instantâneo. Sem registo."),
        "de": ("Münzwurf-Simulator – Kopf oder Zahl | CalcToWork",
               "Simuliere einen Münzwurf für Kopf oder Zahl nach dem Zufallsprinzip. Kumulative Statistiken. Kostenlos und sofort. Keine Anmeldung erforderlich."),
        "it": ("Lancio della Moneta – Simulatore Testa o Croce | CalcToWork",
               "Simula il lancio di una moneta per ottenere testa o croce casualmente. Statistiche cumulative. Gratuito e immediato. Senza registrazione."),
    },
    "1038": {
        "es": ("Hex a RGB – Conversor de Color Hexadecimal a RGB | CalcToWork",
               "Convierte colores hexadecimales a valores RGB al instante. Ejemplo: #FF5733 → R=255, G=87, B=51. Perfecto para diseño web y CSS. Gratis."),
        "en": ("Hex to RGB Color Converter – Hexadecimal to RGB | CalcToWork",
               "Convert hexadecimal colors to RGB values instantly. Example: #FF5733 → R=255, G=87, B=51. Perfect for web design and CSS. Free."),
        "fr": ("Convertisseur Hex en RGB – Couleur Hexadécimale en RGB | CalcToWork",
               "Convertissez les couleurs hexadécimales en valeurs RGB instantanément. Exemple: #FF5733 → R=255, G=87, B=51. Pour design web et CSS. Gratuit."),
        "pt": ("Hex para RGB – Conversor de Cor Hexadecimal para RGB | CalcToWork",
               "Converta cores hexadecimais para valores RGB instantaneamente. Exemplo: #FF5733 → R=255, G=87, B=51. Perfeito para design web e CSS. Grátis."),
        "de": ("Hex zu RGB – Farbkonverter Hexadezimal zu RGB | CalcToWork",
               "Konvertiere Hex-Farben sofort in RGB-Werte. Beispiel: #FF5733 → R=255, G=87, B=51. Perfekt für Webdesign und CSS. Kostenloser Rechner."),
        "it": ("Da Hex a RGB – Convertitore Colore Esadecimale | CalcToWork",
               "Converti colori esadecimali in valori RGB istantaneamente. Esempio: #FF5733 → R=255, G=87, B=51. Perfetto per web design e CSS. Gratuito."),
    },
    "1039": {
        "es": ("Valor de Exposición – Calculadora EV Fotografía | CalcToWork",
               "Calcula el Valor de Exposición (EV) a partir de apertura, velocidad e ISO. Ejemplo: f/4, 1/250 s, ISO 100 → EV=13. Gratis para fotógrafos."),
        "en": ("Exposure Value Calculator – Photography EV | CalcToWork",
               "Calculate Exposure Value (EV) from aperture, shutter speed, and ISO. Example: f/4, 1/250s, ISO 100 → EV=13. Free calculator for photographers."),
        "fr": ("Valeur d'Exposition – Calculateur EV Photographie | CalcToWork",
               "Calculez la Valeur d'Exposition (EV) à partir de l'ouverture, la vitesse et l'ISO. Exemple: f/4, 1/250 s, ISO 100 → EV=13. Gratuit."),
        "pt": ("Valor de Exposição – Calculadora EV Fotografia | CalcToWork",
               "Calcule o Valor de Exposição (EV) a partir de abertura, velocidade e ISO. Exemplo: f/4, 1/250 s, ISO 100 → EV=13. Grátis para fotógrafos."),
        "de": ("Belichtungswert – EV-Rechner für Fotografie | CalcToWork",
               "Berechne den Belichtungswert (EV) aus Blende, Verschlusszeit und ISO. Beispiel: f/4, 1/250 s, ISO 100 → EV=13. Kostenloser Fotorechner."),
        "it": ("Valore di Esposizione – Calcolatore EV Fotografia | CalcToWork",
               "Calcola il Valore di Esposizione (EV) da apertura, tempo e ISO. Esempio: f/4, 1/250 s, ISO 100 → EV=13. Gratuito per fotografi."),
    },
    "1040": {
        "es": ("Profundidad de Campo – Calculadora DoF Fotografía | CalcToWork",
               "Calcula la profundidad de campo (DoF) según focal, apertura, distancia y sensor. Ejemplo: 50mm, f/2.8, 3m, Full Frame → DoF=0.42 m. Gratis."),
        "en": ("Depth of Field Calculator – Photography DoF | CalcToWork",
               "Calculate depth of field (DoF) from focal length, aperture, distance, and sensor. Example: 50mm, f/2.8, 3m, Full Frame → DoF=0.42 m. Free."),
        "fr": ("Profondeur de Champ – Calculateur DoF Photographie | CalcToWork",
               "Calculez la profondeur de champ (DoF) selon focale, ouverture, distance et capteur. Exemple: 50mm, f/2.8, 3m → DoF=0.42 m. Gratuit."),
        "pt": ("Profundidade de Campo – Calculadora DoF Fotografia | CalcToWork",
               "Calcule a profundidade de campo (DoF) por focal, abertura, distância e sensor. Exemplo: 50mm, f/2.8, 3m, Full Frame → DoF=0.42 m. Grátis."),
        "de": ("Schärfentiefe – DoF-Rechner für Fotografie | CalcToWork",
               "Berechne die Schärfentiefe (DoF) aus Brennweite, Blende, Abstand und Sensor. Beispiel: 50mm, f/2.8, 3m → DoF=0.42 m. Kostenlos."),
        "it": ("Profondità di Campo – Calcolatore DoF Fotografia | CalcToWork",
               "Calcola la profondità di campo (DoF) da focale, apertura, distanza e sensore. Esempio: 50mm, f/2.8, 3m → DoF=0.42 m. Gratuito."),
    },
    "1041": {
        "es": ("Distancia Hiperfocal – Calculadora de Foco Máximo | CalcToWork",
               "Calcula la distancia hiperfocal para maximizar la nitidez desde la mitad hasta el infinito. Ejemplo: 35mm, f/8, CoC=0.029mm → H=5.3 m. Gratis."),
        "en": ("Hyperfocal Distance Calculator – Maximum Focus Range | CalcToWork",
               "Calculate hyperfocal distance to maximize sharpness from half H to infinity. Example: 35mm, f/8, CoC=0.029mm → H=5.3 m. Free calculator."),
        "fr": ("Distance Hyperfocale – Calculateur de Mise au Point Maximale | CalcToWork",
               "Calculez la distance hyperfocale pour maximiser la netteté jusqu'à l'infini. Exemple: 35mm, f/8 → H=5.3 m. Calculateur gratuit pour photographes."),
        "pt": ("Distância Hiperfocal – Calculadora de Foco Máximo | CalcToWork",
               "Calcule a distância hiperfocal para maximizar a nitidez até ao infinito. Exemplo: 35mm, f/8, CoC=0.029mm → H=5.3 m. Grátis para fotógrafos."),
        "de": ("Hyperfokaldistanz – Rechner für maximale Schärfe | CalcToWork",
               "Berechne die Hyperfokaldistanz für maximale Schärfe bis Unendlich. Beispiel: 35mm, f/8, CoC=0.029mm → H=5.3 m. Kostenloser Fotorechner."),
        "it": ("Distanza Iperfocale – Calcolatore di Messa a Fuoco Massima | CalcToWork",
               "Calcola la distanza iperfocale per massimizzare la nitidezza fino all'infinito. Esempio: 35mm, f/8 → H=5.3 m. Gratuito per fotografi."),
    },
    "1042": {
        "es": ("Suma de Decibelios – Calculadora de Nivel Sonoro | CalcToWork",
               "Suma dos o más fuentes sonoras en decibelios. Fórmula: dB_total = 10 log₁₀(10^(dB1/10) + 10^(dB2/10)). Ejemplo: 70 dB + 70 dB → 73 dB. Gratis."),
        "en": ("Decibel Sum Calculator – Sound Level Addition | CalcToWork",
               "Add two or more sound sources in decibels. Formula: dBtotal = 10 log₁₀(10^(dB1/10) + 10^(dB2/10)). Example: 70+70 dB → 73 dB. Free."),
        "fr": ("Calculateur de Somme de Décibels – Niveau Sonore | CalcToWork",
               "Additionnez deux sources sonores en décibels. Formule: dBtotal = 10 log₁₀(10^(dB1/10) + 10^(dB2/10)). Exemple: 70+70 dB → 73 dB. Gratuit."),
        "pt": ("Soma de Decibéis – Calculadora de Nível Sonoro | CalcToWork",
               "Some duas ou mais fontes sonoras em decibéis. Fórmula: dBtotal = 10 log₁₀(10^(dB1/10) + 10^(dB2/10)). Exemplo: 70+70 dB → 73 dB. Grátis."),
        "de": ("Dezibel-Addition – Rechner für Schallpegel | CalcToWork",
               "Addiere zwei Schallquellen in Dezibel. Formel: dBges = 10 log₁₀(10^(dB1/10) + 10^(dB2/10)). Beispiel: 70+70 dB → 73 dB. Kostenloser Rechner."),
        "it": ("Somma di Decibel – Calcolatore di Livello Sonoro | CalcToWork",
               "Somma due o più sorgenti sonore in decibel. Formula: dBtot = 10 log₁₀(10^(dB1/10) + 10^(dB2/10)). Esempio: 70+70 dB → 73 dB. Gratuito."),
    },
    "1043": {
        "es": ("Nivel Sonoro a Distancia – Ley del Inverso del Cuadrado | CalcToWork",
               "Calcula el nivel de sonido a diferentes distancias. Fórmula: L2 = L1 − 20 log₁₀(d2/d1). Ejemplo: 90 dB a 1 m → 70 dB a 10 m. Gratis."),
        "en": ("Sound Level at Distance – Inverse Square Law | CalcToWork",
               "Calculate sound level at different distances. Formula: L2 = L1 − 20 log₁₀(d2/d1). Example: 90 dB at 1 m → 70 dB at 10 m. Free."),
        "fr": ("Niveau Sonore à Distance – Loi du Carré Inverse | CalcToWork",
               "Calculez le niveau sonore à différentes distances. Formule: L2 = L1 − 20 log₁₀(d2/d1). Exemple: 90 dB à 1 m → 70 dB à 10 m. Gratuit."),
        "pt": ("Nível Sonoro à Distância – Lei do Inverso do Quadrado | CalcToWork",
               "Calcule o nível sonoro a diferentes distâncias. Fórmula: L2 = L1 − 20 log₁₀(d2/d1). Exemplo: 90 dB a 1 m → 70 dB a 10 m. Grátis."),
        "de": ("Schallpegel auf Abstand – Abstandsgesetz | CalcToWork",
               "Berechne den Schallpegel in verschiedenen Entfernungen. Formel: L2 = L1 − 20 log₁₀(d2/d1). Beispiel: 90 dB bei 1 m → 70 dB bei 10 m. Kostenlos."),
        "it": ("Livello Sonoro a Distanza – Legge del Quadrato Inverso | CalcToWork",
               "Calcola il livello sonoro a diverse distanze. Formula: L2 = L1 − 20 log₁₀(d2/d1). Esempio: 90 dB a 1 m → 70 dB a 10 m. Gratuito."),
    },
    "1044": {
        "es": ("Relación de Contraste – Calculadora para Pantallas | CalcToWork",
               "Calcula la relación de contraste entre la luminosidad más clara y más oscura de una pantalla. Ejemplo: 500 cd/m² blanco, 0.5 cd/m² negro → 1000:1. Gratis."),
        "en": ("Contrast Ratio Calculator – Display & Screen | CalcToWork",
               "Calculate contrast ratio between the brightest and darkest luminance of a display. Example: 500 cd/m² white, 0.5 cd/m² black → 1000:1. Free."),
        "fr": ("Rapport de Contraste – Calculateur pour Écrans | CalcToWork",
               "Calculez le rapport de contraste entre la luminosité maximale et minimale d'un écran. Exemple: 500 cd/m² blanc, 0.5 cd/m² noir → 1000:1. Gratuit."),
        "pt": ("Relação de Contraste – Calculadora para Ecrãs | CalcToWork",
               "Calcule a relação de contraste entre a luminosidade máxima e mínima de um ecrã. Exemplo: 500 cd/m² branco, 0.5 cd/m² preto → 1000:1. Grátis."),
        "de": ("Kontrastverhältnis – Rechner für Monitore | CalcToWork",
               "Berechne das Kontrastverhältnis zwischen der hellsten und dunkelsten Leuchtdichte. Beispiel: 500 cd/m² weiß, 0.5 cd/m² schwarz → 1000:1. Kostenlos."),
        "it": ("Rapporto di Contrasto – Calcolatore per Schermi | CalcToWork",
               "Calcola il rapporto di contrasto tra luminosità massima e minima di uno schermo. Esempio: 500 cd/m² bianco, 0.5 cd/m² nero → 1000:1. Gratuito."),
    },
    "1045": {
        "es": ("Componente de Viento Cruzado – Calculadora Aviación | CalcToWork",
               "Calcula el componente de viento cruzado y de frente para despegue/aterrizaje. Fórmula: XW = viento × sin(ángulo). Ejemplo: 15 kt, 30° → XW=7.5 kt. Gratis."),
        "en": ("Crosswind Component Calculator – Aviation | CalcToWork",
               "Calculate crosswind and headwind components for takeoff/landing. Formula: XW = wind × sin(angle). Example: 15 kt, 30° → XW=7.5 kt. Free."),
        "fr": ("Composante de Vent de Travers – Calculateur Aviation | CalcToWork",
               "Calculez les composantes de vent de travers et de face pour décollage/atterrissage. Formule: XW = vent × sin(angle). Exemple: 15 kt, 30° → XW=7.5 kt."),
        "pt": ("Componente de Vento Cruzado – Calculadora Aviação | CalcToWork",
               "Calcule o componente de vento cruzado e de frente para descolagem/aterragem. Fórmula: XW = vento × sin(ângulo). Exemplo: 15 kt, 30° → XW=7.5 kt."),
        "de": ("Seitenwindkomponente – Rechner für Luftfahrt | CalcToWork",
               "Berechne die Seiten- und Gegenwindkomponente für Start/Landung. Formel: QW = Wind × sin(Winkel). Beispiel: 15 kt, 30° → QW=7.5 kt. Kostenlos."),
        "it": ("Componente di Vento Traverso – Calcolatore Aviazione | CalcToWork",
               "Calcola le componenti di vento traverso e frontale per decollo/atterraggio. Formula: XW = vento × sin(angolo). Esempio: 15 kt, 30° → XW=7.5 kt."),
    },
    "1046": {
        "es": ("Consumo de Combustible – Calculadora L/100 km y MPG | CalcToWork",
               "Calcula el consumo de combustible en L/100 km o millas por galón (MPG). Ejemplo: 500 km con 40 L → 8 L/100 km = 29.4 MPG. Gratis e instantáneo."),
        "en": ("Fuel Consumption Calculator – L/100 km & MPG | CalcToWork",
               "Calculate fuel consumption in L/100 km or miles per gallon (MPG). Example: 500 km with 40 L → 8 L/100 km = 29.4 MPG. Free and instant."),
        "fr": ("Consommation de Carburant – Calculateur L/100 km et MPG | CalcToWork",
               "Calculez la consommation de carburant en L/100 km ou miles par gallon (MPG). Exemple: 500 km avec 40 L → 8 L/100 km = 29.4 MPG. Gratuit."),
        "pt": ("Consumo de Combustível – Calculadora L/100 km e MPG | CalcToWork",
               "Calcule o consumo de combustível em L/100 km ou milhas por galão (MPG). Exemplo: 500 km com 40 L → 8 L/100 km = 29.4 MPG. Grátis."),
        "de": ("Kraftstoffverbrauch – Rechner L/100 km und MPG | CalcToWork",
               "Berechne den Kraftstoffverbrauch in L/100 km oder Meilen pro Gallone (MPG). Beispiel: 500 km mit 40 L → 8 L/100 km = 29.4 MPG. Kostenlos."),
        "it": ("Consumo di Carburante – Calcolatore L/100 km e MPG | CalcToWork",
               "Calcola il consumo di carburante in L/100 km o miglia per gallone (MPG). Esempio: 500 km con 40 L → 8 L/100 km = 29.4 MPG. Gratuito."),
    },
    "1047": {
        "es": ("Velocidad Verdadera – Calculadora TAS Aviación | CalcToWork",
               "Calcula la Velocidad Aire Verdadera (TAS) desde la velocidad indicada (IAS), altitud y temperatura. Ejemplo: IAS=150 kt, 5000 ft, ISA → TAS≈168 kt. Gratis."),
        "en": ("True Airspeed Calculator – TAS from IAS | CalcToWork",
               "Calculate True Airspeed (TAS) from Indicated Airspeed (IAS), altitude, and temperature. Example: IAS=150 kt, 5000 ft, ISA → TAS≈168 kt. Free."),
        "fr": ("Vitesse Vraie – Calculateur TAS Aviation | CalcToWork",
               "Calculez la Vitesse Vraie (TAS) à partir de la vitesse indiquée (IAS), l'altitude et la température. Exemple: IAS=150 kt, 5000 ft → TAS≈168 kt."),
        "pt": ("Velocidade Verdadeira – Calculadora TAS Aviação | CalcToWork",
               "Calcule a Velocidade Ar Verdadeira (TAS) a partir da velocidade indicada (IAS), altitude e temperatura. Exemplo: IAS=150 kt, 5000 ft → TAS≈168 kt."),
        "de": ("Wahre Fluggeschwindigkeit – TAS-Rechner für Luftfahrt | CalcToWork",
               "Berechne die wahre Fluggeschwindigkeit (TAS) aus IAS, Höhe und Temperatur. Beispiel: IAS=150 kt, 5000 ft, ISA → TAS≈168 kt. Kostenloser Rechner."),
        "it": ("Velocità Aria Vera – Calcolatore TAS Aviazione | CalcToWork",
               "Calcola la Velocità Aria Vera (TAS) da IAS, quota e temperatura. Esempio: IAS=150 kt, 5000 ft, ISA → TAS≈168 kt. Gratuito per piloti."),
    },
    "1048": {
        "es": ("Velocidad de Casco – Calculadora de Veleros y Barcos | CalcToWork",
               "Calcula la velocidad máxima teórica de un casco desplazante. Fórmula: V = 1.34 × √LWL. Ejemplo: LWL=10 m → velocidad de casco ≈ 4.4 m/s. Gratis."),
        "en": ("Hull Speed Calculator – Sailboats & Displacement Hulls | CalcToWork",
               "Calculate theoretical maximum speed for displacement hulls. Formula: V = 1.34 × √LWL. Example: LWL=10 m → hull speed ≈ 4.4 m/s. Free."),
        "fr": ("Vitesse de Coque – Calculateur pour Voiliers | CalcToWork",
               "Calculez la vitesse maximale théorique d'une coque déplaçante. Formule: V = 1.34 × √LWL. Exemple: LWL=10 m → vitesse de coque ≈ 4.4 m/s. Gratuit."),
        "pt": ("Velocidade de Casco – Calculadora para Veleiros | CalcToWork",
               "Calcule a velocidade máxima teórica de um casco deslocante. Fórmula: V = 1.34 × √LWL. Exemplo: LWL=10 m → velocidade de casco ≈ 4.4 m/s. Grátis."),
        "de": ("Rumpfgeschwindigkeit – Rechner für Segelboote | CalcToWork",
               "Berechne die theoretische Höchstgeschwindigkeit für Verdrängerrümpfe. Formel: V = 1.34 × √LWL. Beispiel: LWL=10 m → Rumpfgeschwindigkeit ≈ 4.4 m/s."),
        "it": ("Velocità di Carena – Calcolatore per Barche a Vela | CalcToWork",
               "Calcola la velocità massima teorica di uno scafo dislocante. Formula: V = 1.34 × √LWL. Esempio: LWL=10 m → velocità di carena ≈ 4.4 m/s. Gratuito."),
    },
    "1049": {
        "es": ("Distancia Ortodrómica – Calculadora de Gran Círculo | CalcToWork",
               "Calcula la distancia más corta entre dos puntos en la Tierra (gran círculo). Fórmula de Haversine. Ejemplo: Madrid–Nueva York ≈ 5,770 km. Gratis."),
        "en": ("Great-Circle Distance Calculator – Haversine Formula | CalcToWork",
               "Calculate the shortest distance between two points on Earth (great circle). Haversine formula. Example: Madrid to New York ≈ 5,770 km. Free."),
        "fr": ("Distance Orthodromique – Calculateur de Grand Cercle | CalcToWork",
               "Calculez la distance la plus courte entre deux points sur Terre (grand cercle). Formule Haversine. Exemple: Paris–New York ≈ 5,850 km. Gratuit."),
        "pt": ("Distância Ortodrômica – Calculadora de Grande Círculo | CalcToWork",
               "Calcule a distância mais curta entre dois pontos na Terra (grande círculo). Fórmula Haversine. Exemplo: Lisboa–Nova Iorque ≈ 5,430 km. Grátis."),
        "de": ("Orthodrome – Großkreisentfernung Rechner | CalcToWork",
               "Berechne die kürzeste Entfernung zwischen zwei Punkten auf der Erde. Haversine-Formel. Beispiel: Berlin–New York ≈ 6,390 km. Kostenloser Rechner."),
        "it": ("Distanza Ortodromica – Calcolatore del Grande Cerchio | CalcToWork",
               "Calcola la distanza più breve tra due punti sulla Terra. Formula Haversine. Esempio: Roma–New York ≈ 8,230 km. Calcolatore gratuito e immediato."),
    },
}


def run():
    for lang in ["es", "en", "fr", "pt", "de", "it"]:
        path = I18N / f"{lang}.json"
        with open(path, encoding="utf-8") as f:
            data = json.load(f)

        calcs = data.setdefault("calculators", {})
        updated = 0

        for cid, lang_data in SEO.items():
            if cid not in calcs:
                continue
            entry = lang_data.get(lang, lang_data.get("en"))
            if not entry:
                continue
            title, desc = entry
            calcs[cid]["seo_title"] = title
            calcs[cid]["seo_desc"] = desc
            updated += 1

        with open(path, "w", encoding="utf-8", newline="\n") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"[{lang}] {updated} calcs updated")

    print("Done.")


if __name__ == "__main__":
    run()
