"""
CalcToWork – SEO Title Optimizer
Rewrites all seo_title fields in the 6 i18n JSON files.
Rules: ≤46 chars, keyword-first, question format for quantity calculators, power words.
"""
import json
from pathlib import Path

I18N = Path(__file__).parent.parent / "src" / "i18n"

NEW_TITLES = {
    "en": {
        "001": "Concrete Calculator – Cement & Gravel",
        "002": "Reinforced Concrete Calculator – Rebar",
        "003": "Footing Calculator – Concrete & Steel",
        "004": "Retaining Wall Calculator – Concrete",
        "005": "Concrete Column Calculator – Materials",
        "006": "Concrete Beam Calculator – Volume & Steel",
        "007": "Joist Slab Calculator – Materials",
        "008": "Flat Slab Calculator – Volume & Steel",
        "009": "Strip Foundation Calculator – Concrete",
        "010": "Excavation Calculator – Volume & Trucks",
        "011": "How Many Bricks Do I Need? – Calculator",
        "012": "Face Brick Calculator – Materials & Qty",
        "013": "Concrete Block Calculator – Blocks",
        "014": "Drywall Calculator – Boards & Studs",
        "015": "Insulation Calculator – EPS & Rockwool",
        "016": "Sprayed Plaster Calculator – kg Mortar",
        "017": "Cement Mortar Calculator – Cement & Sand",
        "018": "Rendering Calculator – Cement or Gypsum",
        "019": "Stone Masonry Calculator – Stone & Mortar",
        "020": "How Many Roof Tiles Do I Need? Online",
        "021": "How Many Floor Tiles Do I Need? Online",
        "022": "Porcelain Tile Calculator – Boxes & Grout",
        "023": "Laminate Flooring Calculator – Boxes",
        "024": "Parquet Calculator – Boxes & Varnish",
        "025": "Marble & Granite Calculator – m² & Adhesive",
        "026": "Terrazzo Calculator – Pieces & Mortar",
        "027": "Wall Tile Calculator – How Many for Bath?",
        "028": "Mosaic Tile Calculator – Sheets & Adhesive",
        "029": "Tile Adhesive Calculator C1 C2 – kg",
        "030": "Tile Grout Calculator – kg per m²",
        "031": "PVC Drain Pipe Calculator – Pipes & Fittings",
        "032": "Copper & PEX Pipe Calculator – Plumbing",
        "033": "Water Pressure Calculator – Bar & PSI",
        "034": "Water Tank Calculator – Litres Required",
        "035": "Electric Water Heater Calculator – kW",
        "036": "Gas Boiler Calculator – kW for Home",
        "037": "How Many Radiator Elements Do I Need?",
        "038": "Underfloor Heating Calculator – Pipe",
        "039": "Drip Irrigation Calculator – Pipe & Drippers",
        "040": "Water Supply Pipe Sizing – Diameter DN",
        "041": "Pool Filter Calculator – Pump & Filter",
        "042": "Drain Stack Calculator – Pipe Sizing",
        "043": "Cable Size Calculator – mm² Cross-Section",
        "044": "Voltage Drop Calculator – % and Volts",
        "045": "Lumen Calculator – LED Lighting Room",
        "046": "How Many Light Points Do I Need?",
        "047": "Electrical Panel Calculator – Breakers",
        "048": "Solar Panel Calculator – kWp & Panels",
        "049": "Solar Battery Calculator – kWh & Batteries",
        "050": "Three-Phase Power Calculator – kW & kVA",
        "051": "Earthing System Calculator – Ground Rods",
        "052": "Electricity Cost Calculator – kWh & Cost",
        "053": "AC BTU Calculator – What Size Do I Need?",
        "054": "Air Duct Sizing Calculator – Diameter",
        "055": "Mechanical Ventilation Calculator – m³/h",
        "056": "Heat Pump Calculator – Air to Water kW",
        "057": "COP & EER Calculator – Efficiency Online",
        "058": "HVAC Duct Sizing – Pressure Drop Method",
        "059": "Air Grille Calculator – Size & Airflow",
        "060": "Refrigerant Charge Calculator R32 R410A",
        "061": "Window Calculator PVC Aluminium – m²",
        "062": "Interior Door Calculator – Frames & Hinges",
        "063": "Sliding Door Calculator – Track & Hardware",
        "064": "Wooden Stair Calculator – Treads & Risers",
        "065": "Metal Railing Calculator – Posts & Balusters",
        "066": "Steel Structure Calculator – Beams & Weight",
        "067": "Metal Gate Calculator – Steel Weight",
        "068": "Glass Calculator – m² & kg by Type",
        "069": "Wall Paint Calculator – Litres Required",
        "070": "Ceiling Paint Calculator – Litres",
        "071": "Enamel Paint Calculator – Wood & Metal",
        "072": "Wood Varnish Calculator – Litres",
        "073": "How Many Wallpaper Rolls Do I Need?",
        "074": "Textured Finish Calculator – kg Online",
        "075": "Primer & Sealer Calculator – Litres",
        "076": "Filler & Putty Calculator – kg to Smooth",
        "077": "Sandpaper Calculator – Sheets per m²",
        "078": "Renovation Budget Calculator – Cost per m²",
        "079": "Freelance Rate Calculator – Hourly Cost",
        "080": "Equipment Depreciation Calculator",
        "081": "Vehicle Depreciation Calculator – Cost/km",
        "082": "Fuel Cost Calculator – Site Travel",
        "083": "Freelance Daily Rate Calculator",
        "084": "Skip Hire Calculator – Price & Size",
        "085": "Scaffolding Cost Calculator – per m²",
        "086": "Final Site Clean Calculator – Hours & Cost",
        "087": "Contractor Insurance Calculator – Premium",
        "088": "PPE Cost Calculator – per Worker",
        "089": "Site Signage Calculator – Signs Online",
        "090": "Labour Productivity Calculator – m²/Day",
        "091": "Simple Construction Schedule – Weeks",
        "092": "Building Permit Calculator – Fees",
        "093": "Self-Employed Tax Calculator – VAT & Tax",
        "094": "Equipment Financing Calculator – Monthly",
        "095": "Profit Margin Calculator – % & Markup",
        "096": "Break-Even Calculator – Freelance",
        "097": "Water Consumption Calculator – Litres",
        "098": "Waste Factor Calculator – How Much to Buy",
        "099": "Labour Cost Calculator – Total for Site",
        "100": "Tool ROI Calculator – Payback Period",
    },
    "es": {
        "001": "Calculadora Hormigón – Cemento y Grava",
        "002": "Calculadora Hormigón Armado – Acero",
        "003": "Calculadora Zapata Aislada – Hormigón",
        "004": "Calculadora Muro de Contención",
        "005": "Calculadora Pilares – Hormigón y Acero",
        "006": "Calculadora Vigas Hormigón – Volumen",
        "007": "Calculadora Forjado Vigueta y Bovedilla",
        "008": "Calculadora Losa Maciza – Volumen",
        "009": "Calculadora Zapata Corrida – Hormigón",
        "010": "Calculadora Excavación – Volumen",
        "011": "¿Cuántos Ladrillos Necesito? Online",
        "012": "Calculadora Ladrillo Cara Vista",
        "013": "Calculadora Bloque Hormigón – Bloques",
        "014": "Calculadora Pladur – Placas y Perfiles",
        "015": "Calculadora Aislamiento – EPS y Lana",
        "016": "Calculadora Revoco Proyectado – kg",
        "017": "Calculadora Mortero de Cemento",
        "018": "Calculadora Enfoscado – Cemento o Yeso",
        "019": "Calculadora Mampostería – Piedra y Mortero",
        "020": "¿Cuántas Tejas Necesito? Calculadora",
        "021": "¿Cuántas Baldosas Necesito? Online",
        "022": "Calculadora Gres Porcelánico – Cajas",
        "023": "Calculadora Suelo Laminado – Cajas",
        "024": "Calculadora Parquet – Cajas y Barniz",
        "025": "Calculadora Mármol y Granito – m²",
        "026": "Calculadora Terrazo – Piezas y Mortero",
        "027": "¿Cuántos Azulejos Necesito? Online",
        "028": "Calculadora Mosaico – Mallas y Cola",
        "029": "Calculadora Cola Cerámica C1 C2 – kg",
        "030": "Calculadora Lechada – kg por m²",
        "031": "Calculadora Tubería PVC – Evacuación",
        "032": "Calculadora Tuberías Cobre PEX",
        "033": "Calculadora Presión de Agua – Bar y PSI",
        "034": "Calculadora Depósito de Agua – Litros",
        "035": "Calculadora Calentador Eléctrico – kW",
        "036": "Calculadora Caldera Gas – kW",
        "037": "¿Cuántos Elementos de Radiador Necesito?",
        "038": "Calculadora Suelo Radiante – Tubería",
        "039": "Calculadora Riego Goteo – Tuberías",
        "040": "Calculadora Tuberías Fontanería – DN",
        "041": "Calculadora Filtro Piscina – Bomba",
        "042": "Calculadora Bajante – Dimensionado",
        "043": "Calculadora Sección Cable – mm²",
        "044": "Calculadora Caída de Tensión – %",
        "045": "Calculadora Lúmenes LED – Iluminación",
        "046": "¿Cuántos Puntos de Luz Necesito?",
        "047": "Calculadora Cuadro Eléctrico – ICP",
        "048": "Calculadora Paneles Solares – kWp",
        "049": "Calculadora Baterías Solares – kWh",
        "050": "Calculadora Trifásica – kW y kVA",
        "051": "Calculadora Puesta a Tierra – Hastes",
        "052": "Calculadora Consumo Eléctrico – kWh",
        "053": "Calculadora Aire Acondicionado BTU",
        "054": "Calculadora Conductos Aire – Diámetro",
        "055": "Calculadora Ventilación Mecánica – m³/h",
        "056": "Calculadora Bomba de Calor – kW",
        "057": "Calculadora COP y EER – Eficiencia",
        "058": "Dimensionado Conductos HVAC",
        "059": "Calculadora Rejillas Ventilación",
        "060": "Calculadora Gas Refrigerante R32 R410A",
        "061": "Calculadora Ventanas PVC Aluminio",
        "062": "Calculadora Puertas Interior",
        "063": "Calculadora Puertas Correderas",
        "064": "Calculadora Escalera de Madera",
        "065": "Calculadora Barandilla Metálica",
        "066": "Calculadora Estructura Metálica",
        "067": "Calculadora Puerta Metálica – kg Acero",
        "068": "Calculadora Vidrios – m² y kg",
        "069": "Calculadora Pintura Paredes – Litros",
        "070": "Calculadora Pintura Techo – Litros",
        "071": "Calculadora Esmalte – Madera y Metal",
        "072": "Calculadora Barniz Exterior – Litros",
        "073": "¿Cuántos Rollos de Papel Pintado?",
        "074": "Calculadora Textura Paredes – kg",
        "075": "Calculadora Imprimación – Litros",
        "076": "Calculadora Masilla – kg Paredes",
        "077": "Calculadora Lija – Hojas por m²",
        "078": "Calculadora Presupuesto Reforma – m²",
        "079": "Calculadora Precio Hora Autónomo",
        "080": "Calculadora Amortización Equipos",
        "081": "Calculadora Amortización Vehículo",
        "082": "Calculadora Coste Combustible – Obra",
        "083": "Calculadora Dietas Autónomo",
        "084": "Calculadora Contenedor Escombros",
        "085": "Calculadora Andamio – Coste m²",
        "086": "Calculadora Limpieza Final Obra",
        "087": "Calculadora Seguro RC Autónomos",
        "088": "Calculadora EPI Obra – Coste",
        "089": "Calculadora Señalización de Obra",
        "090": "Calculadora Rendimiento Obra – m²/día",
        "091": "Planificación Obra – Duración Semanas",
        "092": "Calculadora Licencia de Obras",
        "093": "Calculadora IRPF IVA Autónomo",
        "094": "Calculadora Financiación Equipos",
        "095": "Calculadora Margen de Beneficio",
        "096": "Calculadora Punto de Equilibrio",
        "097": "Calculadora Agua en Obra – Litros",
        "098": "Calculadora Factor de Merma",
        "099": "Calculadora Coste Mano de Obra",
        "100": "Calculadora ROI Herramienta",
    },
    "fr": {
        "001": "Calculateur Béton – Ciment et Gravier",
        "002": "Calculateur Béton Armé – Acier",
        "003": "Calculateur Semelle Isolée – Béton",
        "004": "Calculateur Mur de Soutènement",
        "005": "Calculateur Poteau Béton – Matériaux",
        "006": "Calculateur Poutre Béton – Volume",
        "007": "Calculateur Plancher Hourdis",
        "008": "Calculateur Dalle Pleine – Volume",
        "009": "Calculateur Semelle Filante",
        "010": "Calculateur Terrassement – Volume",
        "011": "Combien de Briques? – Calculateur",
        "012": "Calculateur Brique de Parement",
        "013": "Calculateur Bloc Béton – Mortier",
        "014": "Calculateur Placo – Plaques et Rails",
        "015": "Calculateur Isolation – EPS et Laine",
        "016": "Calculateur Enduit Projeté – kg",
        "017": "Calculateur Mortier de Ciment",
        "018": "Calculateur Enduit – Ciment ou Plâtre",
        "019": "Calculateur Maçonnerie Pierre",
        "020": "Combien de Tuiles? – Calculateur",
        "021": "Combien de Carrelage? – Calculateur",
        "022": "Calculateur Carrelage Sol – Boîtes",
        "023": "Calculateur Parquet Laminé – Boîtes",
        "024": "Calculateur Parquet Massif – Boîtes",
        "025": "Calculateur Marbre Granit – m²",
        "026": "Calculateur Terrazzo – Pièces",
        "027": "Combien de Carreaux Mur? Online",
        "028": "Calculateur Mosaïque – Treillis",
        "029": "Calculateur Colle Carrelage C1 C2",
        "030": "Calculateur Joint Carrelage – kg",
        "031": "Calculateur Tuyaux PVC – Évacuation",
        "032": "Calculateur Cuivre PEX – Plomberie",
        "033": "Calculateur Pression Eau – Bar PSI",
        "034": "Calculateur Cuve – Litres Requis",
        "035": "Calculateur Chauffe-eau Électrique",
        "036": "Calculateur Chaudière Gaz – kW",
        "037": "Combien d'Éléments de Radiateur?",
        "038": "Calculateur Plancher Chauffant",
        "039": "Calculateur Irrigation Goutte-à-Goutte",
        "040": "Calculateur Tuyaux Plomberie – DN",
        "041": "Calculateur Filtre Piscine – Pompe",
        "042": "Calculateur Colonne de Chute",
        "043": "Calculateur Section Câble – mm²",
        "044": "Calculateur Chute de Tension – %",
        "045": "Calculateur Lumens LED – Pièce",
        "046": "Combien de Points Lumineux? Online",
        "047": "Calculateur Tableau Électrique",
        "048": "Calculateur Panneaux Solaires – kWp",
        "049": "Calculateur Batteries Solaires – kWh",
        "050": "Calculateur Triphasé – kW et kVA",
        "051": "Calculateur Mise à la Terre",
        "052": "Calculateur Consommation Électrique",
        "053": "Calculateur Climatiseur BTU",
        "054": "Calculateur Gaines CVCA – Diamètre",
        "055": "Calculateur Ventilation – m³/h",
        "056": "Calculateur Pompe à Chaleur – kW",
        "057": "Calculateur COP EER – Efficacité",
        "058": "Dimensionnement Gaines – Perte Charge",
        "059": "Calculateur Grilles de Ventilation",
        "060": "Calculateur Fluide Frigorigène R32",
        "061": "Calculateur Fenêtres PVC Aluminium",
        "062": "Calculateur Portes Intérieures",
        "063": "Calculateur Portes Coulissantes",
        "064": "Calculateur Escalier Bois",
        "065": "Calculateur Garde-Corps Métal",
        "066": "Calculateur Charpente Métallique",
        "067": "Calculateur Portail Métal – kg Acier",
        "068": "Calculateur Vitrage – m² et kg",
        "069": "Calculateur Peinture Murs – Litres",
        "070": "Calculateur Peinture Plafond – Litres",
        "071": "Calculateur Laque – Bois et Métal",
        "072": "Calculateur Vernis Bois – Litres",
        "073": "Combien de Rouleaux Papier Peint?",
        "074": "Calculateur Enduit Décoratif – kg",
        "075": "Calculateur Primaire – Litres",
        "076": "Calculateur Enduit de Lissage – kg",
        "077": "Calculateur Papier de Verre – Feuilles",
        "078": "Calculateur Budget Rénovation – m²",
        "079": "Calculateur Tarif Horaire Artisan",
        "080": "Calculateur Amortissement Matériel",
        "081": "Calculateur Amortissement Véhicule",
        "082": "Calculateur Coût Carburant – Chantier",
        "083": "Calculateur Frais de Déplacement",
        "084": "Calculateur Benne à Gravats",
        "085": "Calculateur Échafaudage – Location",
        "086": "Calculateur Nettoyage Fin de Chantier",
        "087": "Calculateur Assurance RC Artisan",
        "088": "Calculateur EPI Chantier – Coût",
        "089": "Calculateur Signalisation Chantier",
        "090": "Calculateur Rendement Chantier",
        "091": "Planification Chantier – Semaines",
        "092": "Calculateur Permis de Construire",
        "093": "Calculateur TVA Auto-Entrepreneur",
        "094": "Calculateur Crédit Matériel",
        "095": "Calculateur Marge Bénéficiaire",
        "096": "Calculateur Point Mort – Auto-Entrepreneur",
        "097": "Calculateur Eau de Chantier – Litres",
        "098": "Calculateur Coefficient de Perte",
        "099": "Calculateur Coût Main-d'Œuvre",
        "100": "Calculateur ROI Outillage",
    },
    "pt": {
        "001": "Calculadora Concreto – Cimento e Brita",
        "002": "Calculadora Concreto Armado – Aço",
        "003": "Calculadora Sapata Isolada",
        "004": "Calculadora Muro de Arrimo",
        "005": "Calculadora Pilar de Concreto",
        "006": "Calculadora Viga de Concreto",
        "007": "Calculadora Laje Treliçada",
        "008": "Calculadora Laje Maciça – Volume",
        "009": "Calculadora Sapata Corrida",
        "010": "Calculadora Escavação – Volume",
        "011": "Quantos Tijolos Preciso? Online",
        "012": "Calculadora Tijolo Aparente",
        "013": "Calculadora Bloco de Concreto",
        "014": "Calculadora Drywall – Chapas e Perfis",
        "015": "Calculadora Isolamento – EPS e Lã",
        "016": "Calculadora Reboco Projetado – kg",
        "017": "Calculadora Argamassa de Cimento",
        "018": "Calculadora Reboco – Cimento ou Gesso",
        "019": "Calculadora Alvenaria de Pedra",
        "020": "Quantas Telhas Preciso? Online",
        "021": "Quantos Porcelanatos Preciso? Online",
        "022": "Calculadora Porcelanato – Caixas",
        "023": "Calculadora Piso Laminado – Caixas",
        "024": "Calculadora Piso de Madeira – Caixas",
        "025": "Calculadora Mármore e Granito – m²",
        "026": "Calculadora Granilite – Peças",
        "027": "Quantos Revestimentos Preciso? Online",
        "028": "Calculadora Mosaico – Malhas",
        "029": "Calculadora Cola Cerâmica C1 C2",
        "030": "Calculadora Rejunte – kg por m²",
        "031": "Calculadora Tubos PVC – Esgoto",
        "032": "Calculadora Tubos Cobre PEX",
        "033": "Calculadora Pressão de Água – Bar",
        "034": "Calculadora Caixa d'Água – Litros",
        "035": "Calculadora Aquecedor Elétrico – kW",
        "036": "Calculadora Caldeira Gás – kW",
        "037": "Quantos Elementos de Radiador? Online",
        "038": "Calculadora Piso Aquecido – Tubos",
        "039": "Calculadora Irrigação Gotejamento",
        "040": "Calculadora Tubulação – Diâmetro DN",
        "041": "Calculadora Filtro Piscina – Bomba",
        "042": "Calculadora Coluna de Queda",
        "043": "Calculadora Seção Cabo – mm²",
        "044": "Calculadora Queda de Tensão – %",
        "045": "Calculadora Lumens LED – Iluminação",
        "046": "Quantos Pontos de Luz Preciso?",
        "047": "Calculadora Quadro Elétrico",
        "048": "Calculadora Painéis Solares – kWp",
        "049": "Calculadora Baterias Solares – kWh",
        "050": "Calculadora Trifásica – kW e kVA",
        "051": "Calculadora Aterramento Elétrico",
        "052": "Calculadora Consumo Elétrico – kWh",
        "053": "Calculadora Ar-Condicionado BTU",
        "054": "Calculadora Dutos de Ar – Diâmetro",
        "055": "Calculadora Ventilação Mecânica – m³/h",
        "056": "Calculadora Bomba de Calor – kW",
        "057": "Calculadora COP e EER – Eficiência",
        "058": "Dimensionamento Dutos HVAC",
        "059": "Calculadora Grelhas Ventilação",
        "060": "Calculadora Gás Refrigerante R32 R410A",
        "061": "Calculadora Janelas PVC Alumínio",
        "062": "Calculadora Portas Internas",
        "063": "Calculadora Portas de Correr",
        "064": "Calculadora Escada de Madeira",
        "065": "Calculadora Corrimão Metálico",
        "066": "Calculadora Estrutura Metálica",
        "067": "Calculadora Portão Metálico – kg Aço",
        "068": "Calculadora Vidros – m² e kg",
        "069": "Calculadora Tinta Parede – Litros",
        "070": "Calculadora Tinta Teto – Litros",
        "071": "Calculadora Esmalte – Madeira e Metal",
        "072": "Calculadora Verniz Externo – Litros",
        "073": "Quantos Rolos de Papel de Parede?",
        "074": "Calculadora Textura Parede – kg",
        "075": "Calculadora Selador – Litros",
        "076": "Calculadora Massa Corrida – kg",
        "077": "Calculadora de Lixas – Folhas",
        "078": "Calculadora Orçamento Reforma – m²",
        "079": "Calculadora Preço Hora Autônomo",
        "080": "Calculadora Depreciação Equipamentos",
        "081": "Calculadora Depreciação Veículo",
        "082": "Calculadora Custo Combustível – Obra",
        "083": "Calculadora Diárias Autônomo",
        "084": "Calculadora Caçamba Entulho",
        "085": "Calculadora Andaime – Custo m²",
        "086": "Calculadora Limpeza Final de Obra",
        "087": "Calculadora Seguro RC Obras",
        "088": "Calculadora EPI Construção – Custo",
        "089": "Calculadora Sinalização de Obra",
        "090": "Calculadora Rendimento Obra – m²/dia",
        "091": "Cronograma de Obra – Semanas",
        "092": "Calculadora Alvará de Obras",
        "093": "Calculadora ISS IRPF Autônomo",
        "094": "Calculadora Financiamento Equipamento",
        "095": "Calculadora Margem de Lucro",
        "096": "Calculadora Ponto de Equilíbrio",
        "097": "Calculadora Água em Obra – Litros",
        "098": "Calculadora Fator de Perda",
        "099": "Calculadora Custo Mão de Obra",
        "100": "Calculadora ROI Ferramenta",
    },
    "de": {
        "001": "Betonrechner – Zement und Kies",
        "002": "Stahlbetonrechner – Bewehrung",
        "003": "Einzelfundament-Rechner",
        "004": "Stützmauer-Rechner – Beton",
        "005": "Betonstützen-Rechner",
        "006": "Betonträger-Rechner",
        "007": "Rippendecken-Rechner",
        "008": "Flachdecken-Rechner – Beton",
        "009": "Streifenfundament-Rechner",
        "010": "Erdarbeiten-Rechner",
        "011": "Wie Viele Ziegel Brauche Ich? Online",
        "012": "Klinker-Rechner – Materialien",
        "013": "Betonstein-Rechner – Mörtel",
        "014": "Trockenbau-Rechner – Platten",
        "015": "Wärmedämmung-Rechner – EPS",
        "016": "Aufgespritzter-Putz-Rechner",
        "017": "Zementmörtel-Rechner",
        "018": "Putz-Rechner – Zement oder Gips",
        "019": "Naturstein-Mauerwerk-Rechner",
        "020": "Wie Viele Dachziegel Brauche Ich?",
        "021": "Wie Viele Fliesen Brauche Ich? Online",
        "022": "Feinsteinzeug-Rechner – Kartons",
        "023": "Laminatboden-Rechner – Kartons",
        "024": "Parkett-Rechner – Kartons",
        "025": "Marmor-Granit-Rechner – m²",
        "026": "Terrazzo-Rechner – Stücke",
        "027": "Wie Viele Wandfliesen? Online",
        "028": "Mosaik-Rechner – Matten",
        "029": "Fliesenkleber-Rechner C1 C2",
        "030": "Fugenmörtel-Rechner – kg",
        "031": "PVC-Rohr-Rechner – Abwasser",
        "032": "Kupfer-PEX-Rohr-Rechner",
        "033": "Wasserdruck-Rechner – Bar PSI",
        "034": "Wassertank-Rechner – Liter",
        "035": "Warmwasserbereiter-Rechner",
        "036": "Gasheizkessel-Rechner – kW",
        "037": "Wie Viele Heizkörper-Elemente?",
        "038": "Fußbodenheizung-Rechner",
        "039": "Tropfbewässerungs-Rechner",
        "040": "Rohrdimensionierung – DN",
        "041": "Schwimmbadfilter-Rechner",
        "042": "Fallrohr-Rechner",
        "043": "Kabelquerschnitt-Rechner – mm²",
        "044": "Spannungsfall-Rechner – %",
        "045": "Lumen-Rechner – LED Beleuchtung",
        "046": "Wie Viele Lichtpunkte? Online",
        "047": "Elektroverteiler-Rechner",
        "048": "Solarmodul-Rechner – kWp",
        "049": "Solarbatterie-Rechner – kWh",
        "050": "Drehstrom-Rechner – kW kVA",
        "051": "Erdungsanlage-Rechner",
        "052": "Stromverbrauch-Rechner – kWh",
        "053": "Klimaanlage-Rechner BTU",
        "054": "Kanalquerschnitt-Rechner",
        "055": "Lüftungsanlage-Rechner – m³/h",
        "056": "Wärmepumpe-Rechner – kW",
        "057": "COP-EER-Rechner – Effizienz",
        "058": "HLK-Kanalrechner – Druckverlust",
        "059": "Lüftungsgitter-Rechner",
        "060": "Kältemittel-Rechner R32 R410A",
        "061": "Fenster-Rechner PVC Aluminium",
        "062": "Innentür-Rechner",
        "063": "Schiebetür-Rechner",
        "064": "Holztreppe-Rechner",
        "065": "Geländer-Rechner",
        "066": "Stahlbau-Rechner",
        "067": "Metalltor-Rechner – kg Stahl",
        "068": "Verglasung-Rechner – m² und kg",
        "069": "Wandfarbe-Rechner – Liter",
        "070": "Deckenfarbe-Rechner – Liter",
        "071": "Lack-Rechner – Holz und Metall",
        "072": "Holzlasur-Rechner – Liter",
        "073": "Wie Viele Tapeten-Rollen? Online",
        "074": "Strukturputz-Rechner – kg",
        "075": "Grundierung-Rechner – Liter",
        "076": "Spachtel-Rechner – kg",
        "077": "Schleifpapier-Rechner",
        "078": "Renovierungsbudget-Rechner",
        "079": "Stundensatz-Rechner",
        "080": "Abschreibung-Ausrüstung-Rechner",
        "081": "Fahrzeug-Abschreibung-Rechner",
        "082": "Kraftstoffkosten-Rechner",
        "083": "Tagegeld-Rechner",
        "084": "Container-Rechner",
        "085": "Gerüst-Rechner – Kosten m²",
        "086": "Baureinigung-Rechner",
        "087": "Haftpflicht-Versicherung-Rechner",
        "088": "PSA-Kosten-Rechner",
        "089": "Baustellenschilder-Rechner",
        "090": "Bauproduktivität-Rechner",
        "091": "Bauzeitenplan – Wochen",
        "092": "Baugenehmigung-Rechner",
        "093": "MwSt-Einkommensteuer-Rechner",
        "094": "Anlagenfinanzierung-Rechner",
        "095": "Gewinnspanne-Rechner",
        "096": "Break-Even-Rechner",
        "097": "Wasserverbrauch-Rechner",
        "098": "Abfallkoeffizient-Rechner",
        "099": "Arbeitskosten-Rechner",
        "100": "Werkzeug-ROI-Rechner",
    },
    "it": {
        "001": "Calcolatore Calcestruzzo – Cemento",
        "002": "Calcolatore Cemento Armato",
        "003": "Calcolatore Platea – Calcestruzzo",
        "004": "Calcolatore Muro di Contenimento",
        "005": "Calcolatore Pilastri – Calcestruzzo",
        "006": "Calcolatore Travi in Cemento",
        "007": "Calcolatore Solaio a Travetti",
        "008": "Calcolatore Soletta Piena",
        "009": "Calcolatore Fondazione Continua",
        "010": "Calcolatore Scavo – Volume",
        "011": "Quanti Mattoni Servono? Online",
        "012": "Calcolatore Mattoni a Vista",
        "013": "Calcolatore Blocchi Cemento",
        "014": "Calcolatore Cartongesso – Lastre",
        "015": "Calcolatore Isolamento – EPS e Lana",
        "016": "Calcolatore Intonaco Proiettato",
        "017": "Calcolatore Malta Cementizia",
        "018": "Calcolatore Intonaco – Cemento Gesso",
        "019": "Calcolatore Muratura in Pietra",
        "020": "Quante Tegole Servono? Online",
        "021": "Quante Piastrelle Servono? Online",
        "022": "Calcolatore Gres Porcellanato",
        "023": "Calcolatore Pavimento Laminato",
        "024": "Calcolatore Parquet – Confezioni",
        "025": "Calcolatore Marmo e Granito – m²",
        "026": "Calcolatore Graniglia – Pezzi",
        "027": "Quante Piastrelle Bagno? Online",
        "028": "Calcolatore Mosaico – Reti",
        "029": "Calcolatore Colla Ceramica C1 C2",
        "030": "Calcolatore Stucco – kg per m²",
        "031": "Calcolatore Tubi PVC – Scarico",
        "032": "Calcolatore Tubi Rame PEX",
        "033": "Calcolatore Pressione Acqua – Bar",
        "034": "Calcolatore Cisterna – Litri",
        "035": "Calcolatore Scaldabagno Elettrico",
        "036": "Calcolatore Caldaia Gas – kW",
        "037": "Quanti Elementi Radiatore? Online",
        "038": "Calcolatore Riscaldamento a Pavimento",
        "039": "Calcolatore Irrigazione a Goccia",
        "040": "Calcolatore Tubazioni – Diametro",
        "041": "Calcolatore Filtro Piscina",
        "042": "Calcolatore Colonna di Scarico",
        "043": "Calcolatore Sezione Cavo – mm²",
        "044": "Calcolatore Caduta di Tensione",
        "045": "Calcolatore Lumen LED – Stanza",
        "046": "Quanti Punti Luce Servono?",
        "047": "Calcolatore Quadro Elettrico",
        "048": "Calcolatore Pannelli Solari – kWp",
        "049": "Calcolatore Batterie Solari – kWh",
        "050": "Calcolatore Trifase – kW e kVA",
        "051": "Calcolatore Impianto di Terra",
        "052": "Calcolatore Consumo Elettrico",
        "053": "Calcolatore Climatizzatore BTU",
        "054": "Calcolatore Condotti Aria – Diametro",
        "055": "Calcolatore Ventilazione – m³/h",
        "056": "Calcolatore Pompa di Calore – kW",
        "057": "Calcolatore COP EER – Efficienza",
        "058": "Dimensionamento Canali HVAC",
        "059": "Calcolatore Griglie Ventilazione",
        "060": "Calcolatore Refrigerante R32 R410A",
        "061": "Calcolatore Finestre PVC Alluminio",
        "062": "Calcolatore Porte Interne",
        "063": "Calcolatore Porte Scorrevoli",
        "064": "Calcolatore Scala in Legno",
        "065": "Calcolatore Ringhiera Metallica",
        "066": "Calcolatore Struttura Metallica",
        "067": "Calcolatore Cancello in Metallo",
        "068": "Calcolatore Vetri – m² e kg",
        "069": "Calcolatore Vernice Pareti – Litri",
        "070": "Calcolatore Vernice Soffitto – Litri",
        "071": "Calcolatore Smalto – Legno e Metallo",
        "072": "Calcolatore Verniciatura Legno",
        "073": "Quanti Rotoli Tappezzeria? Online",
        "074": "Calcolatore Intonachino – kg",
        "075": "Calcolatore Primer – Litri",
        "076": "Calcolatore Rasatura – kg Pareti",
        "077": "Calcolatore Carta Abrasiva",
        "078": "Calcolatore Budget Ristrutturazione",
        "079": "Calcolatore Tariffa Oraria",
        "080": "Calcolatore Ammortamento Attrezzatura",
        "081": "Calcolatore Ammortamento Veicolo",
        "082": "Calcolatore Costo Carburante",
        "083": "Calcolatore Trasferte Lavoro",
        "084": "Calcolatore Noleggio Container",
        "085": "Calcolatore Ponteggio – Costo m²",
        "086": "Calcolatore Pulizia Fine Lavori",
        "087": "Calcolatore Assicurazione RC",
        "088": "Calcolatore DPI Cantiere – Costo",
        "089": "Calcolatore Segnaletica Cantiere",
        "090": "Calcolatore Resa Cantiere – m²/giorno",
        "091": "Cronoprogramma Lavori – Settimane",
        "092": "Calcolatore Permesso di Costruire",
        "093": "Calcolatore IRPEF IVA Autonomo",
        "094": "Calcolatore Finanziamento Attrezzatura",
        "095": "Calcolatore Margine di Profitto",
        "096": "Calcolatore Break-Even",
        "097": "Calcolatore Acqua in Cantiere",
        "098": "Calcolatore Fattore di Spreco",
        "099": "Calcolatore Costo Manodopera",
        "100": "Calcolatore ROI Attrezzatura",
    },
}


def patch_json(lang: str, titles: dict) -> None:
    path = I18N / f"{lang}.json"
    with open(path, encoding="utf-8") as f:
        data = json.load(f)

    calcs = data.get("calculators", data)
    updated = 0
    too_long = []

    for calc_id, new_title in titles.items():
        if calc_id in calcs and isinstance(calcs[calc_id], dict):
            calcs[calc_id]["seo_title"] = new_title
            updated += 1
            full_len = len(new_title) + len(" | CalcToWork")
            if full_len > 60:
                too_long.append(f"  {calc_id}: [{full_len}] {new_title}")

    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"[{lang.upper()}] Updated {updated}/100 titles.")
    if too_long:
        print(f"  WARNING – {len(too_long)} titles still >60 chars rendered:")
        for t in too_long:
            print(t)


if __name__ == "__main__":
    for lang, titles in NEW_TITLES.items():
        patch_json(lang, titles)
    print("\nDone. Run: python scripts/generate_calctowork.py")
